const $=id=>document.getElementById(id);
const FINISHED_STATUSES=new Set(['FT','AET','PEN','CANC','ABD','AWD','WO']);
const state={matches:[],analyses:[],mode:'CACHE',meta:null,filter:'signals',sort:'rank'};
let backgroundRefreshBusy=false,refreshTimer=null;
const PREMATCH_REFRESH_MS=5*60*1000,LIVE_REFRESH_MS=60*1000,LATE_LIVE_REFRESH_MS=45*1000,SAFE_LIVE_REFRESH_MS=90*1000,MANUAL_SCAN_TIMEOUT_MS=42000;

function cleanupNavDuplicates(){const links=[...document.querySelectorAll('a[href="compte-rendu-des-predictions.html"]')];if(links.length>1)links.slice(0,-1).forEach(a=>a.remove())}cleanupNavDuplicates();
function tickClock(){const el=$('clock');if(el)el.textContent=new Date().toLocaleTimeString([],{hour12:false})}setInterval(tickClock,1000);tickClock();
function finite(v){return Number.isFinite(Number(v))?Number(v):null}
function isPastMatch(m,a){return Boolean(m?.isFinished||FINISHED_STATUSES.has(m?.status)||a?.phase==='FINISHED')}
function kickoffText(m){if(m?.isLive)return`LIVE ${m.minute||0}'`;if(FINISHED_STATUSES.has(m?.status))return'FINAL';if(m?.kickoff)return new Date(m.kickoff).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return m?.statusLong||m?.status||'PRE-MATCH'}
function probabilityText(v){const n=finite(v);return n==null?'—':`${(n*100).toFixed(1)}%`}
function scoreText(v){const n=finite(v);return n==null?'—':`${n.toFixed(0)}/100`}
function oddsText(v){const n=finite(v);return n&&n>1?n.toFixed(2):'—'}
function edgeText(v){const n=finite(v);return n==null?'—':`${n>=0?'+':''}${n.toFixed(1)} pp`}
function evText(v){const n=finite(v);return n==null?'—':`${n>=0?'+':''}${n.toFixed(1)}%`}
function confidenceLabel(v){const n=finite(v)||0;return n>=75?'High':n>=55?'Medium':'Low'}
function betLabel(a){const m=String(a?.bestMarket||'').toUpperCase();if(m==='HOME')return'Home team to win';if(m==='DRAW')return'Draw';if(m==='AWAY')return'Away team to win';if(m&&!['NO MARKET','MODEL PENDING','NO BET'].includes(m))return a.bestMarket;return'No bet'}
function signalType(m,a){if(isPastMatch(m,a))return'past';const c=String(a?.classification||'').toUpperCase();if(c.includes('PRIME'))return'prime';if(c.includes('STRONG VALUE'))return'strong-value';if(c.includes('VALUE'))return'value';if(c.includes('WATCH'))return'watch';return'no-bet'}
function rankValue(t){return({prime:5,'strong-value':4,value:3,watch:2,'no-bet':1,past:0})[t]||0}
function edgeNumber(a){return finite(a?.edge)??-999}
function kickoffNumber(m){return Number(m?.timestamp)||(m?.kickoff?new Date(m.kickoff).getTime()/1000:Number.MAX_SAFE_INTEGER)}
function verdictName(t){return t==='prime'?'PRIME':(t==='strong-value'||t==='value')?'VALUE':t==='watch'?'WATCH':'NO BET'}
function verdictHuman(t){return t==='prime'?'Highest-quality eligible signal':(t==='strong-value'||t==='value')?'Positive value after gates':t==='watch'?'Needs more confirmation':'Not eligible'}
function actionLabel(t){return t==='prime'?'REVIEW NOW':(t==='strong-value'||t==='value')?'REVIEW':t==='watch'?'WAIT':'SKIP'}
function providerState(meta=state.meta){if(meta?.staleFallback)return'STALE · NO BET';if(meta?.providerStatus==='RATE_LIMITED')return'RATE LIMITED';if(meta?.providerStatus==='DAILY_EXHAUSTED')return'QUOTA PAUSED';if(meta?.degraded)return'DEGRADED';return meta?.clientCache?'CACHE READY':'CONNECTED'}
function reasonText(m,a){if(isPastMatch(m,a))return'Match finished.';if(a?.integrityBlocker)return`Blocked by integrity gate: ${String(a.integrityBlocker).replaceAll('_',' ')}.`;if(m?.dataStale||state.meta?.actionableData===false)return'Data are visible for context only; this snapshot is too stale or degraded for an actionable decision.';if(!a?.marketAvailable)return'The current evidence or market price is not strong enough for an eligible decision.';if(finite(a?.conservativeEV)>0)return m?.isLive?'The official live snapshot still shows positive expected value, subject to freshness and validation gates.':'The official model sees positive expected value at the current price.';if(signalType(m,a)==='watch')return'Promising, but ARGUS requires more confirmation before eligibility.';return'The current price does not offer enough verified value.'}
function rowsWithTypes(){return state.matches.map((match,index)=>({match,analysis:state.analyses[index]||{},type:signalType(match,state.analyses[index]),index}))}
function sortRows(rows){return rows.slice().sort((a,b)=>state.sort==='confidence'?(finite(b.analysis?.confidence)||0)-(finite(a.analysis?.confidence)||0):state.sort==='edge'?edgeNumber(b.analysis)-edgeNumber(a.analysis):state.sort==='kickoff'?kickoffNumber(a.match)-kickoffNumber(b.match):state.sort==='live'?Number(Boolean(b.match?.isLive))-Number(Boolean(a.match?.isLive))||rankValue(b.type)-rankValue(a.type):rankValue(b.type)-rankValue(a.type)||(finite(b.analysis?.confidence)||0)-(finite(a.analysis?.confidence)||0)||edgeNumber(b.analysis)-edgeNumber(a.analysis)||kickoffNumber(a.match)-kickoffNumber(b.match))}
function activeRows(){return rowsWithTypes().filter(r=>r.type!=='past')}
function actionableRows(){return sortRows(activeRows().filter(r=>['prime','strong-value','value','watch'].includes(r.type)))}
function filteredRows(){let rows=rowsWithTypes();if(state.filter==='past')rows=rows.filter(r=>r.type==='past');else{rows=rows.filter(r=>r.type!=='past');if(state.filter==='signals')rows=rows.filter(r=>['prime','strong-value','value','watch'].includes(r.type));else if(state.filter==='value')rows=rows.filter(r=>['value','strong-value'].includes(r.type));else if(state.filter!=='all')rows=rows.filter(r=>r.type===state.filter)}return sortRows(rows)}
function metricValues(a){return{p:a?.outcomeProbability??a?.conservativeProbability??a?.shrunkProbability??a?.rawProbability,confidence:a?.decisionConfidence??a?.confidence,edge:a?.edge,ev:a?.conservativeEV,fair:a?.fairOdds,odds:a?.marketOdds}}
function updateQuota(meta){const q=meta?.quota||{},remaining=finite(q.dailyRemaining),limit=finite(q.dailyLimit),reserve=finite(q.dynamicReserve),text=remaining==null?'—':limit!=null?`${remaining}/${limit}`:String(remaining);if($('requestQuota'))$('requestQuota').textContent=text;if($('heroQuota'))$('heroQuota').textContent=text;const threshold=reserve??(limit?Math.max(80,Math.ceil(limit*.02)):80),safe=remaining!=null&&remaining<=threshold;if($('safeModeChip'))$('safeModeChip').classList.toggle('visible',safe)}
function updateHistoryCoverage(meta){if($('historyCoverage'))$('historyCoverage').textContent=meta?.historyTeamsCovered!=null&&meta?.historyTeamsTotal!=null?`${meta.historyTeamsCovered}/${meta.historyTeamsTotal}`:'—'}
function updateGovernanceStatus(){const s=window.ArgusGovernance?.systemStatus?.();if($('calibrationStatus'))$('calibrationStatus').textContent=s?.calibration||'UNKNOWN';if($('primeGateStatus'))$('primeGateStatus').textContent=s?.primeGate||'UNKNOWN';if($('trackRecordCount'))$('trackRecordCount').textContent=window.ArgusTrackRecord?.count?.()??0}
function metricStrip(a){const m=metricValues(a);return`<div class="opp-metrics"><div><span>Outcome probability</span><strong>${probabilityText(m.p)}</strong></div><div><span>Decision confidence</span><strong>${scoreText(m.confidence)}</strong></div><div><span>Model edge</span><strong>${edgeText(m.edge)}</strong></div><div><span>Expected value</span><strong>${evText(m.ev)}</strong></div></div>`}
function opportunityCard(row,isTop=false){const{match,analysis,type,index}=row,m=metricValues(analysis);return`<article class="opportunity-card ${type} ${isTop?'number-one':''}"><div class="opp-head"><span class="signal-badge ${type}">${isTop?'BEST TODAY · ':''}${verdictName(type)}</span><span>${kickoffText(match)}</span></div><h4>${match.home} <em>vs</em> ${match.away}</h4><div class="bet-block"><span>Suggested decision</span><strong>${betLabel(analysis)}</strong></div>${metricStrip(analysis)}<small>Current odds ${oddsText(m.odds)} · Fair odds ${oddsText(m.fair)}</small><p>${reasonText(match,analysis)}</p><div class="opportunity-actions"><span class="decision-action ${type}">${actionLabel(type)}</span><button class="detail-btn" data-detail-index="${index}">Why?</button></div></article>`}
function renderTopOpportunities(){const rows=actionableRows().slice(0,4),top=$('topPick'),grid=$('topOpportunities');if(!top||!grid)return;if(!rows.length){top.className='top-pick empty-pick panel';top.innerHTML='<div class="pick-copy"><span class="pick-kicker">ARGUS VERDICT</span><strong>No eligible opportunity right now</strong><small>ARGUS prefers a verified NO BET to a weak signal.</small></div>';grid.innerHTML='';return}top.className=`top-pick panel ${rows[0].type}`;top.innerHTML=opportunityCard(rows[0],true);grid.innerHTML=rows.slice(1).map(r=>opportunityCard(r)).join('')}
function cardTemplate(m,a,index){const type=signalType(m,a),past=type==='past',x=metricValues(a);if(past)return`<article class="match-card passed panel"><div><h4>${m.home} <span>${m.score?.home??0} — ${m.score?.away??0}</span> ${m.away}</h4></div><div class="passed-tag">Finished</div></article>`;return`<article class="match-card panel ${type}"><div class="match-main"><div class="match-topline"><span>${m.competition||'Match'}${m.country?` · ${m.country}`:''}</span><b>${kickoffText(m)}</b></div><h4>${m.home} <em>vs</em> ${m.away}</h4></div><div class="decision-cell"><span>Suggested decision</span><strong>${betLabel(a)}</strong></div><div class="confidence-cell"><span>Decision confidence</span><strong>${scoreText(x.confidence)} · ${confidenceLabel(x.confidence)}</strong><div class="confidence-bar"><i style="width:${Math.max(0,Math.min(100,finite(x.confidence)||0))}%"></i></div><small>Edge ${edgeText(x.edge)} · EV ${evText(x.ev)}</small></div><div class="signal ${type}"><strong>${verdictName(type)}</strong><small>${verdictHuman(type)}</small><span class="row-action">${actionLabel(type)}</span><button class="detail-btn tiny" data-detail-index="${index}">Details</button></div><div class="analysis-detail" id="detail-${index}"><span>Outcome probability ${probabilityText(x.p)}</span><span>Current odds ${oddsText(x.odds)}</span><span>Fair odds ${oddsText(x.fair)}</span><span>Model edge ${edgeText(x.edge)}</span><span>Expected value ${evText(x.ev)}</span><span>${a.engineStatus||'Engine status unavailable'}</span><span>${a.modelVersion?`Model ${a.modelVersion}`:''}</span><span>${a.validationStatus?`Validation ${a.validationStatus}`:''}</span></div></article>`}
function bindButtons(){document.querySelectorAll('[data-detail-index]').forEach(btn=>btn.addEventListener('click',()=>{const el=$(`detail-${btn.dataset.detailIndex}`);if(el)el.classList.toggle('open');else{state.filter='all';renderBoard();setTimeout(()=>{const d=$(`detail-${btn.dataset.detailIndex}`);d?.classList.add('open');d?.scrollIntoView({behavior:'smooth',block:'center'})},0)}}))}
function updateCounts(){const rows=rowsWithTypes(),active=rows.filter(r=>r.type!=='past'),prime=active.filter(r=>r.type==='prime').length,value=active.filter(r=>['value','strong-value'].includes(r.type)).length,watch=active.filter(r=>r.type==='watch').length,noBet=active.filter(r=>r.type==='no-bet').length,past=rows.filter(r=>r.type==='past').length;if($('signalCount'))$('signalCount').textContent=prime+value+watch;if($('primeFilterCount'))$('primeFilterCount').textContent=prime;if($('valueFilterCount'))$('valueFilterCount').textContent=value;if($('watchFilterCount'))$('watchFilterCount').textContent=watch;if($('noBetFilterCount'))$('noBetFilterCount').textContent=noBet;if($('allFilterCount'))$('allFilterCount').textContent=active.length;if($('pastFilterCount'))$('pastFilterCount').textContent=past;if($('heroAnalysed'))$('heroAnalysed').textContent=active.length;if($('heroPrime'))$('heroPrime').textContent=prime;if($('heroWatch'))$('heroWatch').textContent=watch;if($('todayCounts'))$('todayCounts').textContent=`${prime} prime · ${value} value · ${watch} watch`;const best=actionableRows()[0];if($('strongestSignal'))$('strongestSignal').textContent=best?`${best.match.home} vs ${best.match.away} · ${betLabel(best.analysis)} · ${scoreText(best.analysis?.decisionConfidence??best.analysis?.confidence)} decision confidence`:'No eligible opportunity right now.'}
function renderBoard(){updateCounts();renderTopOpportunities();const grid=$('matchGrid'),rows=filteredRows();if(!grid)return;if(!state.matches.length){grid.innerHTML='<div class="empty-state"><strong>Ready to check today</strong><span>ARGUS will review the available matches and surface only decisions that survive the integrity gates.</span></div>';return}if(!rows.length){grid.innerHTML='<div class="empty-state"><strong>Nothing strong enough here</strong><span>ARGUS prefers waiting to forcing a weak decision.</span></div>';return}grid.innerHTML=rows.map(r=>cardTemplate(r.match,r.analysis,r.index)).join('');bindButtons()}
function render(){updateQuota(state.meta);updateHistoryCoverage(state.meta);updateGovernanceStatus();const stamp=state.meta?.fetchedAt?new Date(state.meta.fetchedAt):null,t=stamp?stamp.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';if($('heroUpdate'))$('heroUpdate').textContent=t;if($('lastUpdate'))$('lastUpdate').textContent=stamp?`Observed ${t}${state.meta?.clientCache?' · cached':''}${state.meta?.staleFallback?' · stale':''}`:'Ready to check';if($('liveStatus'))$('liveStatus').textContent=providerState();renderBoard();scheduleNextRefresh()}
function analyzeMatches(matches,meta=null){state.matches=matches;state.meta=meta;state.analyses=matches.map(m=>{const base=window.ArgusEngine.analyze(m);return window.ArgusGovernance?window.ArgusGovernance.apply(base,m):base});render()}
function refreshDelay(){const live=state.matches.filter(m=>m?.isLive);if(!live.length)return PREMATCH_REFRESH_MS;const q=state.meta?.quota||{},remaining=finite(q.dailyRemaining),reserve=finite(q.dynamicReserve),safe=remaining!=null&&reserve!=null&&remaining<=reserve;if(safe)return SAFE_LIVE_REFRESH_MS;return live.some(m=>finite(m.minute)>=80)?LATE_LIVE_REFRESH_MS:LIVE_REFRESH_MS}
function scheduleNextRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshCachedView,refreshDelay())}
function withTimeout(promise,ms,label='REQUEST_TIMEOUT'){let timer;return Promise.race([Promise.resolve(promise),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(label)),ms)})]).finally(()=>clearTimeout(timer))}
function scanErrorMessage(error){const raw=String(error?.message||error||'ANALYSIS_FAILED');if(raw.includes('TIMEOUT'))return'Analysis took too long. ARGUS stopped waiting safely — tap to retry.';return`Analysis failed: ${raw.replaceAll('_',' ').toLowerCase()}. Tap to retry.`}
async function scanToday(){const btn=$('scanBtn');if(btn?.disabled)return;let succeeded=false;if(btn){btn.disabled=true;btn.textContent='Analysing now…'}if($('liveStatus'))$('liveStatus').textContent='ANALYSING';if($('lastUpdate'))$('lastUpdate').textContent='Analysing today’s matches…';try{const task=(async()=>{const matches=await window.ArgusProviders.live({force:true});state.mode=matches.meta?.staleFallback?'STALE':'TODAY';await analyzeMatches(matches,matches.meta||null)})();await withTimeout(task,MANUAL_SCAN_TIMEOUT_MS,'TODAY_ANALYSIS_TIMEOUT');const reviewed=activeRows().length,signals=actionableRows().length;if(!signals&&reviewed&&state.filter==='signals')setFilter('all');if($('liveStatus'))$('liveStatus').textContent=providerState();if($('lastUpdate'))$('lastUpdate').textContent=`Analysis complete · ${reviewed} match${reviewed===1?'':'es'} reviewed${signals?` · ${signals} signal${signals===1?'':'s'}`:' · no eligible bet'}`;if(btn)btn.textContent=`Done · ${reviewed} reviewed`;succeeded=true}catch(e){if($('liveStatus'))$('liveStatus').textContent='ERROR';if($('lastUpdate'))$('lastUpdate').textContent=scanErrorMessage(e);if(!state.matches.length&&$('matchGrid'))$('matchGrid').innerHTML=`<div class="empty-state"><strong>Analysis could not complete</strong><span>${scanErrorMessage(e)}</span></div>`;console.error('ARGUS today analysis failed',e)}finally{if(btn){btn.disabled=false;if(succeeded)setTimeout(()=>{if(!btn.disabled)btn.textContent='Analyse today\'s matches'},1400);else btn.textContent='Retry today\'s analysis'}scheduleNextRefresh()}}
async function detectLiveBackend(){const s=await window.ArgusProviders.health();if(s.meta){updateQuota(s.meta);updateHistoryCoverage(s.meta)}if(Array.isArray(s.matches)&&s.matches.length){const m=s.matches.slice();m.meta=s.meta||null;state.mode=s.stale?'STALE':'CACHE';await analyzeMatches(m,s.meta||null)}else{render();scheduleNextRefresh()}}
async function refreshCachedView(){if(document.hidden||backgroundRefreshBusy||$('scanBtn')?.disabled){scheduleNextRefresh();return}backgroundRefreshBusy=true;try{const matches=await window.ArgusProviders.live({force:false});state.mode=matches.meta?.staleFallback?'STALE':matches.meta?.clientCache?'CACHE':'AUTO';await analyzeMatches(matches,matches.meta||null)}catch(e){console.warn('ARGUS background refresh failed',e)}finally{backgroundRefreshBusy=false;scheduleNextRefresh()}}
function setFilter(f){state.filter=f;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderBoard()}
$('scanBtn')?.addEventListener('click',scanToday);document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('sortSelect')?.addEventListener('change',e=>{state.sort=e.target.value;renderBoard()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshCachedView()});detectLiveBackend();
