const $=id=>document.getElementById(id);const FINISHED_STATUSES=new Set(['FT','AET','PEN','CANC','ABD','AWD','WO']);const state={matches:[],analyses:[],mode:'CACHE',meta:null,filter:'signals',sort:'rank'};
function cleanupNavDuplicates(){const links=[...document.querySelectorAll('a[href="compte-rendu-des-predictions.html"]')];if(links.length>1)links.slice(0,-1).forEach(a=>a.remove())}cleanupNavDuplicates();
function tickClock(){$('clock').textContent=new Date().toLocaleTimeString([],{hour12:false})}setInterval(tickClock,1000);tickClock();
function isPastMatch(m,a){return Boolean(m?.isFinished||FINISHED_STATUSES.has(m?.status)||a?.phase==='FINISHED')}
function kickoffText(m){if(m.isLive)return`LIVE ${m.minute||0}'`;if(FINISHED_STATUSES.has(m.status))return'FINAL';if(m.kickoff)return new Date(m.kickoff).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return m.statusLong||m.status||'PRE-MATCH'}
function pct(v){return Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1)}%`:'—'}
function confidenceLabel(v){const n=Number(v)||0;return n>=75?'High':n>=55?'Medium':'Low'}
function betLabel(a){const m=String(a?.bestMarket||'').toUpperCase();if(m==='HOME')return'Home team to win';if(m==='DRAW')return'Draw';if(m==='AWAY')return'Away team to win';if(m&&!['NO MARKET','MODEL PENDING'].includes(m))return m;return'No bet'}
function signalType(m,a){if(isPastMatch(m,a))return'past';const c=String(a?.classification||'').toUpperCase();if(c.includes('PRIME'))return'prime';if(c.includes('STRONG VALUE'))return'strong-value';if(c.includes('VALUE'))return'value';if(c.includes('WATCH'))return'watch';return'no-bet'}
function rankValue(t){return({prime:5,'strong-value':4,value:3,watch:2,'no-bet':1,past:0})[t]||0}
function edgeNumber(a){return Number.isFinite(Number(a?.edge))?Number(a.edge):-999}
function kickoffNumber(m){return Number(m?.timestamp)||(m?.kickoff?new Date(m.kickoff).getTime()/1000:Number.MAX_SAFE_INTEGER)}
function verdictName(t){return t==='prime'?'PRIME':(t==='strong-value'||t==='value')?'VALUE':t==='watch'?'WATCH':'NO BET'}
function verdictHuman(t){return t==='prime'?'Best opportunity':(t==='strong-value'||t==='value')?'Interesting price':t==='watch'?'Worth monitoring':'Better to skip'}
function actionLabel(t){return t==='prime'?'BET NOW':(t==='strong-value'||t==='value')?'CONSIDER':t==='watch'?'WAIT':'SKIP'}
function reasonText(m,a){if(isPastMatch(m,a))return'Match finished.';if(!a?.marketAvailable)return'The market price is not reliable enough yet.';if(a?.conservativeEV!=null&&Number(a.conservativeEV)>0)return m.isLive?'The live price still looks attractive to ARGUS.':'ARGUS sees more value than the current market price suggests.';if(signalType(m,a)==='watch')return'Promising, but ARGUS wants more confirmation before acting.';return'The current price does not offer enough value.'}
function historyText(m){const h=m.history90d?.home,a=m.history90d?.away;return h&&a?`Recent form: ${Number(h.pointsPerGame||0).toFixed(2)} vs ${Number(a.pointsPerGame||0).toFixed(2)} points/game`:'Recent history is limited'}
function rowsWithTypes(){return state.matches.map((match,index)=>({match,analysis:state.analyses[index],type:signalType(match,state.analyses[index]),index}))}
function sortRows(rows){return rows.slice().sort((a,b)=>state.sort==='confidence'?(Number(b.analysis?.confidence)||0)-(Number(a.analysis?.confidence)||0):state.sort==='edge'?edgeNumber(b.analysis)-edgeNumber(a.analysis):state.sort==='kickoff'?kickoffNumber(a.match)-kickoffNumber(b.match):state.sort==='live'?Number(Boolean(b.match.isLive))-Number(Boolean(a.match.isLive))||rankValue(b.type)-rankValue(a.type):rankValue(b.type)-rankValue(a.type)||(Number(b.analysis?.confidence)||0)-(Number(a.analysis?.confidence)||0)||edgeNumber(b.analysis)-edgeNumber(a.analysis)||kickoffNumber(a.match)-kickoffNumber(b.match))}
function activeRows(){return rowsWithTypes().filter(r=>r.type!=='past')}
function actionableRows(){return sortRows(activeRows().filter(r=>['prime','strong-value','value','watch'].includes(r.type)))}
function filteredRows(){let rows=rowsWithTypes();if(state.filter==='past')rows=rows.filter(r=>r.type==='past');else{rows=rows.filter(r=>r.type!=='past');if(state.filter==='signals')rows=rows.filter(r=>['prime','strong-value','value','watch'].includes(r.type));else if(state.filter==='value')rows=rows.filter(r=>['value','strong-value'].includes(r.type));else if(state.filter!=='all')rows=rows.filter(r=>r.type===state.filter)}return sortRows(rows)}
function updateQuota(meta){const q=meta?.quota,remaining=q?.dailyRemaining,limit=q?.dailyLimit,text=remaining==null?'—':limit!=null?`${remaining}/${limit}`:String(remaining);$('requestQuota').textContent=text;$('heroQuota').textContent=text;const safe=remaining!=null&&Number(remaining)<=10;$('safeModeChip').classList.toggle('visible',safe);if(safe)$('scanBtn').textContent=meta?.clientCache?'Data ready':'Check today'}
function updateHistoryCoverage(meta){$('historyCoverage').textContent=meta?.historyTeamsCovered!=null&&meta?.historyTeamsTotal!=null?`${meta.historyTeamsCovered}/${meta.historyTeamsTotal}`:'—'}
function updateGovernanceStatus(){const s=window.ArgusGovernance?.systemStatus?.();$('calibrationStatus').textContent=s?.calibration||'UNKNOWN';$('primeGateStatus').textContent=s?.primeGate||'UNKNOWN';$('trackRecordCount').textContent=window.ArgusTrackRecord?.count?.()??0}
function opportunityCard(row,isTop=false){const{match,analysis,type,index}=row,edge=Number.isFinite(Number(analysis.edge))?`${Number(analysis.edge)>=0?'+':''}${Number(analysis.edge).toFixed(1)}%`:'—';return`<article class="opportunity-card ${type} ${isTop?'number-one':''}"><div class="opp-head"><span class="signal-badge ${type}">${isTop?'BEST TODAY · ':''}${verdictName(type)}</span><span>${kickoffText(match)}</span></div><h4>${match.home} <em>vs</em> ${match.away}</h4><div class="bet-block"><span>Suggested bet</span><strong>${betLabel(analysis)}</strong></div><div class="opp-metrics"><div><span>Confidence</span><strong>${analysis.confidence||0}% · ${confidenceLabel(analysis.confidence)}</strong></div><div><span>Price value</span><strong>${edge}</strong></div></div><p>${reasonText(match,analysis)}</p><div class="opportunity-actions"><span class="decision-action ${type}">${actionLabel(type)}</span><button class="detail-btn" data-detail-index="${index}">Why?</button></div></article>`}
function renderTopOpportunities(){const rows=actionableRows().slice(0,4),top=$('topPick'),grid=$('topOpportunities');if(!rows.length){top.className='top-pick empty-pick panel';top.innerHTML='<div class="pick-copy"><span class="pick-kicker">ARGUS VERDICT</span><strong>No strong opportunity right now</strong><small>Nothing meets the required standard. The clearest decision is to wait.</small></div>';grid.innerHTML='';return}top.className=`top-pick panel ${rows[0].type}`;top.innerHTML=opportunityCard(rows[0],true);grid.innerHTML=rows.slice(1).map(r=>opportunityCard(r)).join('')}
function cardTemplate(m,a,index){const type=signalType(m,a),past=type==='past',edge=Number.isFinite(Number(a.edge))?`${Number(a.edge)>=0?'+':''}${Number(a.edge).toFixed(1)}%`:'—';if(past)return`<article class="match-card passed panel"><div><h4>${m.home} <span>${m.score?.home??0} — ${m.score?.away??0}</span> ${m.away}</h4></div><div class="passed-tag">Finished</div></article>`;return`<article class="match-card panel ${type}"><div class="match-main"><div class="match-topline"><span>${m.competition||'Match'}${m.country?` · ${m.country}`:''}</span><b>${kickoffText(m)}</b></div><h4>${m.home} <em>vs</em> ${m.away}</h4></div><div class="decision-cell"><span>Suggested bet</span><strong>${betLabel(a)}</strong></div><div class="confidence-cell"><span>Confidence</span><strong>${a.confidence||0}% · ${confidenceLabel(a.confidence)}</strong><div class="confidence-bar"><i style="width:${Math.max(0,Math.min(100,Number(a.confidence)||0))}%"></i></div><small>Price value ${edge}</small></div><div class="signal ${type}"><strong>${verdictName(type)}</strong><small>${verdictHuman(type)}</small><span class="row-action">${actionLabel(type)}</span><button class="detail-btn tiny" data-detail-index="${index}">Details</button></div><div class="analysis-detail" id="detail-${index}"><span>Model ${pct(a.rawProbability)}</span><span>Adjusted ${pct(a.shrunkProbability)}</span><span>Conservative ${pct(a.conservativeProbability)}</span><span>Value ${a.conservativeEV==null?'—':`${a.conservativeEV}%`}</span><span>${a.engineStatus||'Engine status unavailable'}</span><span>${a.shrinkageStatus||''}</span></div></article>`}
function bindButtons(){document.querySelectorAll('[data-detail-index]').forEach(btn=>btn.addEventListener('click',()=>{const el=$(`detail-${btn.dataset.detailIndex}`);if(el)el.classList.toggle('open');else{state.filter='all';renderBoard();setTimeout(()=>{const d=$(`detail-${btn.dataset.detailIndex}`);d?.classList.add('open');d?.scrollIntoView({behavior:'smooth',block:'center'})},0)}}))}
function updateCounts(){const rows=rowsWithTypes(),active=rows.filter(r=>r.type!=='past'),prime=active.filter(r=>r.type==='prime').length,value=active.filter(r=>['value','strong-value'].includes(r.type)).length,watch=active.filter(r=>r.type==='watch').length,noBet=active.filter(r=>r.type==='no-bet').length,past=rows.filter(r=>r.type==='past').length;$('signalCount').textContent=prime+value+watch;$('primeFilterCount').textContent=prime;$('valueFilterCount').textContent=value;$('watchFilterCount').textContent=watch;$('noBetFilterCount').textContent=noBet;$('allFilterCount').textContent=active.length;$('pastFilterCount').textContent=past;$('heroAnalysed').textContent=active.length;$('heroPrime').textContent=prime;$('heroWatch').textContent=watch;$('todayCounts').textContent=`${prime} best · ${value} value · ${watch} watch`;const best=actionableRows()[0];$('strongestSignal').textContent=best?`${best.match.home} vs ${best.match.away} · ${betLabel(best.analysis)} · ${best.analysis.confidence||0}% confidence`:'No strong opportunity right now.'}
function renderBoard(){updateCounts();renderTopOpportunities();const grid=$('matchGrid'),rows=filteredRows();if(!state.matches.length){grid.innerHTML='<div class="empty-state"><strong>Ready to check today</strong><span>ARGUS will review the available matches and surface only the decisions worth your attention.</span></div>';return}if(!rows.length){grid.innerHTML='<div class="empty-state"><strong>Nothing strong enough here</strong><span>ARGUS prefers waiting to forcing a weak bet.</span></div>';return}grid.innerHTML=rows.map(r=>cardTemplate(r.match,r.analysis,r.index)).join('');bindButtons()}
function render(){updateQuota(state.meta);updateHistoryCoverage(state.meta);updateGovernanceStatus();const stamp=state.meta?.fetchedAt?new Date(state.meta.fetchedAt):null,t=stamp?stamp.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';$('heroUpdate').textContent=t;$('lastUpdate').textContent=stamp?`Updated ${t}${state.meta?.clientCache?' · cached':''}`:'Ready to check';renderBoard()}
function analyzeMatches(matches,meta=null){state.matches=matches;state.meta=meta;state.analyses=matches.map(m=>{const base=window.ArgusEngine.analyze(m);return window.ArgusGovernance?window.ArgusGovernance.apply(base,m):base});render()}
async function scanToday(){$('scanBtn').disabled=true;const cache=window.ArgusProviders.cacheStatus?.();$('scanBtn').textContent=cache?.safeMode&&cache?.fresh?'Using fresh data':'Checking matches…';try{const matches=await window.ArgusProviders.live({force:false});state.mode=matches.meta?.clientCache?'CACHE':'TODAY';analyzeMatches(matches,matches.meta||null);$('liveStatus').textContent=matches.meta?.clientCache?'CACHED':'CONNECTED'}catch(e){$('liveStatus').textContent='ERROR';alert(e.message)}finally{$('scanBtn').disabled=false;const c=window.ArgusProviders.cacheStatus?.();$('scanBtn').textContent=c?.safeMode&&c?.fresh?'Data ready':'Check today'}}
async function detectLiveBackend(){const s=await window.ArgusProviders.health();$('liveStatus').textContent=s.cached?'CACHE READY':'READY';if(s.meta){updateQuota(s.meta);updateHistoryCoverage(s.meta)}if(Array.isArray(s.matches)&&s.matches.length){const m=s.matches.slice();m.meta=s.meta||null;state.mode='CACHE';analyzeMatches(m,s.meta||null)}else render()}
function setFilter(f){state.filter=f;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderBoard()}
$('scanBtn').addEventListener('click',scanToday);document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderBoard()});detectLiveBackend();