(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const finite=v=>Number.isFinite(Number(v))?Number(v):null;
  const pct=v=>{const n=finite(v);return n==null?'—':`${(n<=1?n*100:n).toFixed(1)}%`};
  const score=v=>{const n=finite(v);return n==null?'—':`${Math.round(n)}/100`};
  const odd=v=>{const n=finite(v);return n&&n>1?n.toFixed(2):'—'};
  const signed=(v,suffix='')=>{const n=finite(v);return n==null?'—':`${n>=0?'+':''}${n.toFixed(1)}${suffix}`};
  const rank={PRIME:5,VALUE:4,WATCH:3,MODEL:2,'NO BET':1};
  const flagMap={italy:'🇮🇹',england:'🏴',spain:'🇪🇸',france:'🇫🇷',germany:'🇩🇪',belgium:'🇧🇪',netherlands:'🇳🇱',portugal:'🇵🇹',scotland:'🏴',turkey:'🇹🇷',greece:'🇬🇷',austria:'🇦🇹',switzerland:'🇨🇭',denmark:'🇩🇰',norway:'🇳🇴',sweden:'🇸🇪',poland:'🇵🇱',croatia:'🇭🇷',serbia:'🇷🇸',romania:'🇷🇴',ukraine:'🇺🇦',czechia:'🇨🇿','czech republic':'🇨🇿',brazil:'🇧🇷',argentina:'🇦🇷',mexico:'🇲🇽','united states':'🇺🇸',usa:'🇺🇸',japan:'🇯🇵','south korea':'🇰🇷',australia:'🇦🇺','saudi arabia':'🇸🇦','united arab emirates':'🇦🇪',morocco:'🇲🇦',egypt:'🇪🇬',tunisia:'🇹🇳',algeria:'🇩🇿'};
  const flag=country=>flagMap[String(country||'').trim().toLowerCase()]||'🌐';
  const verdictClass=v=>String(v||'NO BET').toLowerCase().replace(/\s+/g,'-');
  const categoryForSelection=v=>{const s=String(v||'').toUpperCase();if(['HOME','DRAW','AWAY'].includes(s))return'1x2';if(s.includes('BTTS'))return'btts';if(s.includes('DOUBLE_CHANCE')||s.includes('DOUBLE CHANCE'))return'dc';if(s.includes('OVER_')||s.includes('UNDER_')||/^OVER\s|^UNDER\s/.test(s))return'goals';return'overview'};
  const labelSelection=a=>typeof betLabel==='function'?betLabel(a):(a?.bestMarket||'No bet');
  const statusType=(m,a)=>typeof signalType==='function'?signalType(m,a):String(a?.classification||'NO BET').toLowerCase();
  const kick=m=>typeof kickoffText==='function'?kickoffText(m):(m?.kickoff?new Date(m.kickoff).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—');
  const officialMetrics=a=>({probability:a?.outcomeProbability??a?.conservativeProbability??a?.shrunkProbability??a?.rawProbability,confidence:a?.decisionConfidence??a?.confidence,edge:a?.edge,ev:a?.conservativeEV,fair:a?.fairOdds,odds:a?.marketOdds});
  const marketSnapshot=m=>{try{return window.ArgusMarketEngine?.analyze?.(m)||null}catch(_){return null}};
  const oneXTwoSnapshot=m=>{try{return window.ArgusEngine?.analyze?.(m)||null}catch(_){return null}};
  function scienceBlock(a){const x=officialMetrics(a),source=esc(a?.decisionSource||'—'),validation=esc(a?.validationStatus||'—'),model=esc(a?.modelVersion||'—');return `<div class="v2-science" hidden><div><span>Outcome probability</span><strong>${pct(x.probability)}</strong></div><div><span>Decision confidence</span><strong>${score(x.confidence)}</strong></div><div><span>Current odds</span><strong>${odd(x.odds)}</strong></div><div><span>Fair odds</span><strong>${odd(x.fair)}</strong></div><div><span>Model edge</span><strong>${signed(x.edge,' pp')}</strong></div><div><span>Expected value</span><strong>${signed(x.ev,'%')}</strong></div><div><span>Validation</span><strong>${validation}</strong></div><div><span>Model</span><strong>${model}</strong></div><div class="wide"><span>Decision source</span><strong>${source}</strong></div>${a?.integrityBlocker?`<div class="wide danger"><span>Integrity blocker</span><strong>${esc(a.integrityBlocker)}</strong></div>`:''}</div>`}
  function officialPanel(m,a){const verdict=String(a?.classification||'NO BET').toUpperCase(),x=officialMetrics(a);return `<div class="v2-panel-main"><div class="v2-decision-copy"><span>ARGUS decision</span><strong>${esc(labelSelection(a))}</strong><small>${esc(a?.engineStatus||'Official decision view')}</small></div><div class="v2-decision-state"><b class="v2-badge ${verdictClass(verdict)}">${esc(verdict)}</b><strong>${score(x.confidence)}</strong><span>confidence</span></div></div><div class="v2-metrics"><div><span>Probability</span><strong>${pct(x.probability)}</strong></div><div><span>Fair odds</span><strong>${odd(x.fair)}</strong></div><div><span>Current odds</span><strong>${odd(x.odds)}</strong></div><div><span>Edge</span><strong>${signed(x.edge,' pp')}</strong></div></div><div class="v2-panel-actions"><button type="button" class="v2-science-toggle">Science</button><a href="markets.html">All markets</a></div>${scienceBlock(a)}`}
  function neutralMarketPanel(m,a,cat){const officialCat=categoryForSelection(a?.selectionKey||a?.bestMarket);if(cat===officialCat&&cat!=='overview')return officialPanel(m,a);if(cat==='1x2'){const raw=oneXTwoSnapshot(m),model=raw?.model,market=raw?.market||{};if(!model)return `<div class="v2-context-empty"><strong>No 1X2 model view available.</strong><span>The official ARGUS decision above remains the source of truth.</span></div>`;const rows=[['Home',model.home,market.home,m?.markets?.home],['Draw',model.draw,market.draw,m?.markets?.draw],['Away',model.away,market.away,m?.markets?.away]];return `<div class="v2-context-head"><div><span>1X2 model view</span><strong>Context only</strong></div><b>NOT ACTIONABLE</b></div><div class="v2-market-grid">${rows.map(([name,p,mp,o])=>`<div><span>${name}</span><strong>${pct(p)}</strong><small>${odd(o)} odds${finite(mp)!=null?` · market ${pct(mp)}`:''}</small></div>`).join('')}</div><p class="v2-context-note">This tab does not promote a bet. PRIME/VALUE status comes only from the official decision pipeline.</p>`}const map={goals:'goals',btts:'btts',dc:'other'},marketCat=map[cat],snap=marketSnapshot(m),rows=(snap?.markets||[]).filter(x=>x.category===marketCat).sort((x,y)=>(rank[y.classification]||0)-(rank[x.classification]||0)||(finite(y.trainingEdge??y.edge)??-999)-(finite(x.trainingEdge??x.edge)??-999));if(!rows.length)return `<div class="v2-context-empty"><strong>No ${esc(cat.toUpperCase())} data available.</strong><span>Nothing is promoted from incomplete evidence.</span></div>`;return `<div class="v2-context-head"><div><span>${esc(cat.toUpperCase())} model view</span><strong>Context only</strong></div><b>NOT ACTIONABLE</b></div><div class="v2-market-grid">${rows.slice(0,4).map(x=>`<div><span>${esc(x.label)}</span><strong>${x.probabilityPct==null?'—':`${x.probabilityPct}%`}</strong><small>fair ${odd(x.fairOdds)} · odds ${odd(x.marketOdds)}</small></div>`).join('')}</div><p class="v2-context-note">Model context is shown for exploration. The official Overview remains authoritative for betting eligibility.</p>`}
  function card(row){const m=row.match,a=row.analysis,type=statusType(m,a),verdict=String(a?.classification||'NO BET').toUpperCase(),country=m?.country||'International',competition=m?.competition||'Match';return `<article class="v2-card ${esc(type)}" data-v2-index="${row.index}"><div class="v2-card-head"><div class="v2-location"><span>${flag(country)}</span><strong>${esc(country)}</strong><i>·</i><b>${esc(competition)}</b></div><time>${esc(kick(m))}</time></div><div class="v2-match-line"><h4>${esc(m?.home||'Home')} <em>vs</em> ${esc(m?.away||'Away')}</h4><div><b class="v2-badge ${verdictClass(verdict)}">${esc(verdict)}</b><strong>${score(a?.decisionConfidence??a?.confidence)}</strong></div></div><div class="v2-tabs" role="tablist" aria-label="Market views"><button class="active" data-v2-tab="overview">Overview</button><button data-v2-tab="1x2">1X2</button><button data-v2-tab="goals">Goals</button><button data-v2-tab="btts">BTTS</button><button data-v2-tab="dc">DC</button></div><div class="v2-market-panel">${officialPanel(m,a)}</div></article>`}
  function groupedMarkup(rows){const groups=new Map();for(const row of rows){const m=row.match,key=`${m?.country||'International'}|||${m?.competition||'Match'}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}return [...groups.entries()].map(([key,items])=>{const [country,competition]=key.split('|||');return `<section class="v2-league-group"><div class="v2-league-head"><div><span>${flag(country)}</span><strong>${esc(country)}</strong><i>·</i><b>${esc(competition)}</b></div><small>${items.length} ${items.length===1?'match':'matches'}</small></div><div class="v2-cards">${items.map(card).join('')}</div></section>`}).join('')}
  function ensureShell(){document.body.classList.add('argus-ui-v2');const main=document.querySelector('main#today'),matches=document.getElementById('matches');if(!main||!matches)return;if(!document.getElementById('v2Command')){const el=document.createElement('section');el.id='v2Command';el.className='v2-command';el.innerHTML=`<div class="v2-command-top"><div><p class="eyebrow">ARGUS OMNI · TODAY</p><h2>See the match. See the decision.</h2><p>Country, league and ARGUS verdict first. Science stays one tap away.</p></div><button id="v2Scan" class="v2-scan" type="button">Check today</button></div><div class="v2-status-strip"><div><span>PRIME</span><strong id="v2Prime">0</strong></div><div><span>VALUE</span><strong id="v2Value">0</strong></div><div><span>WATCH</span><strong id="v2Watch">0</strong></div><div><span>NO BET</span><strong id="v2NoBet">0</strong></div></div><div class="v2-best-line"><span>Best signal</span><strong id="v2Best">Ready when you are</strong><small id="v2Updated">—</small></div><div class="v2-filterbar" role="tablist"><button data-v2-filter="signals" class="active">Best</button><button data-v2-filter="prime">Prime</button><button data-v2-filter="value">Value</button><button data-v2-filter="watch">Watch</button><button data-v2-filter="all">All</button></div>`;main.insertBefore(el,matches);document.getElementById('v2Scan')?.addEventListener('click',()=>{if(typeof scanToday==='function')scanToday()});el.querySelectorAll('[data-v2-filter]').forEach(btn=>btn.addEventListener('click',()=>{state.filter=btn.dataset.v2Filter;el.querySelectorAll('[data-v2-filter]').forEach(x=>x.classList.toggle('active',x===btn));renderBoard()}))}if(!document.getElementById('v2BottomNav')){const nav=document.createElement('nav');nav.id='v2BottomNav';nav.className='v2-bottom-nav';nav.innerHTML='<a class="active" href="/">Matches</a><a href="markets.html">Markets</a><a href="virtual-bankroll.html">Bets</a><a href="prediction-results.html">Results</a>';document.body.appendChild(nav)}}
  function updateCommand(){if(typeof rowsWithTypes!=='function')return;const rows=rowsWithTypes().filter(r=>r.type!=='past'),prime=rows.filter(r=>r.type==='prime').length,value=rows.filter(r=>['value','strong-value'].includes(r.type)).length,watch=rows.filter(r=>r.type==='watch').length,nobet=rows.filter(r=>r.type==='no-bet').length;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('v2Prime',prime);set('v2Value',value);set('v2Watch',watch);set('v2NoBet',nobet);const best=typeof actionableRows==='function'?actionableRows()[0]:null;if(best){const m=best.match,a=best.analysis;set('v2Best',`${flag(m.country)} ${m.country||'International'} · ${m.competition||'Match'} · ${m.home} vs ${m.away} · ${labelSelection(a)}`)}else set('v2Best','No eligible opportunity right now');const t=state?.meta?.fetchedAt?new Date(state.meta.fetchedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';set('v2Updated',`Updated ${t}`)}
  function bindCardInteractions(){document.querySelectorAll('.v2-card').forEach(cardEl=>{const idx=Number(cardEl.dataset.v2Index),m=state.matches[idx],a=state.analyses[idx];cardEl.querySelectorAll('[data-v2-tab]').forEach(btn=>btn.addEventListener('click',()=>{cardEl.querySelectorAll('[data-v2-tab]').forEach(x=>x.classList.toggle('active',x===btn));const panel=cardEl.querySelector('.v2-market-panel');if(panel)panel.innerHTML=btn.dataset.v2Tab==='overview'?officialPanel(m,a):neutralMarketPanel(m,a,btn.dataset.v2Tab);bindScience(cardEl)}));bindScience(cardEl)})}
  function bindScience(scope){scope.querySelectorAll('.v2-science-toggle').forEach(btn=>btn.onclick=()=>{const science=scope.querySelector('.v2-science');if(!science)return;science.hidden=!science.hidden;btn.classList.toggle('active',!science.hidden);btn.textContent=science.hidden?'Science':'Hide science'})}
  function v2RenderBoard(){ensureShell();if(typeof updateCounts==='function')updateCounts();updateCommand();const grid=document.getElementById('matchGrid');if(!grid)return;if(!state.matches.length){grid.innerHTML='<div class="v2-empty"><strong>Ready to check today.</strong><span>ARGUS will surface only what survives the decision gates.</span></div>';return}const rows=typeof filteredRows==='function'?filteredRows():[];if(!rows.length){grid.innerHTML='<div class="v2-empty"><strong>Nothing strong enough here.</strong><span>Waiting is a valid ARGUS decision.</span></div>';return}grid.innerHTML=groupedMarkup(rows);bindCardInteractions()}
  ensureShell();if(typeof renderTopOpportunities==='function')renderTopOpportunities=()=>{};if(typeof renderBoard==='function')renderBoard=v2RenderBoard;try{renderBoard()}catch(_){}
})();
