(()=>{
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const fmtDate=()=>new Intl.DateTimeFormat(undefined,{weekday:'short',day:'2-digit',month:'short'}).format(new Date());
  function installHeader(){const shell=q('.shell');if(!shell||q('.v21-appbar',shell))return;const header=document.createElement('header');header.className='v21-appbar';header.innerHTML=`<div class="v21-brand"><div class="v21-mark">A</div><div class="v21-brandcopy"><strong>ARGUS OMNI v2</strong><small>FOOTBALL INTELLIGENCE</small></div></div><div class="v21-app-actions"><span class="v21-date">${fmtDate()}</span><button class="v21-refresh" type="button" aria-label="Refresh ARGUS">↻</button></div>`;shell.insertBefore(header,shell.firstChild);q('.v21-refresh',header)?.addEventListener('click',()=>{if(typeof scanToday==='function')scanToday()})}
  function rebuildCommand(){const root=q('#v2Command');if(!root||root.dataset.v21==='1')return;root.dataset.v21='1';root.innerHTML=`<div class="v21-daynav" aria-label="Match day"><button class="active" type="button">TODAY</button><button type="button" data-v21-coming="tomorrow">TOMORROW</button><button type="button" data-v21-coming="all">ALL</button><time>${fmtDate()}</time></div><div class="v2-status-strip"><div><span>PRIME</span><strong id="v2Prime">0</strong></div><div><span>VALUE</span><strong id="v2Value">0</strong></div><div><span>WATCH</span><strong id="v2Watch">0</strong></div><div><span>NO BET</span><strong id="v2NoBet">0</strong></div></div><div class="v2-best-line"><span>Best signal</span><strong id="v2Best">Ready when you are</strong><small id="v2Updated">—</small></div><div class="v2-filterbar" role="tablist"><button data-v2-filter="signals" class="active">Best</button><button data-v2-filter="prime">Prime</button><button data-v2-filter="value">Value</button><button data-v2-filter="watch">Watch</button><button data-v2-filter="all">All</button></div>`;
    qa('[data-v2-filter]',root).forEach(btn=>btn.addEventListener('click',()=>{if(typeof state==='undefined')return;state.filter=btn.dataset.v2Filter;qa('[data-v2-filter]',root).forEach(x=>x.classList.toggle('active',x===btn));if(typeof renderBoard==='function')renderBoard()}));
    qa('[data-v21-coming]',root).forEach(btn=>btn.addEventListener('click',()=>{qa('.v21-daynav button',root).forEach(x=>x.classList.toggle('active',x===btn));if(btn.dataset.v21Coming==='all'&&typeof state!=='undefined'){state.filter='all';if(typeof renderBoard==='function')renderBoard()}else if(btn.dataset.v21Coming==='tomorrow'){const best=q('#v2Best');if(best)best.textContent='Tomorrow view is not loaded in the current provider window.'}}));
  }
  function fixEnglandFlag(){qa('.v2-location span,.v2-league-head span').forEach(el=>{if(el.textContent==='🏴')el.textContent='🇬🇧'})}
  function sync(){installHeader();rebuildCommand();fixEnglandFlag();if(typeof updateCommand==='function')try{updateCommand()}catch(_){}}
  sync();
  const obs=new MutationObserver(()=>sync());obs.observe(document.documentElement,{childList:true,subtree:true});
})();
