const $=id=>document.getElementById(id);const FINISHED=new Set(['FT','AET','PEN','CANC','ABD','AWD','WO']);
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}function safe(v,f=0){return Number.isFinite(Number(v))?Number(v):f}function poisson(k,lambda){let fact=1;for(let i=2;i<=k;i++)fact*=i;return Math.exp(-lambda)*Math.pow(lambda,k)/fact}
function kickoffText(m){if(m.isLive)return`LIVE ${m.minute||0}'`;if(m.kickoff)return new Date(m.kickoff).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return m.status||'PRE-MATCH'}
function modelLambdas(match){const h=match.history90d?.home,a=match.history90d?.away;if(!h||!a||safe(h.matches)<3||safe(a.matches)<3)return null;const venueHomePPG=h.homePPG==null?safe(h.pointsPerGame,1.4):safe(h.homePPG,1.4),venueAwayPPG=a.awayPPG==null?safe(a.pointsPerGame,1.2):safe(a.awayPPG,1.2);const formDelta=(safe(h.last5PPG)-safe(a.last5PPG))/3,venueDelta=(venueHomePPG-venueAwayPPG)/3;let lh=safe(h.goalsForPerGame,1.2)*.54+safe(a.goalsAgainstPerGame,1.2)*.46,la=safe(a.goalsForPerGame,1.1)*.54+safe(h.goalsAgainstPerGame,1.1)*.46;lh*=1.06+formDelta*.11+venueDelta*.08;la*=.98-formDelta*.07-venueDelta*.05;lh=clamp(lh,.2,3.8);la=clamp(la,.2,3.8);return{home:lh,away:la}}
function exactScores(match){const base=modelLambdas(match);if(!base)return null;let curH=safe(match.score?.home),curA=safe(match.score?.away),lh=base.home,la=base.away,maxExtra=6;if(match.isLive){const minute=clamp(safe(match.minute),0,95),remain=clamp((95-minute)/95,.03,1);lh=clamp(lh*remain,.02,3.2);la=clamp(la*remain,.02,3.2);maxExtra=5}else{curH=0;curA=0}const rows=[];for(let h=0;h<=maxExtra;h++)for(let a=0;a<=maxExtra;a++)rows.push({home:curH+h,away:curA+a,p:poisson(h,lh)*poisson(a,la)});rows.sort((x,y)=>y.p-x.p);return{top:rows[0],alts:rows.slice(1,3),lambdaHome:lh,lambdaAway:la}}
function pct(v){return`${(v*100).toFixed(1)}%`}function rowHtml(m,p){if(!p)return`<article class="danger-row unavailable"><div class="match"><span>${m.competition||'MATCH'} · ${kickoffText(m)}</span><strong>${m.home} vs ${m.away}</strong></div><div><span>EXACT SCORE</span><strong>DATA LOADING</strong></div><div><span>MODEL PROBABILITY</span><strong>—</strong></div><div><span>WHY</span><small>ARGUS is retrieving the missing 90-day team history from API-Football Pro. If a team has fewer than 3 completed matches in the window, no exact score will be forced.</small></div></article>`;return`<article class="danger-row ${m.isLive?'live':''}"><div class="match"><span>${m.competition||'MATCH'} · ${kickoffText(m)}</span><strong>${m.home} vs ${m.away}</strong><small>${m.isLive?`Current score ${safe(m.score?.home)}-${safe(m.score?.away)}`:'PRE-MATCH'}</small></div><div><span>MOST LIKELY SCORE</span><strong class="exact-score">${p.top.home} — ${p.top.away}</strong></div><div><span>MODEL PROBABILITY</span><strong class="score-prob">${pct(p.top.p)}</strong><small>exact outcome only</small></div><div><span>NEXT SCENARIOS</span><div class="alternatives">${p.alts.map(x=>`<b>${x.home}-${x.away} · ${pct(x.p)}</b>`).join('')}</div><small>xG model: ${p.lambdaHome.toFixed(2)} / ${p.lambdaAway.toFixed(2)}</small></div></article>`}
function render(matches,meta){const active=(matches||[]).filter(m=>!m.isFinished&&!FINISHED.has(m.status));const rows=active.map(m=>({m,p:exactScores(m)})).sort((a,b)=>(b.p?.top?.p||-1)-(a.p?.top?.p||-1));const available=rows.filter(r=>r.p),live=active.filter(m=>m.isLive).length,best=available[0];$('dangerSummary').innerHTML=`<article class="panel"><span>MATCHES</span><strong>${active.length}</strong></article><article class="panel"><span>SCORES MODELED</span><strong>${available.length}</strong></article><article class="panel"><span>LIVE</span><strong>${live}</strong></article><article class="panel"><span>HIGHEST EXACT P</span><strong>${best?pct(best.p.top.p):'—'}</strong></article>`;$('dangerList').innerHTML=rows.length?rows.map(r=>rowHtml(r.m,r.p)).join(''):'<div class="empty-state">AUCUN MATCH ACTIF.</div>';const stamp=meta?.fetchedAt?new Date(meta.fetchedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';const missing=meta?.teamsStillMissing??0;const quota=meta?.quota?.dailyRemaining!=null?` · API ${meta.quota.dailyRemaining}/${meta.quota.dailyLimit||'?'}`:'';$('dangerMeta').textContent=`${available.length}/${active.length} scores calculés · ${missing} équipes à compléter · data ${stamp}${quota}`}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function fetchDangerBatch(){const r=await fetch('/api/danger-data',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function load(){const btn=$('refreshDanger');btn.disabled=true;btn.textContent='LOADING PRO DATA…';let last=null;try{for(let i=0;i<10;i++){last=await fetchDangerBatch();render(last.matches,last.meta);const missing=last.meta?.teamsStillMissing??0;const more=last.meta?.hasMore;const minuteLeft=last.meta?.quota?.minuteRemaining;if(!more||missing===0||(minuteLeft!=null&&minuteLeft<10))break;btn.textContent=`LOADING PRO DATA ${i+1}/10…`;await sleep(180)}if(last?.meta?.hasMore){btn.textContent='CONTINUE DATA LOAD';btn.disabled=false;return}}catch(e){$('dangerList').innerHTML=`<div class="empty-state"><strong>DATA ERROR</strong><span>${e.message}</span></div>`}finally{if(btn.disabled){btn.disabled=false;btn.textContent='REFRESH SCORES'}}}
$('refreshDanger').addEventListener('click',load);load();