/* ARGUS OMNI — human-facing copy and interaction polish. Engine logic stays untouched. */
(() => {
  const replacements = new Map([
    ['BET THIS','Suggested bet'],['ARGUS SUGGESTS','ARGUS suggests'],['CONFIDENCE · HOW SURE?','Confidence'],['VALUE ADVANTAGE','Price value'],['WHY THIS PICK?','Why this pick?'],['WHAT TO BET','Suggested bet'],['ARGUS CONFIDENCE','Confidence'],['BET SIGNAL','Worth considering'],['WAIT','Wait'],['SKIP','Skip'],['NO DATA LOADED','Ready when you are'],['NO BET RIGHT NOW','No strong opportunity right now'],['CHECKING…','Reviewing matches…'],['CONNECTED','Fresh data'],['CACHED','Recent data'],['CACHE READY','Recent data ready'],['READY','Ready'],['ERROR','Data unavailable']
  ]);
  const verdictCopy=text=>{if(!text)return text;if(text.includes('PRIME · STRONGEST'))return text.replace('🟢 PRIME · STRONGEST','PRIME · Best opportunity');if(text.includes('VALUE · INTERESTING'))return text.replace('🔵 VALUE · INTERESTING','VALUE · Interesting price');if(text.includes('WATCH · WAIT'))return text.replace('🟠 WATCH · WAIT','WATCH · Worth monitoring');if(text.includes('NO BET · SKIP'))return text.replace('⚫ NO BET · SKIP','NO BET · Better to skip');return text};
  function addNavLink(nav,href,label,beforeSelector){if(nav.querySelector(`a[href="${href}"]`))return;const a=document.createElement('a');a.className='nav-link';a.href=href;a.textContent=label;const before=beforeSelector?nav.querySelector(beforeSelector):null;nav.insertBefore(a,before||null)}
  function hideTechnicalNav(nav){['training-dashboard.html','compte-rendu-des-predictions.html','evolution-dashboard.html','argus-lab.html'].forEach(h=>nav.querySelectorAll(`a[href="${h}"]`).forEach(a=>a.remove()))}
  function ensurePrimaryNav(){const nav=document.querySelector('.top-status');if(!nav)return;hideTechnicalNav(nav);addNavLink(nav,'live.html','● LIVE','a[href="daily-slip.html"]');addNavLink(nav,'daily-slip.html','Daily Slip','a[href="exact-scores.html"]');addNavLink(nav,'markets.html','Markets');addNavLink(nav,'trends.html','Trends');addNavLink(nav,'shield.html','Shield');addNavLink(nav,'prediction-results.html','Results');addNavLink(nav,'historical-validation.html','Historical Lab');addNavLink(nav,'system-health.html','System Health')}
  function ensureResponsiveNav(){if(document.getElementById('argus-runtime-nav-style'))return;const style=document.createElement('style');style.id='argus-runtime-nav-style';style.textContent=`@keyframes argusLiveNavBlink{0%,100%{background:rgba(235,195,76,.08)}50%{background:rgba(235,195,76,.32)}}.top-status a[href="live.html"]{border:1px solid rgba(235,195,76,.35)!important;color:#ffe18a!important;animation:argusLiveNavBlink 1.4s infinite}.top-status a[href="system-health.html"]{border:1px solid rgba(127,159,189,.35)!important;color:#bdd0df!important}@media (max-width:900px){.topbar{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:10px!important;padding:12px 0 9px!important;min-height:auto!important}.topbar>.brand{align-self:flex-start!important}.top-status{display:flex!important;width:100%!important;max-width:100%!important;gap:7px!important;overflow-x:auto!important;overflow-y:hidden!important;flex-wrap:nowrap!important;padding:2px 0 7px!important;-webkit-overflow-scrolling:touch!important;scrollbar-width:none!important}.top-status::-webkit-scrollbar{display:none!important}.top-status .nav-link{display:inline-flex!important;align-items:center!important;justify-content:center!important;flex:0 0 auto!important;white-space:nowrap!important;padding:9px 11px!important;font-size:8px!important}.top-status .system-status{display:flex!important;flex:0 0 auto!important;min-width:24px!important}.top-status .safe-chip{flex:0 0 auto!important}}@media (max-width:520px){.top-status .nav-link{padding:8px 10px!important;font-size:7.5px!important}.top-status .system-status{display:none!important}}`;document.head.appendChild(style)}
  function ensureLivePrimeFollow(){if(!document.getElementById('matchGrid')||document.querySelector('script[data-argus-live-prime]'))return;const s=document.createElement('script');s.src='src/live-prime-follow.js';s.async=true;s.dataset.argusLivePrime='1';document.head.appendChild(s)}
  function ensureLiveCommand(){if(!document.getElementById('matchGrid')||document.querySelector('script[data-argus-live-command]'))return;const loadCommand=()=>{if(document.querySelector('script[data-argus-live-command]'))return;const s=document.createElement('script');s.src='src/live-command-center.js';s.async=true;s.dataset.argusLiveCommand='1';document.head.appendChild(s)};if(document.querySelector('script[data-argus-live-guard]')){loadCommand();return}const g=document.createElement('script');g.src='src/live-snapshot-guard.js';g.async=true;g.dataset.argusLiveGuard='1';g.onload=loadCommand;g.onerror=loadCommand;document.head.appendChild(g)}
  function polishText(root=document){root.querySelectorAll('span,strong,small,b,button,p').forEach(el=>{if(el.children.length)return;const raw=(el.textContent||'').trim();if(!raw)return;if(replacements.has(raw))el.textContent=replacements.get(raw);else{const refined=verdictCopy(raw);if(refined!==raw)el.textContent=refined}})}
  function polishEmptyStates(){const grid=document.getElementById('matchGrid');if(!grid)return;const empty=grid.querySelector('.empty-state');if(!empty)return;const strong=empty.querySelector('strong'),span=empty.querySelector('span');if(strong?.textContent.trim()==='Ready when you are'&&span)span.textContent="ARGUS can review today's available matches and surface only the decisions worth your attention."}
  function markFreshness(){const update=document.getElementById('lastUpdate');if(!update)return;update.classList.toggle('human-fresh',/^Updated /.test(update.textContent||''))}
  function run(){ensurePrimaryNav();ensureResponsiveNav();ensureLivePrimeFollow();ensureLiveCommand();polishText();polishEmptyStates();markFreshness()}
  let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})});observer.observe(document.body,{childList:true,subtree:true,characterData:true});run();
})();