(function () {
  const clamp = (value, min = 0, max = 100) => Math.min(max, Math.max(min, value));
  const safe = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
  function impliedProbability(odds){const value=safe(odds);return value>1?1/value:0}
  function hasComplete1x2(markets={}){return safe(markets.home)>1&&safe(markets.draw)>1&&safe(markets.away)>1}
  function normalizeMarket(markets={}){const raw={home:impliedProbability(markets.home),draw:impliedProbability(markets.draw),away:impliedProbability(markets.away)},overround=raw.home+raw.draw+raw.away;if(!overround)return{home:0,draw:0,away:0,overround:0};return{home:raw.home/overround,draw:raw.draw/overround,away:raw.away/overround,overround}}
  function normalizeModel(model){const home=Math.max(0,safe(model?.home)),draw=Math.max(0,safe(model?.draw)),away=Math.max(0,safe(model?.away)),sum=home+draw+away;return sum>0?{home:home/sum,draw:draw/sum,away:away/sum}:null}
  function adaptiveTrust(match,phase){return window.ArgusAdaptiveWeights?.boundedMultiplier?.(match,phase)||{multiplier:1,status:'BASELINE',sources:[]}}
  function applyAdaptiveTrust(model,market,marketAvailable,trust){if(!model||!marketAvailable||!market)return model;const m=Math.max(.78,Math.min(1.04,Number(trust?.multiplier)||1));return normalizeModel({home:market.home+(model.home-market.home)*m,draw:market.draw+(model.draw-market.draw)*m,away:market.away+(model.away-market.away)*m})}
  function pressureIndex(match){const s=match.stats||{},shotDelta=safe(s.shotsHome)-safe(s.shotsAway),sotDelta=safe(s.shotsOnTargetHome)-safe(s.shotsOnTargetAway),cornerDelta=safe(s.cornersHome)-safe(s.cornersAway),dangerDelta=safe(s.dangerousAttacksHome)-safe(s.dangerousAttacksAway),possessionDelta=safe(s.possessionHome,50)-50;return clamp(50+shotDelta*2.4+sotDelta*5.2+cornerDelta*1.8+dangerDelta*.55+possessionDelta*.6)}
  function liveModelProbabilities(match,pressure){const minute=clamp(safe(match.minute),0,95),goalDelta=safe(match.score?.home)-safe(match.score?.away),timeWeight=.35+(minute/95)*.65,pressureTilt=(pressure-50)/100;let home=.39+pressureTilt*.34+goalDelta*.18*timeWeight,away=.31-pressureTilt*.30-goalDelta*.18*timeWeight,draw=1-home-away;home=clamp(home*100,4,90)/100;away=clamp(away*100,4,90)/100;draw=clamp(draw*100,6,72)/100;return normalizeModel({home,draw,away})}
  function poisson(k,lambda){let factorial=1;for(let i=2;i<=k;i++)factorial*=i;return Math.exp(-lambda)*Math.pow(lambda,k)/factorial}
  function historyProbabilities(match){const home=match.history90d?.home,away=match.history90d?.away;if(!home||!away||safe(home.matches)<3||safe(away.matches)<3)return null;const venueHomePPG=home.homePPG==null?safe(home.pointsPerGame,1.4):safe(home.homePPG,1.4),venueAwayPPG=away.awayPPG==null?safe(away.pointsPerGame,1.2):safe(away.awayPPG,1.2),formDelta=(safe(home.last5PPG)-safe(away.last5PPG))/3,venueDelta=(venueHomePPG-venueAwayPPG)/3;let lambdaHome=safe(home.goalsForPerGame,1.2)*.54+safe(away.goalsAgainstPerGame,1.2)*.46,lambdaAway=safe(away.goalsForPerGame,1.1)*.54+safe(home.goalsAgainstPerGame,1.1)*.46;lambdaHome*=1.06+formDelta*.11+venueDelta*.08;lambdaAway*=.98-formDelta*.07-venueDelta*.05;lambdaHome=clamp(lambdaHome,.2,3.8);lambdaAway=clamp(lambdaAway,.2,3.8);let pHome=0,pDraw=0,pAway=0;for(let h=0;h<=7;h++)for(let a=0;a<=7;a++){const p=poisson(h,lambdaHome)*poisson(a,lambdaAway);if(h>a)pHome+=p;else if(h===a)pDraw+=p;else pAway+=p}const poissonModel=normalizeModel({home:pHome,draw:pDraw,away:pAway}),ppgHome=clamp(.34+(safe(home.pointsPerGame)-safe(away.pointsPerGame))*.10+venueDelta*.08,.12,.72),ppgAway=clamp(.28+(safe(away.pointsPerGame)-safe(home.pointsPerGame))*.10-venueDelta*.05,.10,.68),ppgDraw=clamp(1-ppgHome-ppgAway,.14,.42),ppgModel=normalizeModel({home:ppgHome,draw:ppgDraw,away:ppgAway});return normalizeModel({home:poissonModel.home*.82+ppgModel.home*.18,draw:poissonModel.draw*.82+ppgModel.draw*.18,away:poissonModel.away*.82+ppgModel.away*.18})}
  function providerProbabilities(match){return normalizeModel(match.preMatchModel)}
  function historicalCoverage(match){const h=match.history90d?.home,a=match.history90d?.away;if(!h||!a)return 0;return Math.min(1,Math.min(safe(h.matches),safe(a.matches))/10)}
  function blendPrematchModels(match){const provider=providerProbabilities(match),history=historyProbabilities(match);if(provider&&history)return{model:normalizeModel({home:provider.home*.58+history.home*.42,draw:provider.draw*.58+history.draw*.42,away:provider.away*.58+history.away*.42}),provider,history,disagreement:(Math.abs(provider.home-history.home)+Math.abs(provider.draw-history.draw)+Math.abs(provider.away-history.away))/3};const model=provider||history;return{model,provider,history,disagreement:0}}
  function liveDataQuality(match){const s=match.stats||{},required=[match.minute,match.score?.home,match.score?.away,s.shotsHome,s.shotsAway,s.shotsOnTargetHome,s.shotsOnTargetAway,s.possessionHome,match.markets?.home,match.markets?.draw,match.markets?.away],present=required.filter(v=>v!==undefined&&v!==null&&v!=='').length;return clamp(Math.round((present/required.length)*100))}
  function liveUncertainty(match,quality){const minute=safe(match.minute);let value=42;if(minute<20)value+=18;if(minute>75)value-=9;value+=(100-quality)*.36;const totalShots=safe(match.stats?.shotsHome)+safe(match.stats?.shotsAway);if(totalShots<7)value+=8;return clamp(Math.round(value),8,88)}
  function chooseBest(model,market,markets,marketAvailable){return[{key:'HOME',probability:model.home,marketProbability:market.home,odds:safe(markets?.home)},{key:'DRAW',probability:model.draw,marketProbability:market.draw,odds:safe(markets?.draw)},{key:'AWAY',probability:model.away,marketProbability:market.away,odds:safe(markets?.away)}].map(item=>({...item,edge:marketAvailable?item.probability-item.marketProbability:0})).sort((a,b)=>b.edge-a.edge)[0]}
  function analyzeLive(match){const marketAvailable=hasComplete1x2(match.markets),market=normalizeMarket(match.markets),pressure=Math.round(pressureIndex(match)),pureLive=liveModelProbabilities(match,pressure),prior=historyProbabilities(match),minute=clamp(safe(match.minute),0,95),priorWeight=prior?clamp(.34*(1-minute/110),.10,.30):0,baseModel=prior?normalizeModel({home:pureLive.home*(1-priorWeight)+prior.home*priorWeight,draw:pureLive.draw*(1-priorWeight)+prior.draw*priorWeight,away:pureLive.away*(1-priorWeight)+prior.away*priorWeight}):pureLive,trust=adaptiveTrust(match,'LIVE'),model=applyAdaptiveTrust(baseModel,market,marketAvailable,trust),quality=liveDataQuality(match),uncertaintyScore=liveUncertainty(match,quality),best=chooseBest(model,market,match.markets,marketAvailable),edgePct=marketAvailable?best.edge*100:0,historyBonus=historicalCoverage(match)*5,confidence=clamp(Math.round(quality*.56+(100-uncertaintyScore)*.28+Math.abs(pressure-50)*.24+historyBonus));let classification='NO BET';if(marketAvailable&&quality>=78&&confidence>=69&&edgePct>=7.5&&minute>=18)classification='PRIME';else if(marketAvailable&&quality>=62&&confidence>=54&&edgePct>=3.5)classification='WATCH';return{phase:'LIVE',pressure,quality,uncertainty:uncertaintyScore,confidence,model,baseModel,adaptiveTrust:trust,market,marketAvailable,historyModel:prior,historyCoverage:historicalCoverage(match),bestMarket:marketAvailable?best.key:'NO MARKET',edge:Number(edgePct.toFixed(1)),fairOdds:marketAvailable&&best.probability>0?Number((1/best.probability).toFixed(2)):null,marketOdds:marketAvailable?best.odds:null,classification}}
  function analyzePreMatch(match){const marketAvailable=hasComplete1x2(match.markets),market=normalizeMarket(match.markets),blended=blendPrematchModels(match),baseModel=blended.model,historyCoverage=historicalCoverage(match);if(!baseModel)return{phase:'PREMATCH',pressure:null,quality:0,uncertainty:100,confidence:0,model:{home:0,draw:0,away:0},baseModel:null,adaptiveTrust:{multiplier:1,status:'BASELINE',sources:[]},market,marketAvailable,historyModel:null,providerModel:null,historyCoverage,bestMarket:marketAvailable?'MODEL PENDING':'NO MARKET',edge:0,fairOdds:null,marketOdds:null,classification:'NO BET'};const trust=adaptiveTrust(match,'PREMATCH'),model=applyAdaptiveTrust(baseModel,market,marketAvailable,trust),best=chooseBest(model,market,match.markets,marketAvailable),edgePct=marketAvailable?best.edge*100:0,spread=Math.max(model.home,model.draw,model.away)-Math.min(model.home,model.draw,model.away),providerBonus=blended.provider?20:0,historyBonus=historyCoverage*45,quality=clamp(Math.round((marketAvailable?30:0)+providerBonus+historyBonus+(blended.provider&&blended.history?5:0))),disagreementPenalty=blended.disagreement*100*.75,uncertaintyScore=clamp(Math.round(52-spread*34+disagreementPenalty+(marketAvailable?0:22)+(1-historyCoverage)*12),16,90),confidence=clamp(Math.round(quality*.52+(100-uncertaintyScore)*.34+spread*26));let classification='NO BET';if(marketAvailable&&historyCoverage>=.5&&confidence>=73&&edgePct>=6.5)classification='PRIME';else if(marketAvailable&&historyCoverage>=.3&&confidence>=56&&edgePct>=3.5)classification='WATCH';return{phase:'PREMATCH',pressure:null,quality,uncertainty:uncertaintyScore,confidence,model,baseModel,adaptiveTrust:trust,market,marketAvailable,historyModel:blended.history,providerModel:blended.provider,modelDisagreement:Number((blended.disagreement*100).toFixed(1)),historyCoverage,bestMarket:marketAvailable?best.key:'NO MARKET',edge:Number(edgePct.toFixed(1)),fairOdds:marketAvailable&&best.probability>0?Number((1/best.probability).toFixed(2)):null,marketOdds:marketAvailable?best.odds:null,classification}}
  function analyze(match){if(match.isLive)return analyzeLive(match);if(['FT','AET','PEN','CANC','ABD','AWD','WO'].includes(match.status))return{...analyzePreMatch({...match,preMatchModel:null}),phase:'FINISHED',classification:'NO BET'};return analyzePreMatch(match)}
  window.ArgusEngine={analyze,analyzeLive,analyzePreMatch,normalizeMarket,pressureIndex,hasComplete1x2,historyProbabilities,applyAdaptiveTrust};
})();