(function(){
  const clamp=(value,min=0,max=100)=>Math.min(max,Math.max(min,value));
  const safe=(value,fallback=0)=>{if(value===null||value===undefined||value==='')return fallback;const n=Number(value);return Number.isFinite(n)?n:fallback};
  const fact=k=>{let x=1;for(let i=2;i<=k;i++)x*=i;return x};
  const poisson=(k,lambda)=>Math.exp(-lambda)*Math.pow(lambda,k)/fact(k);
  function impliedProbability(odds){const value=safe(odds);return value>1?1/value:0}
  function hasComplete1x2(markets={}){return safe(markets.home)>1&&safe(markets.draw)>1&&safe(markets.away)>1}
  function normalizeMarket(markets={}){const raw={home:impliedProbability(markets.home),draw:impliedProbability(markets.draw),away:impliedProbability(markets.away)},overround=raw.home+raw.draw+raw.away;if(!overround)return{home:0,draw:0,away:0,overround:0};return{home:raw.home/overround,draw:raw.draw/overround,away:raw.away/overround,overround}}
  function normalizeModel(model){const home=Math.max(0,safe(model?.home)),draw=Math.max(0,safe(model?.draw)),away=Math.max(0,safe(model?.away)),sum=home+draw+away;return sum>0?{home:home/sum,draw:draw/sum,away:away/sum}:null}
  function adaptiveTrust(match,phase){return window.ArgusAdaptiveWeights?.boundedMultiplier?.(match,phase)||{multiplier:1,status:'BASELINE',sources:[]}}
  function applyAdaptiveTrust(model,market,marketAvailable,trust){if(!model||!marketAvailable||!market)return model;const m=Math.max(.78,Math.min(1.04,Number(trust?.multiplier)||1));return normalizeModel({home:market.home+(model.home-market.home)*m,draw:market.draw+(model.draw-market.draw)*m,away:market.away+(model.away-market.away)*m})}
  function pressureIndex(match){const s=match.stats||{},shotDelta=safe(s.shotsHome)-safe(s.shotsAway),sotDelta=safe(s.shotsOnTargetHome)-safe(s.shotsOnTargetAway),cornerDelta=safe(s.cornersHome)-safe(s.cornersAway),possessionDelta=safe(s.possessionHome,50)-50;return clamp(50+shotDelta*2+sotDelta*4.5+cornerDelta*1.5+possessionDelta*.45)}
  function historyLambdas(match){const home=match.history90d?.home,away=match.history90d?.away;if(!home||!away||safe(home.matches)<3||safe(away.matches)<3)return null;const venueHomePPG=home.homePPG==null?safe(home.pointsPerGame,1.4):safe(home.homePPG,1.4),venueAwayPPG=away.awayPPG==null?safe(away.pointsPerGame,1.2):safe(away.awayPPG,1.2),formDelta=(safe(home.last5PPG)-safe(away.last5PPG))/3,venueDelta=(venueHomePPG-venueAwayPPG)/3;let lambdaHome=safe(home.goalsForPerGame,1.2)*.54+safe(away.goalsAgainstPerGame,1.2)*.46,lambdaAway=safe(away.goalsForPerGame,1.1)*.54+safe(home.goalsAgainstPerGame,1.1)*.46;lambdaHome*=1.06+formDelta*.11+venueDelta*.08;lambdaAway*=.98-formDelta*.07-venueDelta*.05;return{home:clamp(lambdaHome,.2,3.8),away:clamp(lambdaAway,.2,3.8)}}
  function historyProbabilities(match){const l=historyLambdas(match);if(!l)return null;let home=0,draw=0,away=0;for(let h=0;h<=7;h++)for(let a=0;a<=7;a++){const p=poisson(h,l.home)*poisson(a,l.away);if(h>a)home+=p;else if(h===a)draw+=p;else away+=p}return normalizeModel({home,draw,away})}
  function providerProbabilities(match){return normalizeModel(match.preMatchModel)}
  function historicalCoverage(match){const h=match.history90d?.home,a=match.history90d?.away;if(!h||!a)return 0;return Math.min(1,Math.min(safe(h.matches),safe(a.matches))/10)}
  function blendPrematchModels(match){const provider=providerProbabilities(match),history=historyProbabilities(match);if(provider&&history)return{model:normalizeModel({home:provider.home*.58+history.home*.42,draw:provider.draw*.58+history.draw*.42,away:provider.away*.58+history.away*.42}),provider,history,disagreement:(Math.abs(provider.home-history.home)+Math.abs(provider.draw-history.draw)+Math.abs(provider.away-history.away))/3};const model=provider||history;return{model,provider,history,disagreement:0}}
  function liveDataQuality(match){const s=match.stats||{},required=[match.minute,match.score?.home,match.score?.away,s.shotsHome,s.shotsAway,s.shotsOnTargetHome,s.shotsOnTargetAway,s.possessionHome,s.possessionAway,match.markets?.home,match.markets?.draw,match.markets?.away],present=required.filter(v=>v!==undefined&&v!==null&&v!=='').length;return clamp(Math.round(present/required.length*100))}
  function liveUncertainty(match,quality){const minute=safe(match.minute);let value=44;if(minute<20)value+=15;if(minute>75)value-=7;value+=(100-quality)*.34;return clamp(Math.round(value),10,90)}
  function liveStateProbabilities(match){const minute=clamp(safe(match.minute),0,120),target=minute>100?121:96,remaining=Math.max(.25,target-minute),base=historyLambdas(match)||{home:1.35,away:1.15},s=match.stats||{},share=(h,a,pad=2)=>(safe(h)+pad/2)/(safe(h)+safe(a)+pad)-.5,tilt=clamp(share(s.shotsOnTargetHome,s.shotsOnTargetAway,3)*.55+share(s.shotsHome,s.shotsAway,5)*.25+share(s.cornersHome,s.cornersAway,3)*.10+((clamp(safe(s.possessionHome,50),0,100)-50)/100)*.10,-.22,.22),frac=Math.max(.002,remaining/95),scoreHome=safe(match.score?.home),scoreAway=safe(match.score?.away),delta=scoreHome-scoreAway,urgency=clamp(1-remaining/60,0,1),homeState=delta<0?1+.08+.10*urgency:delta>0?1-.03*urgency:1,awayState=delta>0?1+.08+.10*urgency:delta<0?1-.03*urgency:1,lh=clamp(base.home*frac*Math.exp(tilt*.5)*homeState,.003,4),la=clamp(base.away*frac*Math.exp(-tilt*.5)*awayState,.003,4);let home=0,draw=0,away=0,sum=0;for(let h=0;h<=7;h++)for(let a=0;a<=7;a++){const p=poisson(h,lh)*poisson(a,la);sum+=p;const finalH=scoreHome+h,finalA=scoreAway+a;if(finalH>finalA)home+=p;else if(finalH===finalA)draw+=p;else away+=p}const state=normalizeModel({home:home/sum,draw:draw/sum,away:away/sum}),market=hasComplete1x2(match.markets)?normalizeMarket(match.markets):null,quality=liveDataQuality(match),marketWeight=market?clamp(.78-(quality/100)*.18,.58,.78):0,model=market?normalizeModel({home:market.home*marketWeight+state.home*(1-marketWeight),draw:market.draw*marketWeight+state.draw*(1-marketWeight),away:market.away*marketWeight+state.away*(1-marketWeight)}):state;return{model,state,remainingMinutes:remaining,lambdas:{home:lh,away:la},marketWeight,modelVersion:'LOCAL-LIVE-V2-SHADOW',validationStatus:'SHADOW_ONLY'}}
  function chooseBest(model,market,markets,marketAvailable){return[{key:'HOME',probability:model.home,marketProbability:market.home,odds:safe(markets?.home)},{key:'DRAW',probability:model.draw,marketProbability:market.draw,odds:safe(markets?.draw)},{key:'AWAY',probability:model.away,marketProbability:market.away,odds:safe(markets?.away)}].map(item=>({...item,edge:marketAvailable?item.probability-item.marketProbability:0})).sort((a,b)=>b.edge-a.edge)[0]}
  function analyzeLive(match){const marketAvailable=hasComplete1x2(match.markets),market=normalizeMarket(match.markets),live=liveStateProbabilities(match),model=live.model,pressure=Math.round(pressureIndex(match)),quality=liveDataQuality(match),uncertaintyScore=liveUncertainty(match,quality),best=chooseBest(model,market,match.markets,marketAvailable),edgePct=marketAvailable?best.edge*100:0,confidence=clamp(Math.round(quality*.58+(100-uncertaintyScore)*.27+(marketAvailable?15:0)));let classification='NO BET';if(marketAvailable&&quality>=62&&confidence>=54&&edgePct>=2)classification='WATCH';return{phase:'LIVE',pressure,quality,uncertainty:uncertaintyScore,confidence,confidenceMeaning:'DECISION_EVIDENCE_SCORE_NOT_OUTCOME_PROBABILITY',model,baseModel:live.state,market,marketAvailable,historyModel:historyProbabilities(match),historyCoverage:historicalCoverage(match),bestMarket:marketAvailable?best.key:'NO MARKET',edge:Number(edgePct.toFixed(1)),fairOdds:marketAvailable&&best.probability>0?Number((1/best.probability).toFixed(2)):null,marketOdds:marketAvailable?best.odds:null,classification,modelVersion:live.modelVersion,validationStatus:live.validationStatus,remainingMinutes:Number(live.remainingMinutes.toFixed(1)),lambdas:live.lambdas,decisionSource:'LOCAL_SHADOW_ONLY'} }
  function analyzePreMatch(match){const marketAvailable=hasComplete1x2(match.markets),market=normalizeMarket(match.markets),blended=blendPrematchModels(match),baseModel=blended.model,historyCoverage=historicalCoverage(match);if(!baseModel)return{phase:'PREMATCH',pressure:null,quality:0,uncertainty:100,confidence:0,model:{home:0,draw:0,away:0},baseModel:null,adaptiveTrust:{multiplier:1,status:'BASELINE',sources:[]},market,marketAvailable,historyModel:null,providerModel:null,historyCoverage,bestMarket:marketAvailable?'MODEL PENDING':'NO MARKET',edge:0,fairOdds:null,marketOdds:null,classification:'NO BET'};const trust=adaptiveTrust(match,'PREMATCH'),model=applyAdaptiveTrust(baseModel,market,marketAvailable,trust),best=chooseBest(model,market,match.markets,marketAvailable),edgePct=marketAvailable?best.edge*100:0,spread=Math.max(model.home,model.draw,model.away)-Math.min(model.home,model.draw,model.away),providerBonus=blended.provider?20:0,historyBonus=historyCoverage*45,quality=clamp(Math.round((marketAvailable?30:0)+providerBonus+historyBonus+(blended.provider&&blended.history?5:0))),disagreementPenalty=blended.disagreement*100*.75,uncertaintyScore=clamp(Math.round(52-spread*34+disagreementPenalty+(marketAvailable?0:22)+(1-historyCoverage)*12),16,90),confidence=clamp(Math.round(quality*.52+(100-uncertaintyScore)*.34+spread*26));let classification='NO BET';if(marketAvailable&&historyCoverage>=.5&&confidence>=73&&edgePct>=6.5)classification='PRIME';else if(marketAvailable&&historyCoverage>=.3&&confidence>=56&&edgePct>=3.5)classification='WATCH';return{phase:'PREMATCH',pressure:null,quality,uncertainty:uncertaintyScore,confidence,model,baseModel,adaptiveTrust:trust,market,marketAvailable,historyModel:blended.history,providerModel:blended.provider,modelDisagreement:Number((blended.disagreement*100).toFixed(1)),historyCoverage,bestMarket:marketAvailable?best.key:'NO MARKET',edge:Number(edgePct.toFixed(1)),fairOdds:marketAvailable&&best.probability>0?Number((1/best.probability).toFixed(2)):null,marketOdds:marketAvailable?best.odds:null,classification}}
  function analyze(match){if(match.isLive)return analyzeLive(match);if(['FT','AET','PEN','CANC','ABD','AWD','WO'].includes(match.status))return{...analyzePreMatch({...match,preMatchModel:null}),phase:'FINISHED',classification:'NO BET'};return analyzePreMatch(match)}
  window.ArgusEngine={analyze,analyzeLive,analyzePreMatch,normalizeMarket,pressureIndex,hasComplete1x2,historyProbabilities,applyAdaptiveTrust};
})();
