/* ARGUS LIVE — simple human UI, same server decision source. */
(function(){
'use strict';
const MODEL='LIVE-V2-MARKET-CALIBRATED-STATE-POISSON',UI_MS=5000,DECISION_MS=10000;let latest=[],lastAt=0,seq=0;
const n=(v,f=null)=>{if(v===null||v===undefined||v==='')return f;const x=Number(v);return Number.isFinite(x)?x:f};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function paperMarket(c,m){const s=String(c?.selection||c?.side||'').toUpperCase();if(s==='HOME')return{market:`${m.home} to win`,selection:s};if(s==='AWAY')return{market:`${m.away} to win`,selection:s};if(s==='DRAW')return{market:'Draw',selection:s};let x=s.match(/^(OVER|UNDER)_(\d+)_(\d+)$/);if(x)return{market:`${x[1]==='OVER'?'Over':'Under'} ${x[2]}.${x[3]} goals`,selection:s};if(s==='BTTS_YES')return{market:'Both teams to score',selection:s};if(s==='BTTS_NO')return{market:'Both teams NOT to score',selection:s};x=s.match(/^DOUBLE_CHANCE_(1X|12|X2)$/);if(x)return{market:`Double chance ${x[1]}`,selection:s};x=s.match(/^(HOME|AWAY)_(OVER|UNDER)_0_5$/);if(x)return{market:`${x[1]==='HOME'?m.home:m.away} ${x[2]==='OVER'?'over':'under'} 0.5 goals`,selection:s};return null}
function playLabel(c,m){return paperMarket(c,m)?.market||c?.label||String(c?.selection||'No bet').replaceAll('_',' ')}
function reason(d){const a=d?.issues||[];if(a.includes('EVIDENCE_STALE_OR_WEAK'))return'The live data is too old. ARGUS waits.';if(a.includes('DECISION_INTEGRITY_FAILURE'))return'The numbers do not match well enough. ARGUS says no.';if(a.includes('LIVE_V2_SHADOW_ONLY'))return'ARGUS likes this and saves a virtual bet to learn.';if(a.length)return'ARGUS does not like this bet enough yet.';return'ARGUS does not see a good live bet right now.'}
function row(m,d){const c=d?.candidate||null,v=String(d?.verdict||'NO BET').toUpperCase(),ready=Boolean(d?.eligible)&&['PRIME','VALUE'].includes(v),watch=v==='WATCH',rank=ready?3:watch?2:0;return{m,d,c,rank,ready,watch,play:playLabel(c,m),chance:c?.probabilityPct??(c?.probability!=null?c.probability*100:null),odds:c?.odds??null}}
async function saveTraining(rows){const windows=rows.map(r=>{const m=r.m,d=r.d,c=r.c,p=paperMarket(c,m);if(!p||c?.modelVersion!==MODEL)return null;return{fixtureId:m.id,home:m.home,away:m.away,competition:m.competition||null,kickoff:m.kickoff||null,status:'OPEN',minute:m.minute,score:m.score||null,selection:p.selection,market:p.market,odds:c.odds,modelProbability:c.probabilityPct??(c.probability*100),marketProbability:c.marketProbabilityPct??(c.marketProbability*100),fairOdds:c.fairOdds,edgePct:c.edgePct,evPct:c.evPct,quality:d.dataQuality,decisionConfidence:d.confidence?.net,observedAgeSeconds:c.observedAgeSeconds??d.evidenceFreshness?.observedAgeSeconds,modelVersion:c.modelVersion,validationStatus:c.validationStatus,freshnessStatus:d.evidenceFreshness?.status,mathIntegrity:c.mathIntegrity,veto:(d.issues||[]).filter(x=>['DECISION_INTEGRITY_FAILURE','EVIDENCE_STALE_OR_WEAK','LIVE_CANONICAL_MODEL_MISSING'].includes(x))}}).filter(Boolean);if(!windows.length)return;try{await fetch('/api/live-paper-bankroll',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({windows}),keepalive:true})}catch(_){}}
async function decide(){const cache=window.ArgusProviders?.readCache?.(),matches=(cache?.matches||[]).filter(x=>x?.isLive);if(!matches.length){latest=[];lastAt=Date.now();render();return}const id=++seq;try{const r=await fetch('/api/bet-eligibility',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({matches,preKickoffGates:[]})});if(!r.ok)throw new Error('unavailable');const j=await r.json();if(id!==seq)return;latest=matches.map(m=>row(m,j?.decisions?.[String(m.id)]||{verdict:'NO BET',eligible:false,issues:['NO_DECISION']})).sort((a,b)=>b.rank-a.rank);lastAt=Date.now();render();saveTraining(latest)}catch(_){if(id!==seq)return;latest=matches.map(m=>row(m,{verdict:'NO BET',eligible:false,issues:['NO_DECISION']}));lastAt=Date.now();render()}}
function stateLabel(r){if(r.ready)return['PLAY','play'];if(r.watch)return['WAIT','watch'];return['SKIP','wait']}
function mainCard(r){const [state,cls]=stateLabel(r),score=r.m?.score?`${r.m.score.home}-${r.m.score.away}`:'—';return `<div class="simple-live-card ${cls}"><div class="live-line"><span>${n(r.m.minute,0)}' · ${esc(score)}</span><b>${state}</b></div><h3>${esc(r.m.home)} vs ${esc(r.m.away)}</h3><div class="simple-pick"><span>ARGUS says</span><strong>${r.ready||r.watch?esc(r.play):'No bet'}</strong></div><p>${esc(reason(r.d))}</p><div class="simple-numbers"><div><span>Chance</span><strong>${r.chance!=null?`${Number(r.chance).toFixed(0)}%`:'—'}</strong></div><div><span>Odds</span><strong>${r.odds>1?Number(r.odds).toFixed(2):'—'}</strong></div></div></div>`}
function smallCard(r){const [state,cls]=stateLabel(r),score=r.m?.score?`${r.m.score.home}-${r.m.score.away}`:'—';return `<article class="simple-live-row ${cls}"><div><small>${n(r.m.minute,0)}' · ${esc(score)}</small><h4>${esc(r.m.home)} vs ${esc(r.m.away)}</h4><p>${r.ready||r.watch?esc(r.play):esc(reason(r.d))}</p></div><b>${state}</b></article>`}
function set(id,v){const x=document.getElementById(id);if(x)x.textContent=v}
function render(){const attention=latest.filter(x=>x.rank>0),ready=latest.filter(x=>x.ready),rejected=latest.length-attention.length,best=latest[0];set('liveCount',latest.length);set('liveOpportunityCount',attention.length);set('liveRejectCount',rejected);set('liveUpdated',lastAt?`Checked ${Math.max(0,Math.round((Date.now()-lastAt)/1000))}s ago`:'Waiting');set('liveRefreshState',latest.length?'Watching live matches':'Waiting for a live match');const main=document.getElementById('livePrimaryDecision');if(main)main.innerHTML=best?mainCard(best):'<div class="simple-empty"><strong>No live match right now.</strong><span>ARGUS will start automatically when a match is live.</span></div>';const grid=document.getElementById('liveCommandGrid');if(grid)grid.innerHTML=latest.length?latest.map(smallCard).join(''):'<div class="simple-empty"><strong>Nothing to show yet.</strong><span>Live choices will appear here.</span></div>';const sum=document.getElementById('liveRejectedSummary');if(sum)sum.textContent=latest.length?`${ready.length} ready to play · ${attention.length-ready.length} waiting · ${rejected} skipped.`:'Waiting for live matches.'}
async function provider(force=false){try{if(document.visibilityState==='visible')await window.ArgusProviders?.live?.({force:Boolean(force)})}catch(_){}}
function tick(){if(Date.now()-lastAt>=DECISION_MS)decide();render()}
window.addEventListener('load',async()=>{set('liveRefreshState','Refreshing live data…');await provider(true);decide();setInterval(()=>provider(false),10000);setInterval(tick,UI_MS)});document.addEventListener('argus:data-updated',decide);
})();
