/* ARGUS OMNI — PRESSURE WINDOW live timing engine. Client-side, evidence-gated, no automatic wagering. */
(function(){
'use strict';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const num=(v,f=null)=>Number.isFinite(Number(v))?Number(v):f;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const FOLLOW_KEY='argus-followed-live-matches-v1';
const SNAP_KEY='argus-pressure-local-v1';
const ALERT_SEEN_KEY='argus-pressure-open-seen-v1';
const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
const matchKey=(home,away)=>`${norm(home)}|${norm(away)}`;
function followed(){try{return new Set(JSON.parse(localStorage.getItem(FOLLOW_KEY)||'[]').map(String))}catch(_){return new Set()}}
function localMemory(){try{return JSON.parse(localStorage.getItem(SNAP_KEY)||'{}')}catch(_){return{}}}
function saveLocal(x){try{localStorage.setItem(SNAP_KEY,JSON.stringify(x))}catch(_){}}
function seenAlerts(){try{return new Set(JSON.parse(localStorage.getItem(ALERT_SEEN_KEY)||'[]'))}catch(_){return new Set()}}
function markSeen(id){const s=seenAlerts();s.add(id);try{localStorage.setItem(ALERT_SEEN_KEY,JSON.stringify([...s].slice(-100)))}catch(_){}}
function stat(m,k){return num(m?.stats?.[k],0)}
function score(m){return [num(m?.score?.home,0),num(m?.score?.away,0)]}
function totalGoals(m){const [h,a]=score(m);return h+a}
function liveMomentum(m){const shots=stat(m,'shotsHome')+stat(m,'shotsAway'),sot=stat(m,'shotsOnTargetHome')+stat(m,'shotsOnTargetAway'),corners=stat(m,'cornersHome')+stat(m,'cornersAway'),minute=Math.max(1,num(m.minute,1));return clamp((shots/minute)*145+(sot/minute)*250+(corners/minute)*80,0,100)}
function asymmetry(m){const sh=stat(m,'shotsHome'),sa=stat(m,'shotsAway'),th=stat(m,'shotsOnTargetHome'),ta=stat(m,'shotsOnTargetAway'),ch=stat(m,'cornersHome'),ca=stat(m,'cornersAway'),ph=num(m?.stats?.possessionHome,50),raw=(sh-sa)*2.1+(th-ta)*5.4+(ch-ca)*2+(ph-50)*.55;return clamp(50+raw,0,100)}
function marketBook(m){return m.multiMarkets||m.multimarkets||m.marketOdds||m.oddsMarkets||m.extraMarkets||m.marketsMulti||{} }
function oddFor(m,key){const b=marketBook(m);const aliases={over05:['over05','over0_5','totalOver05'],over15:['over15','over1_5','totalOver15'],over25:['over25','over2_5','totalOver25'],bttsYes:['bttsYes','goal','bothTeamsScoreYes'],bttsNo:['bttsNo','noGoal','bothTeamsScoreNo'],cornersOver85:['cornersOver85','cornersOver8_5'],cornersUnder85:['cornersUnder85','cornersUnder8_5'],homeOver05:['homeOver05','homeTeamOver05'],awayOver05:['awayOver05','awayTeamOver05']};for(const a of aliases[key]||[key]){const v=num(b?.[a],null);if(v&&v>1)return v}return null}
function implied(o){return o&&o>1?1/o:null}
function trendBoost(m,key){const h=m?.trend10?.home||m?.trends?.home||[],a=m?.trend10?.away||m?.trends?.away||[];const all=[...(Array.isArray(h)?h:[]),...(Array.isArray(a)?a:[])];const map={over05:['OVER_0_5_GOALS'],over15:['OVER_1_5_GOALS'],over25:['OVER_2_5_GOALS'],bttsYes:['GOAL'],bttsNo:['NO_GOAL'],cornersOver85:['CORNERS_OVER_8_5'],cornersUnder85:['CORNERS_UNDER_8_5']};return all.some(t=>map[key]?.includes(t.condition)&&t.perfect10)?7:0}
function goalProb(m,line){const minute=clamp(num(m.minute,0),0,95),g=totalGoals(m),mom=liveMomentum(m),press=Math.abs(asymmetry(m)-50)*2,remaining=Math.max(0,95-minute);const need=Math.max(0,Math.ceil(line+.001-g));if(need<=0)return .99;const rate=clamp(.019+(mom/100)*.018+(press/100)*.009,.012,.052);const lambda=rate*remaining;let p=1-Math.exp(-lambda);if(need>=2)p=1-Math.exp(-lambda)*(1+lambda);if(need>=3)p=1-Math.exp(-lambda)*(1+lambda+lambda*lambda/2);return clamp(p,.03,.96)}
function bttsProb(m){const [h,a]=score(m),minute=clamp(num(m.minute,0),0,95),remaining=Math.max(0,95-minute),p=asymmetry(m),mom=liveMomentum(m);if(h>0&&a>0)return .99;if(h===0&&a===0){const base=clamp(.30+(mom/100)*.30-(minute/95)*.16,.12,.70);return base}const trailingHome=h===0,sidePressure=trailingHome?p:(100-p),rate=clamp(.012+(sidePressure/100)*.025+(mom/100)*.012,.008,.05);return clamp(1-Math.exp(-rate*remaining),.04,.88)}
function cornersProb(m,line,over=true){const minute=Math.max(1,clamp(num(m.minute,0),1,95)),current=stat(m,'cornersHome')+stat(m,'cornersAway'),remaining=Math.max(0,95-minute),rate=current/minute,expected=current+rate*remaining*.92+(liveMomentum(m)/100)*1.4;const z=(expected-line)/2.1;const p=1/(1+Math.exp(-z));return over?clamp(p,.04,.96):clamp(1-p,.04,.96)}
function candidateMarkets(m){const out=[];const defs=[['over05','Over 0.5 goals',()=>goalProb(m,.5)],['over15','Over 1.5 goals',()=>goalProb(m,1.5)],['over25','Over 2.5 goals',()=>goalProb(m,2.5)],['bttsYes','GOAL',()=>bttsProb(m)],['bttsNo','NO GOAL',()=>1-bttsProb(m)],['cornersOver85','Corners Over 8.5',()=>cornersProb(m,8.5,true)],['cornersUnder85','Corners Under 8.5',()=>cornersProb(m,8.5,false)]];for(const [key,label,pf] of defs){const odds=oddFor(m,key);if(!odds)continue;const p=pf(),q=implied(odds),edge=(p-q)*100;out.push({key,label,odds,prob:p,implied:q,edge,trendBoost:trendBoost(m,key)})}const a=window.ArgusEngine?.analyzeLive?.(m);if(a?.marketAvailable&&a?.marketOdds>1){out.push({key:'1x2',label:a.bestMarket==='HOME'?`${m.home} win`:a.bestMarket==='AWAY'?`${m.away} win`:'Draw',odds:a.marketOdds,prob:num(a.model?.[String(a.bestMarket||'').toLowerCase()],0),implied:implied(a.marketOdds),edge:num(a.edge,0),trendBoost:0,engine:a})}return out.sort((x,y)=>(y.edge+y.trendBoost*.25)-(x.edge+x.trendBoost*.25))}
function stateFingerprint(m,market,odds){const s=m?.stats||{},sc=m?.score||{};return [m?.minute,sc.home,sc.away,s.shotsHome,s.shotsAway,s.shotsOnTargetHome,s.shotsOnTargetAway,s.cornersHome,s.cornersAway,s.possessionHome,s.possessionAway,market,odds].join('|')}
function velocity(fixtureId,pressure,odds,fingerprint){const mem=localMemory(),arr=Array.isArray(mem[fixtureId])?mem[fixtureId]:[],last=arr[arr.length-1],now=Date.now();if(last?.fingerprint===fingerprint)return{pressureVelocity:0,oddsChangePct:0,velocityFresh:false,velocityBasis:'DUPLICATE_SNAPSHOT_IGNORED'};let dv=0,oddsLag=0;if(last&&now-last.t<=12*60*1000){const mins=Math.max(.25,(now-last.t)/60000);dv=(pressure-last.pressure)/mins;if(odds&&last.odds)oddsLag=((odds-last.odds)/last.odds)*100}arr.push({t:now,pressure,odds,fingerprint});mem[fixtureId]=arr.slice(-24);saveLocal(mem);return{pressureVelocity:Number(dv.toFixed(2)),oddsChangePct:Number(oddsLag.toFixed(2)),velocityFresh:Boolean(last),velocityBasis:last?'UNIQUE_SNAPSHOT_DELTA':'FIRST_UNIQUE_SNAPSHOT'}}
function evaluate(m){if(!m?.isLive)return null;const minute=clamp(num(m.minute,0),0,120);if(minute<8||minute>88)return null;const analysis=window.ArgusEngine?.analyzeLive?.(m)||null,reg=window.ArgusLiveRegime?.evaluate?.(m,analysis)||null,pressure=num(analysis?.pressure,asymmetry(m)),momentum=liveMomentum(m),quality=num(analysis?.quality,0),uncertainty=num(analysis?.uncertainty,100),cands=candidateMarkets(m),best=cands[0]||null;if(!best)return{fixtureId:m.id,home:m.home,away:m.away,status:'WAIT',reason:'No verified live price for supported markets',pressure,momentum,quality,minute,followed:followed().has(matchKey(m.home,m.away))};const vel=velocity(String(m.id),pressure,best.odds,stateFingerprint(m,best.label,best.odds)),veto=[];if(quality<68)veto.push('LIVE_DATA_QUALITY_LOW');if(uncertainty>62)veto.push('UNCERTAINTY_HIGH');if(['REVERSAL','BROKEN'].includes(reg?.status))veto.push(`THESIS_${reg.status}`);if(best.edge<3)veto.push('EDGE_TOO_SMALL');if(best.prob<.52)veto.push('MODEL_PROBABILITY_LOW');if(momentum<28&&best.key.startsWith('over'))veto.push('TEMPO_TOO_LOW');if(num(m?.cards?.redHome,0)+num(m?.cards?.redAway,0)>0&&minute<18)veto.push('EARLY_RED_CARD_SHOCK');const marketSuspended=Boolean(m?.marketSuspended||m?.oddsSuspended||m?.marketsLocked);if(marketSuspended)veto.push('MARKET_SUSPENDED');let windowScore=38+quality*.22+(100-uncertainty)*.14+Math.min(18,Math.max(0,best.edge)*1.7)+momentum*.10+Math.min(7,best.trendBoost);if(Math.abs(pressure-50)>=22)windowScore+=5;if(vel.pressureVelocity>1.5)windowScore+=5;if(veto.length)windowScore-=veto.length*16;windowScore=clamp(Math.round(windowScore));let status='WAIT';if(!veto.length&&windowScore>=88&&best.edge>=5&&quality>=74)status='OPEN';else if(!veto.length&&windowScore>=78&&best.edge>=3.5)status='WATCH';let priceAction='HOLD';if(status!=='WAIT'&&best.edge>=6&&vel.pressureVelocity>0.6&&vel.oddsChangePct>=1.5)priceAction='PRICE_IMPROVING';else if(status==='WATCH'&&best.edge>=3.5&&momentum>=55)priceAction='WAIT_FOR_BETTER_PRICE';return{fixtureId:m.id,home:m.home,away:m.away,competition:m.competition,minute,score:m.score,status,windowScore,pressure,momentum,quality,uncertainty,market:best.label,odds:best.odds,modelProbability:Number((best.prob*100).toFixed(1)),marketProbability:Number((best.implied*100).toFixed(1)),edgePct:Number(best.edge.toFixed(1)),trendBoost:best.trendBoost,pressureVelocity:vel.pressureVelocity,oddsChangePct:vel.oddsChangePct,velocityFresh:vel.velocityFresh,velocityBasis:vel.velocityBasis,priceAction,veto,regime:reg?.status||null,followed:followed().has(matchKey(m.home,m.away)),policy:{noGuarantee:true,automaticWagering:false}}
}
async function persist(rows){if(!rows.length)return;try{await fetch('/api/pressure-window-memory',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({windows:rows}),keepalive:true})}catch(_){}}
function notifyFollowed(rows){const seen=seenAlerts();for(const x of rows){if(x.status!=='OPEN'||!x.followed||x.windowScore<90)continue;const id=`${x.fixtureId}|${x.market}|${Math.floor(x.minute/3)}`;if(seen.has(id))continue;markSeen(id);document.dispatchEvent(new CustomEvent('argus:pressure-window-open',{detail:x}));break}}
function ensureUI(){if(document.getElementById('argus-pressure-window'))return;const anchor=document.querySelector('.today-verdict')||document.querySelector('.market-shortcuts')||document.querySelector('main');if(!anchor)return;const s=document.createElement('section');s.id='argus-pressure-window';s.className='panel';s.style.cssText='margin:18px 0;padding:22px;border:1px solid rgba(155,176,143,.24);border-radius:20px;background:linear-gradient(120deg,rgba(78,111,91,.10),rgba(22,27,32,.97))';s.innerHTML='<div style="display:flex;justify-content:space-between;gap:14px;align-items:flex-start"><div><p class="eyebrow">LIVE TIMING INTELLIGENCE</p><h3 style="margin:6px 0 5px">Pressure Window</h3><p style="margin:0;color:#aaa69f;font-size:10px">Looks for temporary gaps between live evidence and the current market price. No verified gap = no window.</p></div><strong id="pw-count" style="font:700 22px Space Grotesk">0 OPEN</strong></div><div id="pw-grid" style="display:grid;gap:8px;margin-top:14px"><div style="color:#aaa69f;font-size:10px">Waiting for live matches…</div></div>';anchor.parentNode.insertBefore(s,anchor)}
function render(rows){ensureUI();const g=document.getElementById('pw-grid'),c=document.getElementById('pw-count');if(!g||!c)return;const active=rows.filter(x=>x&&['OPEN','WATCH'].includes(x.status)).sort((a,b)=>b.windowScore-a.windowScore);c.textContent=`${rows.filter(x=>x?.status==='OPEN').length} OPEN`;if(!active.length){g.innerHTML='<div style="color:#aaa69f;font-size:10px">No live pricing gap strong enough right now.</div>';return}g.innerHTML=active.slice(0,5).map(x=>`<article style="padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025)"><div style="display:flex;justify-content:space-between;gap:10px"><strong>${esc(x.home)} vs ${esc(x.away)} · ${x.minute}'</strong><b>${x.status} · ${x.windowScore}/100</b></div><div style="margin-top:7px;font-size:12px;font-weight:700">${esc(x.market)} @ ${Number(x.odds).toFixed(2)}</div><small style="display:block;color:#aaa69f;margin-top:5px">ARGUS ${x.modelProbability}% · market ${x.marketProbability}% · edge ${x.edgePct}% · pressure ${x.pressure} · momentum ${Math.round(x.momentum)}</small><small style="display:block;color:#b9c7b4;margin-top:5px">${esc(x.priceAction.replaceAll('_',' '))}${x.followed?' · FOLLOWING LIVE':''}</small></article>`).join('')}
function scan(){const row=window.ArgusProviders?.readCache?.(),matches=row?.matches||[];const evaluated=matches.filter(m=>m?.isLive).map(evaluate).filter(Boolean);render(evaluated);notifyFollowed(evaluated);persist(evaluated)}
window.ArgusPressureWindow={evaluate,scan};window.addEventListener('load',()=>{ensureUI();setTimeout(scan,1200);setInterval(scan,60000)});document.addEventListener('argus:data-updated',scan);
})();