(function(){
  const CACHE_KEY='argus-live-cache-v6';
  const PREMATCH_TTL=60*1000,LIVE_TTL=45*1000,LATE_LIVE_TTL=30*1000,SAFE_TTL=90*1000,AVAILABILITY_WINDOW_MS=100*60*1000;
  function readCache(){try{const row=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(!row||!Array.isArray(row.matches)||!row.savedAt)return null;return row}catch(_){return null}}
  function notifyDataUpdated(detail={}){try{document.dispatchEvent(new CustomEvent('argus:data-updated',{detail}))}catch(_){}}
  function writeCache(payload){try{localStorage.setItem(CACHE_KEY,JSON.stringify({matches:payload.matches||[],meta:payload.meta||null,savedAt:Date.now()}))}catch(_){}notifyDataUpdated({matches:payload.matches||[],meta:payload.meta||null})}
  function quotaInfo(row){const q=row?.meta?.quota||{},remaining=Number(q.dailyRemaining),limit=Number(q.dailyLimit),reserve=Number(q.dynamicReserve);return{remaining:Number.isFinite(remaining)?remaining:null,limit:Number.isFinite(limit)?limit:null,reserve:Number.isFinite(reserve)?reserve:null}}
  function desiredTtl(row,safeMode){const live=(row?.matches||[]).filter(m=>m?.isLive);if(!live.length)return PREMATCH_TTL;if(safeMode)return SAFE_TTL;return live.some(m=>Number(m?.minute)>=80)?LATE_LIVE_TTL:LIVE_TTL}
  function cacheStatus(){const row=readCache();if(!row)return{available:false,fresh:false,ageMs:null,safeMode:false,ttlMs:null};const ageMs=Date.now()-row.savedAt,q=quotaInfo(row),threshold=q.reserve??(q.limit?Math.max(80,Math.ceil(q.limit*.02)):80),safeMode=q.remaining!=null&&q.remaining<=threshold,ttl=desiredTtl(row,safeMode);return{available:true,fresh:ageMs<ttl,ageMs,safeMode,remaining:q.remaining,limit:q.limit,threshold,ttlMs:ttl,lateLive:(row.matches||[]).some(m=>m?.isLive&&Number(m?.minute)>=80)}}
  function cachedMatches(row){const matches=(row?.matches||[]).slice();matches.meta={...(row?.meta||{}),clientCache:true,clientCacheAgeMs:Date.now()-row.savedAt};return matches}
  function availabilityIds(matches){const now=Date.now();return matches.filter(m=>{if(m?.isFinished)return false;if(m?.isLive)return true;const k=new Date(m?.kickoff||0).getTime();return Number.isFinite(k)&&k>0&&k-now<=AVAILABILITY_WINDOW_MS&&k-now>=-30*60*1000}).map(m=>Number(m.id)).filter(Boolean)}
  async function mergeAvailability(matches,meta){const ids=availabilityIds(matches);if(!ids.length)return{matches,meta};try{const date=encodeURIComponent(meta?.date||''),res=await fetch(`/api/availability?ids=${ids.join('-')}${date?`&date=${date}`:''}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!res.ok)return{matches,meta};const data=await res.json(),map=data.availability||{},merged=matches.map(m=>map[String(m.id)]?{...m,availability:map[String(m.id)]}:m);return{matches:merged,meta:{...(meta||{}),availability:data.meta||null}}}catch(_){return{matches,meta}}}
  async function persistPredictions(){return{ok:true,skipped:true,reason:'OFFICIAL_DECISION_WRITER_ONLY'}}
  async function demo(){const response=await fetch('data/demo-matches.json',{cache:'no-store'});if(!response.ok)throw new Error('Demo feed unavailable');return response.json()}
  async function live(options={}){const force=Boolean(options.force),row=readCache(),status=cacheStatus();if(!force&&row&&status.fresh){const matches=cachedMatches(row);notifyDataUpdated({matches,meta:matches.meta,cached:true});return matches}const endpoint=window.ARGUS_LIVE_ENDPOINT||'/api/live',response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Live endpoint error ${response.status}`);const base={matches:Array.isArray(payload)?payload:payload.matches||[],meta:payload.meta||null},normalized=await mergeAvailability(base.matches,base.meta);writeCache(normalized);const matches=normalized.matches.slice();matches.meta=normalized.meta;return matches}
  async function health(){const row=readCache(),status=cacheStatus();if(row&&status.fresh)return{ready:true,cached:true,meta:{...(row.meta||{}),clientCache:true,clientCacheAgeMs:status.ageMs,clientCacheTtlMs:status.ttlMs},matches:row.matches||[]};return{ready:true,cached:false,meta:row?.meta||null,matches:row?.matches||[]}}
  window.ArgusProviders={demo,live,health,cacheStatus,readCache,persistPredictions};
})();
