(function(){
  const KEY='argus-training-memory-v1',TTL=15*60*1000,FALLBACK={version:'TRAINING-MEMORY-1',totalSettled:0,policy:{minimumSample:20,positiveSample:60,minMultiplier:.80,maxMultiplier:1.02},leagueMarket:{},market:{},league:{}};
  function readRow(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}}
  function save(payload){try{localStorage.setItem(KEY,JSON.stringify({savedAt:Date.now(),payload}))}catch(_){}return payload}
  function payload(){return readRow()?.payload||FALLBACK}
  async function refresh(force=false){const row=readRow();if(!force&&row&&Date.now()-row.savedAt<TTL)return row.payload;try{const r=await fetch('/api/training-memory',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Training memory unavailable');return save(j)}catch(_){return row?.payload||FALLBACK}}
  function canonicalMarket(label){const x=String(label||'').trim().toUpperCase();if(!x)return'UNKNOWN';if(x==='HOME'||x==='DRAW'||x==='AWAY'||x==='1X2')return'1X2';if(x.includes('EXACT')||/^\d+-\d+$/.test(x))return'EXACT SCORE';if(x.includes('BTTS'))return'BTTS';if(x.includes('CORNER'))return'CORNERS';return x}
  function profile(match,market){const p=payload(),lg=match?.competition||'UNKNOWN',mk=canonicalMarket(market),combo=p.leagueMarket?.[`${lg}|||${mk}`],marketP=p.market?.[mk],leagueP=p.league?.[lg];const candidates=[combo,marketP,leagueP].filter(x=>x&&Number.isFinite(Number(x.multiplier)));if(!candidates.length)return{multiplier:1,status:'LEARNING',sample:0,source:'NONE',reason:'No settled training evidence yet'};const min=Number(p.policy?.minMultiplier)||.8,max=Number(p.policy?.maxMultiplier)||1.02;const chosen=candidates.sort((a,b)=>(Number(b.sample)||0)-(Number(a.sample)||0))[0];let multiplier=Math.max(min,Math.min(max,Number(chosen.multiplier)||1));const statuses=candidates.map(x=>String(x.status||''));if(statuses.includes('DEGRADED'))multiplier=Math.min(multiplier,.8);else if(statuses.includes('CAUTION'))multiplier=Math.min(multiplier,.9);return{...chosen,multiplier,status:statuses.includes('DEGRADED')?'DEGRADED':statuses.includes('CAUTION')?'CAUTION':chosen.status||'LEARNING',source:combo===chosen?'LEAGUE_MARKET':marketP===chosen?'MARKET':'LEAGUE'} }
  function adjustEdge(match,market,edge){const e=Number(edge);const p=profile(match,market);return{rawEdge:Number.isFinite(e)?e:null,adjustedEdge:Number.isFinite(e)?Number((e*p.multiplier).toFixed(1)):null,...p}}
  function summary(){const p=payload(),rows=Object.values(p.leagueMarket||{});return{settled:p.totalSettled||0,profiles:rows.length,validated:rows.filter(x=>(x.sample||0)>=20).length,positive:rows.filter(x=>x.status==='VALIDATING_POSITIVE').length,caution:rows.filter(x=>['CAUTION','DEGRADED'].includes(x.status)).length,learning:rows.filter(x=>(x.sample||0)<20).length}}
  window.ArgusTrainingMemory={refresh,payload,profile,adjustEdge,summary,canonicalMarket};refresh(false);
})();
