(function(){
  const KEY='argus-training-memory-v1',CAL_KEY='argus-probability-calibration-v2',TTL=15*60*1000,FALLBACK={version:'TRAINING-MEMORY-1',totalSettled:0,policy:{minimumSample:20,positiveSample:60,minMultiplier:.80,maxMultiplier:1.02},leagueMarket:{},market:{},league:{}};
  function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch(_){return null}}
  function save(k,payload){try{localStorage.setItem(k,JSON.stringify({savedAt:Date.now(),payload}))}catch(_){}return payload}
  function payload(){return read(KEY)?.payload||FALLBACK}
  async function fetchJson(url){const r=await fetch(url,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||url);return j}
  async function refresh(force=false){const row=read(KEY),calRow=read(CAL_KEY),fresh=row&&Date.now()-row.savedAt<TTL,calFresh=calRow&&Date.now()-calRow.savedAt<TTL;if(!force&&fresh&&calFresh)return row.payload;const jobs=[];if(force||!fresh)jobs.push(fetchJson('/api/training-memory').then(j=>save(KEY,j)).catch(()=>row?.payload||FALLBACK));else jobs.push(Promise.resolve(row.payload));if(force||!calFresh)jobs.push(fetchJson('/api/probability-calibration').then(j=>save(CAL_KEY,j)).catch(()=>calRow?.payload||null));else jobs.push(Promise.resolve(calRow.payload));const [training]=await Promise.all(jobs);return training}
  function canonicalMarket(label){const x=String(label||'').trim().toUpperCase();if(!x)return'UNKNOWN';if(x==='HOME'||x==='DRAW'||x==='AWAY'||x==='1X2')return'1X2';if(x.includes('EXACT')||/^\d+-\d+$/.test(x)||x.startsWith('SCORE:'))return'EXACT SCORE';if(x.includes('BTTS'))return'BTTS';if(x.includes('CORNER'))return'CORNERS';return x}
  function profile(match,market){const p=payload(),lg=match?.competition||'UNKNOWN',mk=canonicalMarket(market),combo=p.leagueMarket?.[`${lg}|||${mk}`],marketP=p.market?.[mk],leagueP=p.league?.[lg];const candidates=[combo,marketP,leagueP].filter(x=>x&&Number.isFinite(Number(x.multiplier)));if(!candidates.length)return{multiplier:1,status:'LEARNING',sample:0,source:'NONE',reason:'No settled training evidence yet'};const min=Number(p.policy?.minMultiplier)||.8,max=Number(p.policy?.maxMultiplier)||1.02,chosen=candidates.sort((a,b)=>(Number(b.sample)||0)-(Number(a.sample)||0))[0];let multiplier=Math.max(min,Math.min(max,Number(chosen.multiplier)||1));const statuses=candidates.map(x=>String(x.status||''));if(statuses.includes('DEGRADED'))multiplier=Math.min(multiplier,.8);else if(statuses.includes('CAUTION'))multiplier=Math.min(multiplier,.9);return{...chosen,multiplier,status:statuses.includes('DEGRADED')?'DEGRADED':statuses.includes('CAUTION')?'CAUTION':chosen.status||'LEARNING',source:combo===chosen?'LEAGUE_MARKET':marketP===chosen?'MARKET':'LEAGUE'}}
  function adjustEdge(match,market,edge){const e=Number(edge),p=profile(match,market);return{rawEdge:Number.isFinite(e)?e:null,adjustedEdge:Number.isFinite(e)?Number((e*p.multiplier).toFixed(1)):null,...p}}
  function summary(){const p=payload(),rows=Object.values(p.leagueMarket||{});return{settled:p.totalSettled||0,profiles:rows.length,validated:rows.filter(x=>(x.sample||0)>=20).length,positive:rows.filter(x=>x.status==='VALIDATING_POSITIVE').length,caution:rows.filter(x=>['CAUTION','DEGRADED'].includes(x.status)).length,learning:rows.filter(x=>(x.sample||0)<20).length}}
  function calPayload(){return read(CAL_KEY)?.payload||null}
  function calBucket(p){const pc=Math.max(0,Math.min(99.999,Number(p)*100)),lo=Math.floor(pc/5)*5;return `${lo}-${lo+5}`}
  function calProfile(marketKey,p){const data=calPayload();if(!data||!Number.isFinite(Number(p)))return null;const mk=String(marketKey||'UNKNOWN').toUpperCase();return data.marketBucket?.[`${mk}|||${calBucket(p)}`]||data.market?.[mk]||data.globalBucket?.[calBucket(p)]||null}
  function calAdjust(marketKey,p){const raw=Number(p);if(!Number.isFinite(raw))return{raw:p,calibrated:p,adjustment:0,status:'NO_DATA',profile:null};const prof=calProfile(marketKey,raw);if(!prof||Number(prof.sample)<20)return{raw,calibrated:raw,adjustment:0,status:prof?.status||'UNVALIDATED',profile:prof};const adj=Number(prof.governedAdjustment)||0,cal=Math.max(.01,Math.min(.99,raw+adj));return{raw,calibrated:cal,adjustment:adj,status:prof.status,profile:prof}}
  window.ArgusTrainingMemory={refresh,payload,profile,adjustEdge,summary,canonicalMarket};
  window.ArgusProbabilityCalibration={refresh:async(force=false)=>{await refresh(force);return calPayload()},payload:calPayload,profile:calProfile,adjust:calAdjust};
  refresh(false);
})();