import { listJson, readManyJson, readJson, writeJson, storageReady } from './_report-store.js';
const REGISTRY_PATH='argus/autopilot/adaptive-weight-registry.json';
function num(v){const x=Number(v);return Number.isFinite(x)?x:null}
function bucketConfidence(c){const n=num(c);if(n==null)return'UNKNOWN';if(n<50)return'<50';if(n<60)return'50-59';if(n<70)return'60-69';if(n<80)return'70-79';return'80+'}
function add(map,key,row){if(!map[key])map[key]={n:0,w:0,l:0,pl:0};const a=map[key];a.n++;if(row.outcome==='WIN')a.w++;if(row.outcome==='LOSS')a.l++;if(num(row.pl)!=null)a.pl+=Number(row.pl)}
function profile(a){const settled=a.w+a.l,roi=settled?100*a.pl/settled:null;let multiplier=1,status='BASELINE',reason='Insufficient evidence for adaptation';if(settled>=20){if(roi<=-15){multiplier=.78;status='DEGRADED';reason='Strong negative out-of-sample ROI'}else if(roi<=-5){multiplier=.88;status='CAUTION';reason='Negative out-of-sample ROI'}else if(roi>=8&&settled>=50){multiplier=1.04;status='VALIDATING_POSITIVE';reason='Positive evidence; upside capped by governance'}else{status='NEUTRAL';reason='Evidence does not justify material adaptation'}}return{sample:settled,wins:a.w,losses:a.l,roi:roi==null?null:Number(roi.toFixed(2)),multiplier,status,reason}}
function finish(map){return Object.fromEntries(Object.entries(map).map(([k,a])=>[k,profile(a)]))}
function stableView(payload){return{league:payload.league,confidence:payload.confidence,classification:payload.classification,phase:payload.phase}}
function hash(value){const s=JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Adaptive weights storage unavailable'});const blobs=await listJson('argus/reports/',400),reports=await readManyJson(blobs),league={},confidence={},classification={},phase={};let settled=0;for(const report of reports)for(const row of report.matches||[]){if(!['WIN','LOSS'].includes(row.outcome)||!row.prediction)continue;settled++;add(league,row.competition||'UNKNOWN',row);add(confidence,bucketConfidence(row.prediction.confidence),row);add(classification,row.prediction.classification||'UNKNOWN',row);add(phase,row.prediction.phase||'UNKNOWN',row)}const payload={version:'ADAPTIVE-WEIGHTS-2',generatedAt:new Date().toISOString(),settled,policy:{minimumSample:20,positiveSample:50,minMultiplier:.78,maxMultiplier:1.04,primeUnlock:false,rule:'Adaptation is bounded, evidence-driven, versioned, and may never bypass V7/V8/V12 governance.'},league:finish(league),confidence:finish(confidence),classification:finish(classification),phase:finish(phase)};const fingerprint=hash(stableView(payload));const registry=await readJson(REGISTRY_PATH,{version:'ADAPTIVE-REGISTRY-1',currentFingerprint:null,versions:[]});registry.versions=Array.isArray(registry.versions)?registry.versions:[];if(registry.currentFingerprint!==fingerprint){const number=(registry.versions.at(-1)?.number||0)+1;registry.versions.push({number,fingerprint,createdAt:payload.generatedAt,settled,payload:stableView(payload)});if(registry.versions.length>50)registry.versions=registry.versions.slice(-50);registry.currentFingerprint=fingerprint;registry.updatedAt=payload.generatedAt;await writeJson(REGISTRY_PATH,registry)}payload.registry={fingerprint,currentVersion:registry.versions.at(-1)?.number||1,versionsStored:registry.versions.length,rollbackReady:registry.versions.length>1};return res.status(200).json(payload)}