import { readJson, writeJson, storageReady } from './_report-store.js';

const ALERT_STATE='argus/alerts/state.json';
const ALERT_FEED='argus/alerts/feed.json';
const now=()=>new Date().toISOString();
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function keyOf(x){return `${x.fixtureId}|${x.selection||x.eligibilityCandidate?.side||''}|${x.finalVerdict||''}`}
function score(row){let s=n(row.score);if(row.finalVerdict==='PRIME')s+=12;else if(row.finalVerdict==='VALUE')s+=5;if(row.betEligible)s+=8;if(row.preKickoffGate==='PASSED')s+=5;if(row.lineupsConfirmed)s+=4;if(row.portfolioBlocked)s-=30;if(row.marketRegime==='VOLATILE'||row.marketRegime?.regime==='VOLATILE')s-=10;if(row.preKickoffGate==='BLOCKED')s-=25;return Math.max(0,Math.min(100,Math.round(s)))}
function qualifies(row){if(!row||row.isLive||row.status==='FT'||row.portfolioBlocked||!row.betEligible)return false;if(!['PRIME','VALUE'].includes(row.finalVerdict))return false;const s=score(row),edge=n(row.eligibilityCandidate?.edge,row.edge),conf=n(row.netConfidence,row.confidence);if(row.finalVerdict==='PRIME')return s>=88&&conf>=65;if(row.finalVerdict==='VALUE')return s>=82&&conf>=70&&edge>=4;return false}
function reason(row){const out=[];out.push(`${row.finalVerdict} eligible`);if(row.lineupsConfirmed)out.push('lineups confirmed');if(row.preKickoffGate==='PASSED')out.push('pre-kickoff gate passed');if(n(row.netConfidence)>0)out.push(`confidence ${n(row.netConfidence)}%`);const e=n(row.eligibilityCandidate?.edge,row.edge);if(e)out.push(`edge ${e.toFixed(1)}%`);return out.join(' · ')}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET'&&req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Alert storage unavailable'});const plan=await readJson('argus/autopilot/decision-plan.json',{plan:[],generatedAt:null});const state=await readJson(ALERT_STATE,{seen:{}}),feed=await readJson(ALERT_FEED,{alerts:[]});const ts=Date.now(),cooldownMs=90*60*1000,newAlerts=[];for(const row of plan.plan||[]){if(!qualifies(row))continue;const k=keyOf(row),prev=state.seen[k],sc=score(row),odds=n(row.stakeOdds,row.eligibilityCandidate?.odds);const materiallyBetter=prev&&((odds&&prev.odds&&odds>=prev.odds*1.04)||(sc-prev.score>=6)||(row.lineupsConfirmed&&!prev.lineupsConfirmed));if(prev&&ts-prev.sentAt<cooldownMs&&!materiallyBetter)continue;const alert={id:`${k}|${ts}`,createdAt:now(),fixtureId:row.fixtureId,competition:row.competition,home:row.home,away:row.away,kickoff:row.kickoff,verdict:row.finalVerdict,selection:row.stakeSelection||row.eligibilityCandidate?.side||null,odds:odds||null,confidence:row.netConfidence??null,score:sc,reason:reason(row),risk:(row.eligibilityIssues||[]).slice(0,3),type:prev?'SIGNAL_UPGRADED':'HIGH_INTEREST'};newAlerts.push(alert);state.seen[k]={sentAt:ts,score:sc,odds:odds||null,lineupsConfirmed:Boolean(row.lineupsConfirmed)}}if(newAlerts.length){feed.alerts=[...newAlerts,...(feed.alerts||[])].slice(0,100);await writeJson(ALERT_FEED,feed);await writeJson(ALERT_STATE,state)}return res.status(200).json({version:'ALERT-ENGINE-1',generatedAt:now(),newAlerts,feed:feed.alerts||[],policy:{primeThreshold:88,valueThreshold:82,cooldownMinutes:90,liveAlerts:false,automaticWagering:false,rule:'Notify only genuinely eligible high-interest situations; never manufacture alerts to create activity.'}})}
