export const config={maxDuration:120};
function authorized(req){const secret=String(process.env.CRON_SECRET||'').trim();return !secret||req.headers.authorization===`Bearer ${secret}`}
function brusselsClock(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Brussels',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return{hour:Number(p.hour),minute:Number(p.minute)}}
async function jsonFetch(url,options={}){const secret=String(process.env.CRON_SECRET||'').trim(),internalAuth=secret?`Bearer ${secret}`:null;const r=await fetch(url,{...options,headers:{Accept:'application/json',...(internalAuth?{Authorization:internalAuth}:{}),...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`${url} -> HTTP ${r.status}: ${data.error||'request failed'}`);return data}
function compactEligibilityMatch(m={}){return{id:m.id,fixtureId:m.fixtureId,kickoff:m.kickoff||null,home:m.home||null,away:m.away||null,competition:m.competition||null,isFinished:Boolean(m.isFinished),preMatchModel:m.preMatchModel||null,markets:m.markets||{},marketOdds:{coverage:Number(m.marketOdds?.coverage)||0},history90d:{home:m.history90d?.home?{matches:Number(m.history90d.home.matches)||0}:null,away:m.history90d?.away?{matches:Number(m.history90d.away.matches)||0}:null},confidence:m.confidence??null,confidencePenalty:Number(m.confidencePenalty)||0,dataQuality:m.dataQuality??null,quality:m.quality??null,marketRegime:m.marketRegime?{regime:m.marketRegime.regime||null,directionalStatus:m.marketRegime.directionalStatus||null,timingAction:m.marketRegime.timingAction||null,timingReason:m.marketRegime.timingReason||null,timingTimeBucket:m.marketRegime.timingTimeBucket||null,lastAgeMinutes:m.marketRegime.lastAgeMinutes??null,selectedMovePct:m.marketRegime.selectedMovePct??null}:null,matchContext:m.matchContext?.regime?{regime:m.matchContext.regime}:null,playerImpact:m.playerImpact?{lineupsConfirmed:Boolean(m.playerImpact.lineupsConfirmed)}:null,crossSourceAgreement:m.crossSourceAgreement||null,uncertaintyBudget:m.uncertaintyBudget||null}}
function projectBody(path,body={}){if(path==='/api/decision-stability')return{matches:(Array.isArray(body.matches)?body.matches:[]).map(m=>({id:m?.id,fixtureId:m?.fixtureId}))};if(path==='/api/bet-eligibility')return{matches:(Array.isArray(body.matches)?body.matches:[]).map(compactEligibilityMatch),preKickoffGates:Array.isArray(body.preKickoffGates)?body.preKickoffGates:[]};return body}
function post(base,path,body){const projected=projectBody(path,body);return jsonFetch(`${base}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(projected)})}
function minutesToKickoff(m){const t=new Date(m?.kickoff||0).getTime();return Number.isFinite(t)?Math.round((t-Date.now())/60000):99999}
function canBackfill(meta={}){const remaining=Number(meta?.quota?.dailyRemaining);return !Number.isFinite(remaining)||remaining>500}
export default async function handler(req,res){
 res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!authorized(req))return res.status(401).json({error:'Unauthorized'});
 const clock=brusselsClock(),active=clock.hour>=6||(clock.hour===0&&clock.minute<=30);if(!active)return res.status(200).json({ok:true,skipped:true,reason:'OUTSIDE_ACTIVE_WINDOW',brussels:clock});
 const proto=(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers['x-forwarded-host']||req.headers.host||'argus-omni-live.vercel.app',productionHost=String(process.env.VERCEL_PROJECT_PRODUCTION_URL||'').trim().replace(/^https?:\/\//,''),base=productionHost?`https://${productionHost}`:`${proto}://${host}`,started=Date.now();
 try{
  let existing=null;try{existing=await jsonFetch(`${base}/api/decision-scheduler`)}catch(_){}const oldPlan=Array.isArray(existing?.plan)?existing.plan:[],cadences=oldPlan.map(x=>Number(x.cadenceMinutes)).filter(Number.isFinite),cadence=cadences.length?Math.max(5,Math.min(...cadences)):30,last=existing?.generatedAt?new Date(existing.generatedAt).getTime():0,ageMinutes=last?Math.floor((Date.now()-last)/60000):Infinity,urgent=oldPlan.some(x=>{const m=minutesToKickoff(x);return m>=0&&m<=69});if(ageMinutes<cadence&&!urgent)return res.status(200).json({ok:true,skipped:true,reason:'NOT_DUE',ageMinutes,cadenceMinutes:cadence,brussels:clock,elapsedMs:Date.now()-started});
  const live=await jsonFetch(`${base}/api/live`),matches=Array.isArray(live.matches)?live.matches:[];if(!matches.length)return res.status(200).json({ok:true,skipped:true,reason:'NO_FIXTURES',brussels:clock,elapsedMs:Date.now()-started,meta:live.meta||null});const payload={matches,meta:live.meta||{}};
  let tacticalBackfill={processedTeams:0,totalSaved:0,matchupSaved:0,skipped:!canBackfill(live.meta)};if(canBackfill(live.meta))try{tacticalBackfill=await post(base,'/api/tactical-backfill',payload)}catch(_){}
  let availability={availability:{},meta:{requested:0,loaded:0}};const near=matches.filter(m=>!m.isLive&&!m.isFinished&&minutesToKickoff(m)>=0&&minutesToKickoff(m)<=180).map(m=>m.id).filter(Boolean);if(near.length)try{availability=await jsonFetch(`${base}/api/availability?ids=${near.join('-')}`)}catch(_){}
  let memory={profiles:{},playerCount:0,savedLineups:0,settledMatches:0};try{memory=await post(base,'/api/player-memory',{...payload,availability:availability.availability||{}})}catch(_){}
  let playerImpact={impact:{},fixtures:0};if(near.length)try{playerImpact=await post(base,'/api/player-impact',{...payload,availability:availability.availability||{},profiles:memory.profiles||{}})}catch(_){}const playerAdjusted=matches.map(m=>{const x=playerImpact.impact?.[String(m.id)];return x?.adjustedModel?{...m,rawPreMatchModel:m.preMatchModel,preMatchModel:x.adjustedModel,playerImpact:x}:m});
  let tacticalImpact={impact:{},fixtures:0};if(near.length)try{tacticalImpact=await post(base,'/api/tactical-impact',{matches:playerAdjusted,availability:availability.availability||{}})}catch(_){}const tacticalAdjusted=playerAdjusted.map(m=>{const x=tacticalImpact.impact?.[String(m.id)];return x?.adjustedModel?{...m,preTacticalModel:m.preMatchModel,preMatchModel:x.adjustedModel,tacticalImpact:x}:m});
  let matchupImpact={impact:{},fixtures:0};if(near.length)try{matchupImpact=await post(base,'/api/matchup-impact',{matches:tacticalAdjusted,availability:availability.availability||{}})}catch(_){}const matchupAdjusted=tacticalAdjusted.map(m=>{const x=matchupImpact.impact?.[String(m.id)];return x?.adjustedModel?{...m,preMatchupModel:m.preMatchModel,preMatchModel:x.adjustedModel,matchupImpact:x}:m});
  let competitionContext={impact:{},fixtures:0,learned:0};try{competitionContext=await post(base,'/api/competition-context',{matches:matchupAdjusted})}catch(_){}const competitionAdjusted=matchupAdjusted.map(m=>{const x=competitionContext.impact?.[String(m.id)];return x?.adjustedModel?{...m,preCompetitionModel:m.preMatchModel,preMatchModel:x.adjustedModel,competitionContext:x}:m});
  let matchContext={impact:{},fixtures:0};try{matchContext=await post(base,'/api/match-context',{matches:competitionAdjusted})}catch(_){}const contextAdjusted=competitionAdjusted.map(m=>{const x=matchContext.impact?.[String(m.id)];return x?.adjustedModel?{...m,preContextModel:m.preMatchModel,preMatchModel:x.adjustedModel,matchContext:x}:m});
  let calibration={league:{},classification:{},phase:{},settled:0};try{calibration=await jsonFetch(`${base}/api/calibration-engine`)}catch(_){}let forensics={settled:0,failureMode:{}};try{forensics=await post(base,'/api/postmatch-forensics',{})}catch(_){}
  let calibrationImpact={impact:{},fixtures:0,applied:0};try{calibrationImpact=await post(base,'/api/calibration-impact',{matches:contextAdjusted,calibration})}catch(_){}const calibrated=contextAdjusted.map(m=>{const x=calibrationImpact.impact?.[String(m.id)];return x?.adjustedModel?{...m,preCalibrationModel:m.preMatchModel,preMatchModel:x.adjustedModel,calibrationImpact:x}:m});
  let falsePositiveMemory={settled:0,league:{},classification:{},edge:{},confidence:{},composite:{}};try{falsePositiveMemory=await jsonFetch(`${base}/api/false-positive-memory`)}catch(_){}let confidenceCalibration={impact:{},fixtures:0};try{confidenceCalibration=await post(base,'/api/confidence-calibration',{matches:calibrated,memory:falsePositiveMemory})}catch(_){}const confidenceAdjusted=calibrated.map(m=>{const x=confidenceCalibration.impact?.[String(m.id)];return x?{...m,confidenceCalibration:x,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.confidencePenalty||0)}:m});
  let marketRegime={regimes:{},fixtures:0};try{marketRegime=await post(base,'/api/market-regime',{matches:confidenceAdjusted})}catch(_){}const marketAdjusted=confidenceAdjusted.map(m=>{const x=marketRegime.regimes?.[String(m.id)];return x?{...m,marketRegime:x,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.confidencePenalty||0)}:m});
  let agreement={agreement:{},summary:{}};try{agreement=await post(base,'/api/cross-source-agreement',{matches:marketAdjusted})}catch(_){}const agreementAdjusted=marketAdjusted.map(m=>{const x=agreement.agreement?.[String(m.id)];return x?{...m,crossSourceAgreement:x,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.penalty||0)}:m});
  let decay={signals:{},summary:{}};try{decay=await post(base,'/api/signal-decay',{matches:agreementAdjusted})}catch(_){}const decayedMatches=agreementAdjusted.map(m=>{const x=decay.signals?.[String(m.id)];return x?{...m,signalDecay:x,signalDecayStatus:x.status,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.penalty||0)}:m});
  const prePayload={matches:decayedMatches,meta:live.meta||{}},gate=await post(base,'/api/prekickoff-gate',{...prePayload,availability:availability.availability||{}});let uncertainty={budgets:{},summary:{}};try{uncertainty=await post(base,'/api/uncertainty-budget',{matches:decayedMatches,preKickoffGates:gate.gates||[]})}catch(_){}const uncertainMatches=decayedMatches.map(m=>{const x=uncertainty.budgets?.[String(m.id)];return x?{...m,uncertaintyBudget:x,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.confidencePenalty||0)}:m});
  let stability={stability:{},summary:{}};try{stability=await post(base,'/api/decision-stability',{matches:uncertainMatches})}catch(_){}const impactedMatches=uncertainMatches.map(m=>{const x=stability.stability?.[String(m.id)];return x?{...m,decisionStability:x,confidencePenalty:Number(m.confidencePenalty||0)+Number(x.penalty||0)}:m}),impactedPayload={matches:impactedMatches,meta:live.meta||{}};
  const eligibility=await post(base,'/api/bet-eligibility',{...impactedPayload,preKickoffGates:gate.gates||[]});
  let stress={stress:{},summary:{}};try{stress=await post(base,'/api/decision-robustness',{matches:impactedMatches,eligibility})}catch(_){}let robustEligibility=eligibility;try{robustEligibility=await post(base,'/api/robustness-gate',{eligibility,stress})}catch(_){}
  const portfolio=await post(base,'/api/portfolio-risk',{...impactedPayload,eligibility:robustEligibility}),staking=await post(base,'/api/stake-intelligence',{eligibility:robustEligibility,portfolio}),events=await post(base,'/api/live-events',impactedPayload),market=await post(base,'/api/market-memory',impactedPayload),scheduler=await post(base,'/api/decision-scheduler',{...impactedPayload,events:events.events||[],preKickoffGates:gate.gates||[],eligibility:robustEligibility,portfolio,staking});
  let lifecycle={added:0,tracked:0};try{lifecycle=await post(base,'/api/opportunity-lifecycle',{plan:scheduler.plan||[]})}catch(_){}
  return res.status(200).json({ok:true,skipped:false,matches:matches.length,events:events.detected||0,forcedRechecks:events.forcedRechecks||0,marketSnapshots:market.saved||0,signalDecay:decay.summary||null,crossSourceAgreement:agreement.summary||null,uncertaintyBudget:uncertainty.summary||null,decisionStability:stability.summary||null,robustness:stress.summary||null,lifecycle:{added:lifecycle.added||0,tracked:lifecycle.tracked||0},availability:{...(availability.meta||{}),monitoringWindowMinutes:180},tacticalBackfill:{processedTeams:tacticalBackfill.processedTeams||0,totalSaved:tacticalBackfill.totalSaved||0,matchupSaved:tacticalBackfill.matchupSaved||0,skipped:Boolean(tacticalBackfill.skipped)},playerMemory:{players:memory.playerCount||0,savedLineups:memory.savedLineups||0,settledMatches:memory.settledMatches||0,validatedProfiles:Object.values(memory.profiles||{}).filter(p=>p?.validated).length},playerImpactFixtures:playerImpact.fixtures||0,tacticalImpactFixtures:tacticalImpact.fixtures||0,matchupImpactFixtures:matchupImpact.fixtures||0,competitionContext:{fixtures:competitionContext.fixtures||0,learned:competitionContext.learned||0},matchContext:{fixtures:matchContext.fixtures||0},calibration:{settled:calibration.settled||0,fixtures:calibrationImpact.fixtures||0,applied:calibrationImpact.applied||0},postMatchForensics:{settled:forensics.settled||0,structuralRisks:Object.values(forensics.failureMode||{}).filter(x=>x?.status==='STRUCTURAL_RISK').length},falsePositiveMemory:{settled:falsePositiveMemory.settled||0,riskProfiles:Object.values(falsePositiveMemory.composite||{}).filter(x=>x?.status==='FALSE_POSITIVE_RISK').length},confidenceCalibration:{fixtures:confidenceCalibration.fixtures||0,penalized:Object.values(confidenceCalibration.impact||{}).filter(x=>Number(x?.confidencePenalty)>0).length},marketRegime:{fixtures:marketRegime.fixtures||0,volatile:Object.values(marketRegime.regimes||{}).filter(x=>x?.regime==='VOLATILE').length,stale:Object.values(marketRegime.regimes||{}).filter(x=>x?.regime==='STALE').length},preKickoff:gate.summary||null,eligibility:robustEligibility.summary||null,portfolio:portfolio.summary||null,staking:staking.summary||null,scheduler:scheduler.summary||null,security:{internalCronAuthPropagated:Boolean(String(process.env.CRON_SECRET||'').trim()),internalBaseUsesProductionDomain:Boolean(productionHost)},brussels:clock,elapsedMs:Date.now()-started})
 }catch(error){return res.status(500).json({ok:false,error:error.message,brussels:clock,elapsedMs:Date.now()-started})}
}
