import { readJson, writeJson, storageReady } from './_report-store.js';
import { providerPlanMeta } from './_provider-plan.js';

const API_BASE='https://v3.football.api-sports.io';
const TZ='Europe/Brussels';
const INJURY_TTL=4*60*60*1000;
const FIXTURE_TTL=8*60*1000;
const QUOTA_GUARD_PATH='argus/data/api-football-quota-guard.json';
const MINUTE_RESERVE=5;
const AVAILABILITY_RESERVE_RATIO=.04;
const MIN_AVAILABILITY_RESERVE=300;

function headers(){const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error('API_FOOTBALL_KEY is not configured');return {'x-apisports-key':key,Accept:'application/json'}}
function headerNumber(h,name){const raw=h.get(name);if(raw==null||raw==='')return null;const n=Number(raw);return Number.isFinite(n)?n:null}
function providerDayUtc(){return new Date().toISOString().slice(0,10)}
function guardDay(g){return g?.providerDayUtc||g?.date||String(g?.observedAt||'').slice(0,10)||null}
function guardCurrent(g){return Boolean(g)&&guardDay(g)===providerDayUtc()}
function reserve(limit){const configured=Number(providerPlanMeta()?.dailyLimit)||7500,l=Number(limit)||configured;return Math.max(MIN_AVAILABILITY_RESERVE,Math.ceil(l*AVAILABILITY_RESERVE_RATIO))}
function quotaErrorKind(data){const text=JSON.stringify(data?.errors||data||{}).toLowerCase();if(text.includes('per minute')||text.includes('requests per minute'))return'minute';if(text.includes('daily')||text.includes('per day')||text.includes('request limit')||text.includes('rate limit')||text.includes('too many requests'))return'daily';return null}
function seedQuota(guard){const current=guardCurrent(guard);return{providerCalls:0,dailyLimit:current&&Number(guard?.dailyLimit)>0?Number(guard.dailyLimit):(Number(providerPlanMeta()?.dailyLimit)||7500),dailyRemaining:current&&Number.isFinite(Number(guard?.dailyRemaining))?Number(guard.dailyRemaining):null,minuteRemaining:current&&Number.isFinite(Number(guard?.minuteRemaining))?Number(guard.minuteRemaining):null,kind:current&&guard?.exhausted?'daily':null,providerError:current?guard?.providerError||null:null,observedAt:current?guard?.observedAt||null:null}}
function quotaBlocked(q){if(q.kind==='daily')return true;if(q.dailyRemaining!=null&&q.dailyRemaining<=reserve(q.dailyLimit))return true;if(q.minuteRemaining!=null&&q.minuteRemaining<=MINUTE_RESERVE)return true;return false}
function captureQuota(q,h){const limit=headerNumber(h,'x-ratelimit-requests-limit'),remaining=headerNumber(h,'x-ratelimit-requests-remaining'),minute=headerNumber(h,'x-ratelimit-remaining');if(limit!=null)q.dailyLimit=limit;if(remaining!=null)q.dailyRemaining=remaining;if(minute!=null)q.minuteRemaining=minute;q.observedAt=new Date().toISOString()}
async function apiGet(path,q){if(quotaBlocked(q))throw new Error('API-Football availability quota reserve protected');q.providerCalls++;const r=await fetch(`${API_BASE}${path}`,{headers:headers()});captureQuota(q,r.headers);const data=await r.json().catch(()=>({})),kind=quotaErrorKind(data);if(kind){q.kind=kind;q.providerError=JSON.stringify(data?.errors||data||{});if(kind==='daily')q.dailyRemaining=0;throw new Error(kind==='minute'?'API-Football minute rate limit':'API-Football daily quota exhausted')}if(!r.ok)throw new Error(`API-Football HTTP ${r.status}`);if(data?.errors&&Object.keys(data.errors).length)throw new Error(`API-Football: ${JSON.stringify(data.errors)}`);return data}
async function persistQuota(q,previous){if(!storageReady()||!q.observedAt)return;try{const current=await readJson(QUOTA_GUARD_PATH,null);if(guardCurrent(current)&&current?.exhausted)return;const dailyLimit=Number(q.dailyLimit)||Number(providerPlanMeta()?.dailyLimit)||7500,dailyRemaining=q.kind==='daily'?0:(Number.isFinite(Number(q.dailyRemaining))?Math.max(0,Number(q.dailyRemaining)):null),used=dailyRemaining==null?null:Math.max(0,dailyLimit-dailyRemaining),mode=q.kind==='daily'?'HALT':q.kind==='minute'?'THROTTLED':dailyRemaining!=null&&dailyRemaining<=reserve(dailyLimit)?'CRITICAL':dailyRemaining!=null&&dailyRemaining<=Math.ceil(dailyLimit*.2)?'THROTTLED':'NORMAL';await writeJson(QUOTA_GUARD_PATH,{...(guardCurrent(previous)?previous:{}),date:providerDayUtc(),providerDayUtc:providerDayUtc(),exhausted:q.kind==='daily',mode,reason:q.kind==='daily'?'PROVIDER_QUOTA_EXHAUSTED':q.kind==='minute'?'MINUTE_RATE_LIMIT_RECOVERABLE':null,dailyLimit,dailyRemaining,used,minuteRemaining:q.minuteRemaining,observedAt:q.observedAt,source:'API_FOOTBALL_AVAILABILITY',providerError:q.kind?q.providerError:null})}catch(_){}}
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
function chunk(a,n){const out=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out}
async function injuries(date,q,providerAllowed){const path=`argus/data/injuries-${date}.json`;let cached=null;if(storageReady())try{cached=await readJson(path,null)}catch(_){}if(cached?.savedAt&&Date.now()-new Date(cached.savedAt).getTime()<INJURY_TTL&&Array.isArray(cached.response))return {rows:cached.response,cache:'HIT'};if(!providerAllowed||quotaBlocked(q))return{rows:cached?.response||[],cache:cached?.response?'STALE_QUOTA':'BLOCKED_QUOTA',error:'QUOTA_GUARD'};try{const data=await apiGet(`/injuries?date=${date}&timezone=${encodeURIComponent(TZ)}`,q),rows=data.response||[];if(storageReady())try{await writeJson(path,{savedAt:new Date().toISOString(),response:rows})}catch(_){}return {rows,cache:'MISS'}}catch(error){return {rows:cached?.response||[],cache:cached?.response?'STALE':'ERROR',error:error.message}}}
async function fixtures(ids,q,providerAllowed){const key=ids.slice().sort((a,b)=>a-b).join('-'),path=`argus/data/availability-fixtures-${key}.json`;let cached=null;if(storageReady())try{cached=await readJson(path,null)}catch(_){}if(cached?.savedAt&&Date.now()-new Date(cached.savedAt).getTime()<FIXTURE_TTL&&Array.isArray(cached.response))return{rows:cached.response,cache:'HIT'};if(!providerAllowed||quotaBlocked(q))return{rows:cached?.response||[],cache:cached?.response?'STALE_QUOTA':'BLOCKED_QUOTA',error:'QUOTA_GUARD'};try{const rows=[];for(const group of chunk(ids,20)){if(quotaBlocked(q))break;const data=await apiGet(`/fixtures?ids=${group.join('-')}&timezone=${encodeURIComponent(TZ)}`,q);rows.push(...(data.response||[]))}if(rows.length&&storageReady())try{await writeJson(path,{savedAt:new Date().toISOString(),response:rows})}catch(_){}return{rows:rows.length?rows:(cached?.response||[]),cache:rows.length?'MISS':cached?.response?'STALE_QUOTA':'BLOCKED_QUOTA'}}catch(error){return{rows:cached?.response||[],cache:cached?.response?'STALE':'ERROR',error:error.message}}}
function injuryIndex(rows){const map=new Map();for(const row of rows||[]){const fid=Number(row.fixture?.id),tid=Number(row.team?.id);if(!fid||!tid)continue;const key=`${fid}:${tid}`;if(!map.has(key))map.set(key,[]);map.get(key).push({playerId:row.player?.id||null,name:row.player?.name||null,type:row.player?.type||null,reason:row.player?.reason||null})}return map}
function lineup(f,teamId){const row=(f.lineups||[]).find(x=>Number(x.team?.id)===Number(teamId));if(!row)return null;const starters=(row.startXI||[]).map(x=>({id:x.player?.id||null,name:x.player?.name||null,number:x.player?.number||null,pos:x.player?.pos||null,grid:x.player?.grid||null}));const bench=(row.substitutes||[]).map(x=>({id:x.player?.id||null,name:x.player?.name||null,number:x.player?.number||null,pos:x.player?.pos||null}));return {confirmed:starters.length>=11,formation:row.formation||null,coach:row.coach?.name||null,starters,bench}}
function availability(f,index){const fid=Number(f.fixture?.id),homeId=Number(f.teams?.home?.id),awayId=Number(f.teams?.away?.id),h=lineup(f,homeId),a=lineup(f,awayId),ha=index.get(`${fid}:${homeId}`)||[],aa=index.get(`${fid}:${awayId}`)||[],confirmed=Boolean(h?.confirmed&&a?.confirmed);return {fixtureId:fid,lineupsConfirmed:confirmed,lineupStatus:confirmed?'CONFIRMED':'PENDING_OR_UNAVAILABLE',home:{teamId:homeId,teamName:f.teams?.home?.name||null,formation:h?.formation||null,coach:h?.coach||null,starters:h?.starters||[],bench:h?.bench||[],absences:ha,absenceCount:ha.length},away:{teamId:awayId,teamName:f.teams?.away?.name||null,formation:a?.formation||null,coach:a?.coach||null,starters:a?.starters||[],bench:a?.bench||[],absences:aa,absenceCount:aa.length},policy:'Availability can downgrade confidence. Confirmed lineups are required at the final pre-kickoff gate; availability alone cannot create PRIME.'}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=45, stale-while-revalidate=30');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});try{const ids=String(req.query?.ids||'').split(/[,-]/).map(Number).filter(Boolean).slice(0,120);if(!ids.length)return res.status(200).json({availability:{},meta:{requested:0,loaded:0,providerCalls:0}});const date=String(req.query?.date||today()),guard=storageReady()?await readJson(QUOTA_GUARD_PATH,null):null,q=seedQuota(guard),providerAllowed=!(guardCurrent(guard)&&(guard?.exhausted||guard?.mode==='HALT'))&&!quotaBlocked(q),[fixtureResult,injuryResult]=await Promise.all([fixtures(ids,q,providerAllowed),injuries(date,q,providerAllowed)]);await persistQuota(q,guard);const index=injuryIndex(injuryResult.rows),map={};for(const f of fixtureResult.rows){const a=availability(f,index);map[String(a.fixtureId)]=a}return res.status(200).json({availability:map,meta:{date,requested:ids.length,loaded:fixtureResult.rows.length,lineupsConfirmed:Object.values(map).filter(x=>x.lineupsConfirmed).length,injuryRows:injuryResult.rows.length,injuryCache:injuryResult.cache,fixtureCache:fixtureResult.cache,fixtureTtlMinutes:FIXTURE_TTL/60000,injuryTtlMinutes:INJURY_TTL/60000,providerCalls:q.providerCalls,providerBlocked:!providerAllowed||quotaBlocked(q),quota:{dailyLimit:q.dailyLimit,dailyRemaining:q.dailyRemaining,minuteRemaining:q.minuteRemaining,reserve:reserve(q.dailyLimit),observedAt:q.observedAt},quotaGuardRespected:true}})}catch(error){return res.status(503).json({error:error.message,availability:{}})}}
