const MAX_SIDE_ADJ=.025;
const SOURCE_ROLLOUT_SCALE=.50;
const SOURCE_MIN_SAMPLE=100;
const SOURCE_MIN_TOTAL=600;
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function clamp(v,lo=-MAX_SIDE_ADJ,hi=MAX_SIDE_ADJ){return Math.max(lo,Math.min(hi,v))}
function profileOk(p){return p&&Number(p.sample)>=20&&p.status!=='UNVALIDATED'&&p.governedAdjustment}
function sourceProfileOk(p){return p&&Number(p.sample)>=SOURCE_MIN_SAMPLE&&p.status==='VALIDATED'&&Number.isFinite(Number(p.governedAdjustment))}
function phaseKey(m){return m?.isLive?'LIVE':'PREMATCH'}
function classKey(m){return m?.classification||m?.prediction?.classification||null}
function rawProbabilitySource(m){const chain=[m?.rawPreMatchModel,m?.preTacticalModel,m?.preMatchupModel,m?.preCompetitionModel,m?.preContextModel,m?.preMatchModel];for(const x of chain){const s=String(x?.source||'').toUpperCase();if(s)return s}return''}
function shadowSourceKey(m){const raw=rawProbabilitySource(m);if(raw.includes('API-FOOTBALL-PREDICTIONS'))return'ARGUS_PREMATCH_1X2';return null}
function combine(m,cal){const sources=[];const league=cal?.league?.[m.competition||'UNKNOWN'];const phase=cal?.phase?.[phaseKey(m)];const cls=classKey(m)?cal?.classification?.[classKey(m)]:null;if(profileOk(league))sources.push({name:'league',weight:.55,p:league});if(profileOk(phase))sources.push({name:'phase',weight:.20,p:phase});if(profileOk(cls))sources.push({name:'classification',weight:.25,p:cls});if(!sources.length)return{delta:{home:0,draw:0,away:0},sources:[],confidence:'NONE'};const total=sources.reduce((s,x)=>s+x.weight,0);const delta={home:0,draw:0,away:0};for(const s of sources)for(const k of ['home','draw','away'])delta[k]+=n(s.p.governedAdjustment?.[k])*s.weight/total;for(const k of Object.keys(delta))delta[k]=clamp(delta[k]);const minSample=Math.min(...sources.map(s=>Number(s.p.sample)||0));return{delta,sources:sources.map(s=>({name:s.name,sample:s.p.sample,status:s.p.status,brier:s.p.brier,weight:Number((s.weight/total).toFixed(3))})),confidence:minSample>=50?'HIGH':'MEDIUM'}}
function sourceDelta(m,probCal){
 if(m?.isLive||!probCal||Number(probCal?.settled)<SOURCE_MIN_TOTAL)return{delta:{home:0,draw:0,away:0},sources:[],confidence:'NONE',sourceKey:null,reason:'INSUFFICIENT_TOTAL_SOURCE_EVIDENCE'};
 const sourceKey=shadowSourceKey(m);if(!sourceKey)return{delta:{home:0,draw:0,away:0},sources:[],confidence:'NONE',sourceKey:null,reason:'UNSUPPORTED_MODEL_SOURCE'};
 if(!probCal?.sourceMarket||typeof probCal.sourceMarket!=='object')return{delta:{home:0,draw:0,away:0},sources:[],confidence:'NONE',sourceKey,reason:'SOURCE_SEGMENTED_CALIBRATION_UNAVAILABLE'};
 const map={home:'HOME',draw:'DRAW',away:'AWAY'},delta={home:0,draw:0,away:0},sources=[];
 for(const[k,mk]of Object.entries(map)){const p=probCal.sourceMarket?.[`${sourceKey}|||${mk}`];if(!sourceProfileOk(p))continue;const applied=clamp(Number(p.governedAdjustment)*SOURCE_ROLLOUT_SCALE);delta[k]=applied;sources.push({name:`source:${sourceKey}:${mk}`,sourceKey,market:mk,sample:Number(p.sample),status:p.status,brier:p.brier,direction:p.direction,averagePredicted:p.averagePredicted,observedRate:p.observedRate,calibrationGapPct:p.calibrationGapPct,rawGovernedAdjustment:Number(p.governedAdjustment),rolloutScale:SOURCE_ROLLOUT_SCALE,appliedAdjustment:Number(applied.toFixed(4))})}
 return{delta,sources,confidence:sources.length===3?'HIGH':sources.length?'MEDIUM':'NONE',sourceKey,reason:sources.length===3?'SOURCE_PROFILES_VALIDATED':'SOURCE_PROFILES_INCOMPLETE'};
}
function merge(base,source){const delta={home:clamp(n(base?.delta?.home)+n(source?.delta?.home)),draw:clamp(n(base?.delta?.draw)+n(source?.delta?.draw)),away:clamp(n(base?.delta?.away)+n(source?.delta?.away))},sources=[...(base?.sources||[]),...(source?.sources||[])];const confidence=base?.confidence==='HIGH'||source?.confidence==='HIGH'?'HIGH':sources.length?'MEDIUM':'NONE';return{delta,sources,confidence}}
function adjust(model,d){if(!model)return null;let h=n(model.home),x=n(model.draw),a=n(model.away);if(!(h>0&&x>0&&a>0))return null;h=Math.max(.01,h+d.home);x=Math.max(.01,x+d.draw);a=Math.max(.01,a+d.away);const s=h+x+a;return{home:Number((h/s).toFixed(4)),draw:Number((x/s).toFixed(4)),away:Number((a/s).toFixed(4)),source:'ARGUS-CALIBRATION-IMPACT'}}
async function probabilityCalibration(req){try{const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],host=String(req.headers['x-forwarded-host']||req.headers.host||'argus-omni-live.vercel.app').split(',')[0].trim(),r=await fetch(`${proto}://${host}/api/probability-calibration`,{headers:{Accept:'application/json'}});if(!r.ok)return null;return await r.json()}catch(_){return null}}
export default async function handler(req,res){
 res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 const matches=Array.isArray(req.body?.matches)?req.body.matches:[],cal=req.body?.calibration||{},probCal=await probabilityCalibration(req),impact={};
 for(const m of matches.filter(x=>!x.isFinished)){
  const segment=combine(m,cal),source=sourceDelta(m,probCal),c=merge(segment,source);
  impact[String(m.id)]={fixtureId:m.id,confidence:c.confidence,sources:c.sources,probabilityDelta:{home:Number((c.delta.home*100).toFixed(2)),draw:Number((c.delta.draw*100).toFixed(2)),away:Number((c.delta.away*100).toFixed(2))},adjustedModel:c.sources.length?adjust(m.preMatchModel,c.delta):null,sourceCalibration:{eligible:source.sources.length===3,reason:source.reason,rawProbabilitySource:rawProbabilitySource(m)||null,shadowSourceKey:source.sourceKey||null,settledEvidence:probCal?.settled||0,rolloutScale:SOURCE_ROLLOUT_SCALE,minimumTotalEvidence:SOURCE_MIN_TOTAL,minimumMarketSample:SOURCE_MIN_SAMPLE,profiles:source.sources},governance:{minimumSample:20,validatedSample:50,maxAbsoluteSideAdjustmentPct:MAX_SIDE_ADJ*100,sourceCalibrationRequiresValidatedSample:SOURCE_MIN_SAMPLE,sourceCalibrationRequiresTotalEvidence:SOURCE_MIN_TOTAL,sourceCalibrationRolloutScale:SOURCE_ROLLOUT_SCALE,sourceSegmentedEvidenceRequired:true,mayBypassGate:false,primeRequiresNormalDownstreamGates:true,unvalidatedSegmentsIgnored:true}}
 }
 return res.status(200).json({ok:true,version:'CALIBRATION-IMPACT-3-SOURCE-SEGMENTED-OOS',fixtures:Object.keys(impact).length,applied:Object.values(impact).filter(x=>x.adjustedModel).length,sourceCalibrationApplied:Object.values(impact).filter(x=>x.sourceCalibration?.eligible).length,probabilityCalibration:{available:Boolean(probCal),settled:probCal?.settled||0,version:probCal?.version||null,sourceSegmented:Boolean(probCal?.sourceMarket)},impact})
}
