import { readJson, writeJson, storageReady } from './_report-store.js';

const ROOT='argus/competition-context';
const MIN_SAMPLE=20,HIGH_SAMPLE=60,MAX_ADJ=.035;
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function key(m){return String(m?.competition||'UNKNOWN').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'-').slice(0,80)}
function outcome(m){const h=n(m?.score?.home),a=n(m?.score?.away);return h>a?'home':h<a?'away':'draw'}
function probs(m){const p=m?.rawPreMatchModel||m?.preMatchModel;if(!p)return null;const h=n(p.home),d=n(p.draw),a=n(p.away);return h>0&&d>0&&a>0?{home:h,draw:d,away:a}:null}
function brier(p,y){return ((p.home-(y==='home'))**2+(p.draw-(y==='draw'))**2+(p.away-(y==='away'))**2)/3}
function summarize(rows=[]){const sample=rows.length;if(!sample)return{sample:0,confidence:'NONE'};let home=0,draw=0,away=0,goals=0,bs=0,bc=0;for(const r of rows){if(r.outcome==='home')home++;else if(r.outcome==='draw')draw++;else away++;goals+=n(r.goals);if(Number.isFinite(r.brier)){bs+=r.brier;bc++}}return{sample,homeRate:home/sample,drawRate:draw/sample,awayRate:away/sample,goalsPerMatch:goals/sample,brier:bc?bs/bc:null,confidence:sample>=HIGH_SAMPLE?'HIGH':sample>=MIN_SAMPLE?'MEDIUM':'LOW'}}
function delta(profile){if(!profile||profile.sample<MIN_SAMPLE)return{home:0,draw:0,away:0};const trust=profile.sample>=HIGH_SAMPLE?.65:.35;return{home:Math.max(-MAX_ADJ,Math.min(MAX_ADJ,(profile.homeRate-.44)*.12*trust)),draw:Math.max(-MAX_ADJ,Math.min(MAX_ADJ,(profile.drawRate-.27)*.10*trust)),away:Math.max(-MAX_ADJ,Math.min(MAX_ADJ,(profile.awayRate-.29)*.12*trust))}}
function adjust(model,d){if(!model)return null;let h=n(model.home),x=n(model.draw),a=n(model.away);if(!(h>0&&x>0&&a>0))return null;h=Math.max(.01,h*(1+d.home));x=Math.max(.01,x*(1+d.draw));a=Math.max(.01,a*(1+d.away));const s=h+x+a;return{home:+(h/s).toFixed(4),draw:+(x/s).toFixed(4),away:+(a/s).toFixed(4),source:'ARGUS-COMPETITION-CONTEXT'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(200).json({ok:true,fixtures:0,impact:{},storage:false});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],doc=await readJson(`${ROOT}/memory.json`,{competitions:{}});doc.competitions||={};let learned=0;for(const m of matches.filter(x=>x.isFinished)){const k=key(m),rows=Array.isArray(doc.competitions[k])?doc.competitions[k]:[],id=Number(m.id);if(!id||rows.some(r=>Number(r.fixtureId)===id))continue;const p=probs(m),y=outcome(m);rows.push({fixtureId:id,date:m.kickoff||null,outcome:y,goals:n(m.score?.home)+n(m.score?.away),brier:p?brier(p,y):null});doc.competitions[k]=rows.slice(-300);learned++}if(learned){doc.updatedAt=new Date().toISOString();await writeJson(`${ROOT}/memory.json`,doc)}const impact={};for(const m of matches.filter(x=>!x.isFinished)){const profile=summarize(doc.competitions[key(m)]||[]),d=delta(profile),adjustedModel=adjust(m.preMatchModel,d);impact[String(m.id)]={competition:m.competition||null,profile,probabilityDelta:{home:+(d.home*100).toFixed(2),draw:+(d.draw*100).toFixed(2),away:+(d.away*100).toFixed(2)},adjustedModel,governance:{minimumSample:MIN_SAMPLE,highConfidenceSample:HIGH_SAMPLE,maxAbsoluteAdjustmentPct:MAX_ADJ*100,mayCreatePrime:false,mayDowngrade:true}}}return res.status(200).json({ok:true,version:'COMPETITION-CONTEXT-1',learned,fixtures:Object.keys(impact).length,impact})}
