import { readJson, writeJson, storageReady } from './_report-store.js';

const PLAN_PATH='argus/autopilot/decision-plan.json';
const TREND_PATH='argus/research/streak-intelligence.json';
const slipPath=date=>`argus/daily-slip/${date}.json`;
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function brusselsDate(d=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Brussels',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function active(row,date){if(!row||row.isLive||['FT','AET','PEN','CANC','ABD','AWD','WO'].includes(row.status))return false;const k=new Date(row.kickoff||0);if(!Number.isFinite(k.getTime()))return false;return brusselsDate(k)===date}
function pickLabel(r){const s=String(r.stakeSelection||r.eligibilityCandidate?.side||'').toUpperCase();if(s==='HOME')return `${r.home} win`;if(s==='AWAY')return `${r.away} win`;if(s==='DRAW')return 'Draw';return s||'Selection unavailable'}
function normalized(r){const odds=n(r.stakeOdds||r.eligibilityCandidate?.odds,null),confidence=n(r.netConfidence,null),score=n(r.portfolioRankScore,r.score||0);return{fixtureId:r.fixtureId,competition:r.competition,home:r.home,away:r.away,kickoff:r.kickoff,verdict:r.finalVerdict,selection:pickLabel(r),selectionKey:String(r.stakeSelection||r.eligibilityCandidate?.side||'').toUpperCase(),odds:odds&&odds>1?odds:null,confidence,rankScore:score,recommendedStakePct:n(r.recommendedStakePct,0),positive:r.eligibilityPositive||[],risks:[...(r.eligibilityIssues||[]),...(r.portfolioReasons||[])],marketRegime:r.marketRegime||null,lineupsConfirmed:Boolean(r.lineupsConfirmed),preKickoffGate:r.preKickoffGate||null,context:r.matchContext||r.competitionContext||null}}
function score(r){let s=n(r.rankScore,0)+n(r.confidence,0)*.35;if(r.verdict==='PRIME')s+=30;else if(r.verdict==='VALUE')s+=14;if(r.lineupsConfirmed)s+=5;if(r.preKickoffGate==='PASSED')s+=4;if((r.marketRegime?.regime||r.marketRegime)==='VOLATILE'||(r.marketRegime?.regime||r.marketRegime)==='STALE')s-=12;s-=Math.min(15,(r.risks||[]).length*3);return s}
function correlationReason(a,b){if(a.fixtureId===b.fixtureId)return 'same fixture';const teamsA=new Set([a.home,a.away].filter(Boolean)),teamsB=[b.home,b.away].filter(Boolean);if(teamsB.some(t=>teamsA.has(t)))return 'same team exposure';if(a.competition&&b.competition&&a.competition===b.competition&&Math.abs(new Date(a.kickoff)-new Date(b.kickoff))<3*3600000)return 'same league/time cluster';return null}
function diversify(rows,max){const out=[],rejected=[];for(const r of rows){let reason=null;for(const x of out){reason=correlationReason(r,x);if(reason)break}if(reason){rejected.push({fixtureId:r.fixtureId,selection:r.selection,reason});continue}out.push(r);if(out.length>=max)break}return{rows:out,rejected}}
function combinedOdds(rows){const xs=rows.map(x=>n(x.odds,null)).filter(x=>x&&x>1);return xs.length===rows.length&&xs.length?Number(xs.reduce((a,b)=>a*b,1).toFixed(2)):null}
function rationale(r){const why=[];if(r.verdict==='PRIME')why.push('PRIME validated');else why.push('VALUE eligible');if(r.confidence!=null)why.push(`${r.confidence}% confidence`);if(r.lineupsConfirmed)why.push('lineups confirmed');if(r.preKickoffGate==='PASSED')why.push('pre-kickoff gate passed');if(r.positive?.length)why.push(String(r.positive[0]));return why.slice(0,4).join(' · ')}
function buildSlip(name,result){const rows=result.rows,odds=combinedOdds(rows),avgConf=rows.length?Number((rows.reduce((s,x)=>s+n(x.confidence,0),0)/rows.length).toFixed(1)):null;return{name,available:rows.length>0,legs:rows.map(x=>({...x,why:rationale(x)})),combinedOdds:odds,averageConfidence:avgConf,estimatedStakePct:rows.length?Number(Math.min(...rows.map(x=>n(x.recommendedStakePct,0))).toFixed(2)):0,correlationGuard:{active:true,rejected:result.rejected},warning:rows.length?'Selections passed ARGUS eligibility and correlation guards. They can still change as odds, lineups or governance gates change.':'No sufficiently strong low-correlation selections right now.'}}
function trendEligible(t,date){return Boolean(t&&t.perfect10===true&&t.playsToday===true&&t.completeWindow===true&&t.verifiedCalendarContinuity===true&&Number(t.recentSample)===10&&Number(t.recentHits)===10&&Number(t.recentHitRate)===100&&Number(t.dataCoveragePct)===100&&t.todayMatch&&brusselsDate(new Date(t.todayMatch.kickoff||0))===date)}
function trendRow(t){return{team:t.team,condition:t.condition,label:t.label,family:t.family,currentStreak:t.currentStreak,recentHits:t.recentHits,recentSample:t.recentSample,recentHitRate:t.recentHitRate,dataCoveragePct:t.dataCoveragePct,fixtureId:t.todayMatch?.fixtureId||null,opponent:t.todayMatch?.opponent||null,kickoff:t.todayMatch?.kickoff||null,isLive:Boolean(t.todayMatch?.isLive),minute:t.todayMatch?.minute??null,source:t.source,signal:'10/10 PERFECT TREND',why:'Same condition occurred in all 10 of the team’s 10 most recent consecutive matches, with verified continuity and 100% data coverage.'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Daily slip storage unavailable'});const date=String(req.query?.date||brusselsDate()),plan=await readJson(PLAN_PATH,{generatedAt:null,plan:[]}),trends=await readJson(TREND_PATH,{generatedAt:null,trends:[]}),rows=(plan.plan||[]).filter(r=>active(r,date)&&r.betEligible&&['PRIME','VALUE'].includes(r.finalVerdict)).map(normalized).filter(r=>r.odds&&r.confidence!=null).sort((a,b)=>score(b)-score(a));const safe=diversify(rows.filter(r=>r.verdict==='PRIME'||r.confidence>=72),2),balanced=diversify(rows.filter(r=>r.confidence>=64),3),aggressive=diversify(rows.filter(r=>r.confidence>=58),4),bestSingle=rows[0]?{...rows[0],why:rationale(rows[0])}:null;const trend10=(trends.trends||[]).filter(t=>trendEligible(t,date)).map(trendRow).sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff)||a.team.localeCompare(b.team)||a.label.localeCompare(b.label));const payload={version:'DAILY-SLIP-3',date,generatedAt:new Date().toISOString(),sourceGeneratedAt:plan.generatedAt||null,trendSourceGeneratedAt:trends.generatedAt||null,status:rows.length||trend10.length?'READY':'WAIT',bestSingle,slips:{safe:buildSlip('SAFE',safe),balanced:buildSlip('BALANCED',balanced),aggressive:buildSlip('AGGRESSIVE',aggressive)},trend10:{available:trend10.length>0,count:trend10.length,signals:trend10,policy:{strictLatestTen:true,exactWindow:'10/10',playsTodayRequired:true,perfect10Required:true,coverageRequiredPct:100,calendarContinuityRequired:true,noGapFilling:true,noOlderSubstitutes:true,informationalOnly:true,noPrimeCreation:true,automaticBetPlacement:false},warning:trend10.length?'These are perfect recent streaks, not guarantees. They are shown separately from PRIME/VALUE and do not become bets automatically.':'No team playing today currently has a verified 10/10 perfect trend.'},eligibleCount:rows.length,policy:{source:'Decision Scheduler only for betting slips; Streak Intelligence only for separate Trend 10/10 section',allowedVerdicts:['PRIME','VALUE'],watchExcluded:true,noBetExcluded:true,correlationGuard:true,automaticBetPlacement:false,rule:'Never fill a betting slip with weak or materially correlated selections. Trend 10/10 is informational and must remain separate from PRIME/VALUE.'}};await writeJson(slipPath(date),payload);return res.status(200).json(payload)}