import { readJson, listJson, readManyJson, storageReady, writeJson } from './_report-store.js';

const API_BASE='https://v3.football.api-sports.io';
const TZ='Europe/Brussels';
const QUOTA_GUARD_PATH='argus/data/api-football-quota-guard.json';
const FINAL_STATUSES=new Set(['FT','AET','PEN']);
const VOID_STATUSES=new Set(['CANC','ABD','AWD','WO']);

function dateInBrussels(value=new Date()) {
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value);
  const m=Object.fromEntries(parts.map(p=>[p.type,p.value]));
  return `${m.year}-${m.month}-${m.day}`;
}
function validSelection(v){ return ['HOME','DRAW','AWAY'].includes(String(v||'').toUpperCase()); }
function isActionableClass(c){ const x=String(c||'').toUpperCase(); return x.includes('PRIME') || x.includes('VALUE'); }
function pickSnapshot(fixture){const snaps=Array.isArray(fixture?.snapshots)?fixture.snapshots:[];const kickoff=fixture?.kickoff?new Date(fixture.kickoff).getTime():Infinity;const prematch=snaps.filter(s=>s.phase==='PREMATCH'&&new Date(s.recordedAt).getTime()<=kickoff&&validSelection(s.selection));if(prematch.length)return prematch[prematch.length-1];const live=snaps.filter(s=>s.phase==='LIVE'&&validSelection(s.selection));return live.length?live[live.length-1]:null}
function resultFromStored(stored){const snaps=Array.isArray(stored?.snapshots)?stored.snapshots:[];const final=snaps.slice().reverse().find(s=>FINAL_STATUSES.has(s.status)||VOID_STATUSES.has(s.status));if(!final)return{state:'PENDING'};if(VOID_STATUSES.has(final.status))return{state:'VOID'};const h=Number(final.score?.home),a=Number(final.score?.away);if(!Number.isFinite(h)||!Number.isFinite(a))return{state:'PENDING'};return{state:'FINAL',winner:h>a?'HOME':h<a?'AWAY':'DRAW',home:h,away:a}}
function outcomeFromFixture(row){const status=row?.fixture?.status?.short;if(VOID_STATUSES.has(status))return{state:'VOID'};if(!FINAL_STATUSES.has(status))return{state:'PENDING'};const h=row?.score?.fulltime?.home??row?.goals?.home,a=row?.score?.fulltime?.away??row?.goals?.away;if(!Number.isFinite(Number(h))||!Number.isFinite(Number(a)))return{state:'PENDING'};return{state:'FINAL',winner:Number(h)>Number(a)?'HOME':Number(h)<Number(a)?'AWAY':'DRAW',home:Number(h),away:Number(a)}}
function settle(snapshot,result){if(!snapshot||!validSelection(snapshot.selection))return{outcome:'NO PREDICTION',pl:null};if(result.state==='VOID')return{outcome:'VOID',pl:0};if(result.state!=='FINAL')return{outcome:'PENDING',pl:null};const win=String(snapshot.selection).toUpperCase()===result.winner,odds=Number(snapshot.odds);return{outcome:win?'WIN':'LOSS',pl:win&&odds>1?Number((odds-1).toFixed(2)):-1}}
async function fetchFixtures(date){const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error('API_FOOTBALL_KEY is not configured');const r=await fetch(`${API_BASE}/fixtures?date=${date}&timezone=${encodeURIComponent(TZ)}`,{headers:{'x-apisports-key':key,Accept:'application/json'}});if(!r.ok)throw new Error(`API-Football HTTP ${r.status}`);const data=await r.json();if(data?.errors&&Object.keys(data.errors).length)throw new Error(`API-Football: ${JSON.stringify(data.errors)}`);return data.response||[]}
function buildSummary(rows){const predicted=rows.filter(r=>r.prediction).length,settled=rows.filter(r=>['WIN','LOSS'].includes(r.outcome)).length,wins=rows.filter(r=>r.outcome==='WIN').length,losses=rows.filter(r=>r.outcome==='LOSS').length,voids=rows.filter(r=>r.outcome==='VOID').length,pending=rows.filter(r=>r.outcome==='PENDING').length,actionable=rows.filter(r=>r.prediction&&isActionableClass(r.prediction.classification)),actionableSettled=actionable.filter(r=>['WIN','LOSS'].includes(r.outcome)),actionableWins=actionableSettled.filter(r=>r.outcome==='WIN').length,actionablePL=actionable.reduce((s,r)=>s+(Number.isFinite(Number(r.pl))?Number(r.pl):0),0);return{matches:rows.length,predicted,settled,wins,losses,voids,pending,hitRate:settled?Number((wins/settled*100).toFixed(1)):null,actionableBets:actionable.length,actionableSettled:actionableSettled.length,actionableWins,actionableLosses:actionableSettled.length-actionableWins,actionableHitRate:actionableSettled.length?Number((actionableWins/actionableSettled.length*100).toFixed(1)):null,flatStakePL:Number(actionablePL.toFixed(2)),roi:actionableSettled.length?Number((actionablePL/actionableSettled.length*100).toFixed(1)):null}}
async function listReports(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');if(!storageReady())return res.status(200).json({storageReady:false,reports:[]});const limit=Math.max(1,Math.min(120,Number(req.query?.limit)||30));const blobs=await listJson('argus/reports/',limit),reports=await readManyJson(blobs);reports.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));return res.status(200).json({storageReady:true,reports})}

export default async function handler(req,res){
  if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});
  if(String(req.query?.mode||'').toLowerCase()==='list')return listReports(req,res);
  res.setHeader('Cache-Control','no-store');
  if(!storageReady())return res.status(503).json({error:'Prediction archive storage is not configured'});
  const secret=process.env.REPORT_CRON_SECRET;if(secret&&req.headers.authorization!==`Bearer ${secret}`)return res.status(401).json({error:'Unauthorized'});
  const date=String(req.query?.date||dateInBrussels()),existing=await readJson(`argus/reports/${date}.json`,null);if(existing&&req.query?.force!=='1')return res.status(200).json({...existing,idempotent:true});
  const predictionStore=await readJson(`argus/predictions/${date}.json`,{date,fixtures:{}}),guard=await readJson(QUOTA_GUARD_PATH,null),providerBlocked=Boolean(guard?.date===date&&guard?.exhausted);let fixtures=[],fixtureSource=providerBlocked?'ARCHIVE_ONLY_QUOTA_GUARD':'ARCHIVE_ONLY',providerError=providerBlocked?'PROVIDER_BLOCKED_BY_QUOTA_GUARD':null;if(!providerBlocked)try{fixtures=await fetchFixtures(date);fixtureSource='API_FOOTBALL'}catch(error){providerError=error.message}
  const byId=new Map(fixtures.map(f=>[String(f.fixture?.id),f])),ids=new Set([...byId.keys(),...Object.keys(predictionStore.fixtures||{})]),rows=[];
  for(const id of ids){const fixture=byId.get(id),stored=predictionStore.fixtures?.[id]||null,prediction=pickSnapshot(stored),result=fixture?outcomeFromFixture(fixture):resultFromStored(stored),settlement=settle(prediction,result);rows.push({fixtureId:Number(id),competition:fixture?.league?.name||stored?.competition||null,country:fixture?.league?.country||stored?.country||null,home:fixture?.teams?.home?.name||stored?.home||null,away:fixture?.teams?.away?.name||stored?.away||null,kickoff:fixture?.fixture?.date||stored?.kickoff||null,finalStatus:fixture?.fixture?.status?.short||null,finalScore:result.state==='FINAL'?{home:result.home,away:result.away}:null,prediction,snapshotCount:stored?.snapshots?.length||0,outcome:settlement.outcome,pl:settlement.pl})}
  rows.sort((a,b)=>new Date(a.kickoff||0)-new Date(b.kickoff||0));const report={date,timezone:TZ,generatedAt:new Date().toISOString(),fixtureSource,providerBlocked,providerError,integrity:'NO HINDSIGHT — report evaluates snapshots stored before settlement.',methodology:'Final pre-match snapshot is evaluated first; if absent, latest live snapshot is used. If provider data is unavailable or quota-guarded, unresolved outcomes remain PENDING.',summary:buildSummary(rows),matches:rows};await writeJson(`argus/reports/${date}.json`,report);return res.status(200).json(report)
}