import { readJson, storageReady } from './_report-store.js';

const PLAN='argus/autopilot/decision-plan.json';
const LEDGER='argus/ledger';
const SURVIVING='argus/research/surviving-edge.json';
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const up=v=>String(v||'').toUpperCase();
function dateTZ(v=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Brussels',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(v).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function activeToday(r,today){if(!r||r.isLive||['FT','AET','PEN','CANC','ABD','AWD','WO'].includes(r.status))return false;const d=new Date(r.kickoff||0);return Number.isFinite(d.getTime())&&dateTZ(d)===today}
async function recentSettled(){const days=[];for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()-i);days.push(dateTZ(d))}const rows=[];for(const day of days){const j=await readJson(`${LEDGER}/${day}.json`,null);for(const r of j?.records||[]){if(['WIN','LOSS','VOID'].includes(up(r.settlement?.status||r.status)))rows.push({...r,_day:day})}}return rows.sort((a,b)=>new Date(b.settlement?.settledAt||b.updatedAt||b.createdAt||0)-new Date(a.settlement?.settledAt||a.updatedAt||a.createdAt||0)).slice(0,20)}
function losingRun(rows){let c=0;for(const r of rows){const s=up(r.settlement?.status||r.status);if(s==='LOSS')c++;else if(s==='WIN')break}return c}
function duplicateExposure(rows){const counts=new Map();for(const r of rows){for(const t of [r.home,r.away].filter(Boolean)){counts.set(t,(counts.get(t)||0)+1)}}return [...counts.entries()].filter(([,v])=>v>1).map(([team,count])=>({team,count}))}
function assess(row,survivor,global){const reasons=[],protective=[];let risk=0;if(row.finalVerdict!=='PRIME'){risk+=22;reasons.push('Not PRIME')}else protective.push('PRIME eligible');if(!row.betEligible){risk+=35;reasons.push('Eligibility failed')}if(n(row.netConfidence,0)<68){risk+=14;reasons.push('Confidence below 68%')}else protective.push(`Confidence ${n(row.netConfidence).toFixed(0)}%`);if(n(row.eligibilityCandidate?.edgePct??row.eligibilityCandidate?.edge,0)<4){risk+=12;reasons.push('Edge below 4%')}else protective.push('Edge above 4%');if(['VOLATILE','STALE','WIDE'].includes(up(row.marketRegime?.regime||row.marketRegime))){risk+=18;reasons.push('Adverse market regime')}if(row.portfolioBlocked){risk+=30;reasons.push('Portfolio block')}if(['DEGRADED','CAUTION'].includes(up(row.learningStatus))){risk+=15;reasons.push(`Learning ${up(row.learningStatus)}`)}if(n(row.matchContext?.regime?.riskScore,0)>=55){risk+=14;reasons.push('Context risk elevated')}if(!survivor||survivor.status!=='SURVIVING_EDGE'){risk+=12;reasons.push('No Surviving Edge confirmation')}else protective.push(`Surviving Edge ${survivor.survivalScore}/100`);if(global.losingRun>=3){risk+=18;reasons.push(`Model has ${global.losingRun} recent settled losses in a row`)}if(global.todayPrimeCount>=4){risk+=10;reasons.push('Too many simultaneous PRIME candidates')}risk=Math.min(100,risk);let status='CLEAR';if(risk>=60)status='STOP';else if(risk>=35)status='COOL_DOWN';else if(risk>=20)status='REVIEW';return{fixtureId:row.fixtureId,home:row.home,away:row.away,kickoff:row.kickoff,selection:up(row.stakeSelection||row.eligibilityCandidate?.side),status,riskScore:risk,reasons,protective,automaticWagering:false}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Storage unavailable'});const today=String(req.query?.date||dateTZ()),plan=await readJson(PLAN,{generatedAt:null,plan:[]}),surv=await readJson(SURVIVING,{survivors:[],near:[]}),settled=await recentSettled(),lr=losingRun(settled),active=(plan.plan||[]).filter(r=>activeToday(r,today)),sm=new Map([...(surv.survivors||[]),...(surv.near||[])].map(x=>[String(x.fixtureId),x])),global={losingRun:lr,todayPrimeCount:active.filter(x=>x.finalVerdict==='PRIME'&&x.betEligible).length};const decisions=active.map(r=>assess(r,sm.get(String(r.fixtureId)),global)).sort((a,b)=>b.riskScore-a.riskScore),dupes=duplicateExposure(active.filter(x=>x.betEligible&&['PRIME','VALUE'].includes(x.finalVerdict)));const overall=decisions.some(x=>x.status==='STOP')?'STOP':lr>=3?'COOL_DOWN':decisions.some(x=>x.status==='COOL_DOWN')?'COOL_DOWN':'CLEAR';return res.status(200).json({version:'DECISION-SHIELD-1',generatedAt:new Date().toISOString(),date:today,overall,summary:{matchesReviewed:decisions.length,stop:decisions.filter(x=>x.status==='STOP').length,coolDown:decisions.filter(x=>x.status==='COOL_DOWN').length,review:decisions.filter(x=>x.status==='REVIEW').length,clear:decisions.filter(x=>x.status==='CLEAR').length,recentOfficialLosingRun:lr,duplicateTeamExposure:dupes},decisions,policy:{purpose:'Reduce avoidable human and model decision errors before any wager is considered.',recentOfficialResultsAreModelRecordsNotUserProfit:true,noChasingLosses:true,noMartingale:true,noStakeEscalation:true,noGuarantee:true,automaticWagering:false,rule:'When evidence conflicts or recent error risk rises, ARGUS should prefer STOP or COOL DOWN over forcing action.'}})}