import { readJson, writeJson, storageReady } from './_report-store.js';

const STATE_PATH='argus/autopilot/live-event-state.json';
const LOG_PATH='argus/autopilot/live-event-log.json';
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function pressure(m={}){const s=m.stats||{};const shot=n(s.shotsHome)-n(s.shotsAway),sot=n(s.shotsOnTargetHome)-n(s.shotsOnTargetAway),corn=n(s.cornersHome)-n(s.cornersAway),danger=n(s.dangerousAttacksHome)-n(s.dangerousAttacksAway),poss=n(s.possessionHome,50)-50;return Math.round(clamp(50+shot*2.4+sot*5.2+corn*1.8+danger*.55+poss*.6,0,100))}
function odds(m={}){const x=m.markets||{};return {home:n(x.home,null),draw:n(x.draw,null),away:n(x.away,null)}}
function maxOddsMove(a={},b={}){let best={side:null,pct:0,from:null,to:null};for(const k of ['home','draw','away']){const x=n(a[k],null),y=n(b[k],null);if(!x||!y||x<=1||y<=1)continue;const pct=Math.abs((y/x-1)*100);if(pct>best.pct)best={side:k,pct,from:x,to:y}}return best}
function redCards(m={}){const s=m.stats||{};return {home:n(s.redCardsHome??m.redCards?.home??m.cards?.redHome,0),away:n(s.redCardsAway??m.redCards?.away??m.cards?.redAway,0)}}
function snapshot(m){return {fixtureId:m.id,home:m.home,away:m.away,competition:m.competition,kickoff:m.kickoff,status:m.status,isLive:Boolean(m.isLive),minute:n(m.minute,null),score:{home:n(m.score?.home,0),away:n(m.score?.away,0)},pressure:pressure(m),odds:odds(m),redCards:redCards(m),recordedAt:new Date().toISOString()}}
function diff(prev,cur){if(!prev)return[];const events=[];const ts=new Date().toISOString();const base={fixtureId:cur.fixtureId,home:cur.home,away:cur.away,competition:cur.competition,minute:cur.minute,recordedAt:ts};if(cur.score.home!==prev.score?.home||cur.score.away!==prev.score?.away)events.push({...base,type:'GOAL_OR_SCORE_CHANGE',severity:'CRITICAL',from:`${prev.score?.home??0}-${prev.score?.away??0}`,to:`${cur.score.home}-${cur.score.away}`,forceRecheck:true});if(cur.redCards.home>n(prev.redCards?.home)||cur.redCards.away>n(prev.redCards?.away))events.push({...base,type:'RED_CARD',severity:'CRITICAL',from:prev.redCards,to:cur.redCards,forceRecheck:true});const om=maxOddsMove(prev.odds,cur.odds);if(om.pct>=12)events.push({...base,type:'ODDS_SHOCK',severity:'HIGH',side:om.side,movePct:Number(om.pct.toFixed(1)),from:om.from,to:om.to,forceRecheck:true});else if(om.pct>=7)events.push({...base,type:'ODDS_MOVE',severity:'MEDIUM',side:om.side,movePct:Number(om.pct.toFixed(1)),from:om.from,to:om.to,forceRecheck:false});const pd=Math.abs(cur.pressure-n(prev.pressure,50));if(pd>=22)events.push({...base,type:'PRESSURE_SWING',severity:'HIGH',from:prev.pressure,to:cur.pressure,delta:pd,forceRecheck:true});else if(pd>=14)events.push({...base,type:'PRESSURE_SHIFT',severity:'MEDIUM',from:prev.pressure,to:cur.pressure,delta:pd,forceRecheck:false});if(!prev.isLive&&cur.isLive)events.push({...base,type:'KICKOFF',severity:'MEDIUM',forceRecheck:true});if(prev.isLive&&!cur.isLive&&['FT','AET','PEN'].includes(cur.status))events.push({...base,type:'MATCH_FINISHED',severity:'INFO',forceRecheck:false});return events}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!storageReady())return res.status(503).json({error:'Live event storage unavailable'});if(req.method==='GET'){const [state,log]=await Promise.all([readJson(STATE_PATH,{version:'LIVE-EVENTS-1',fixtures:{}}),readJson(LOG_PATH,{version:'LIVE-EVENT-LOG-1',events:[]})]);return res.status(200).json({version:'LIVE-EVENTS-1',updatedAt:state.updatedAt||null,summary:{tracked:Object.keys(state.fixtures||{}).length,recentEvents:(log.events||[]).slice(-50).length,forcedRechecks:(log.events||[]).slice(-50).filter(e=>e.forceRecheck).length},events:(log.events||[]).slice(-50).reverse()})}if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[];const state=await readJson(STATE_PATH,{version:'LIVE-EVENTS-1',fixtures:{}}),log=await readJson(LOG_PATH,{version:'LIVE-EVENT-LOG-1',events:[]});state.fixtures||={};log.events=Array.isArray(log.events)?log.events:[];const detected=[];for(const m of matches){if(!m?.id)continue;const cur=snapshot(m),prev=state.fixtures[String(m.id)]||null;detected.push(...diff(prev,cur));state.fixtures[String(m.id)]=cur}state.updatedAt=new Date().toISOString();state.version='LIVE-EVENTS-1';if(detected.length){log.events.push(...detected);if(log.events.length>1000)log.events=log.events.slice(-1000);log.updatedAt=state.updatedAt}await Promise.all([writeJson(STATE_PATH,state),writeJson(LOG_PATH,log)]);const forced=detected.filter(e=>e.forceRecheck);return res.status(200).json({ok:true,detected:detected.length,forcedRechecks:forced.length,events:detected,forceImmediateRefresh:forced.length>0,policy:'Events accelerate monitoring only. They never create or upgrade a betting verdict by themselves.'})}