import { listJson, readManyJson, writeJson, storageReady } from './_report-store.js';

const OUT='argus/learning/market-truth.json';
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const sideKey=s=>{const x=String(s||'').toUpperCase();return x==='HOME'?'home':x==='DRAW'?'draw':x==='AWAY'?'away':null};
function phaseBucket(mins){if(mins==null)return'UNKNOWN';if(mins>1440)return'T-24H+';if(mins>360)return'T-24_TO_6H';if(mins>60)return'T-6_TO_1H';if(mins>15)return'T-60_TO_15M';return'T-15M_TO_KO'}
function summarize(rows){if(!rows.length)return{sample:0,avgCLV:null,positiveCLVRate:null,avgEntryOdds:null,avgCloseOdds:null,avgBestPriceGain:null};const clv=rows.map(r=>r.clvPct).filter(Number.isFinite),pos=clv.filter(x=>x>0).length;return{sample:rows.length,avgCLV:clv.length?Number((clv.reduce((a,b)=>a+b,0)/clv.length).toFixed(2)):null,positiveCLVRate:clv.length?Number((pos/clv.length*100).toFixed(1)):null,avgEntryOdds:Number((rows.reduce((s,r)=>s+r.entryOdds,0)/rows.length).toFixed(3)),avgCloseOdds:Number((rows.reduce((s,r)=>s+r.closeOdds,0)/rows.length).toFixed(3)),avgBestPriceGain:Number((rows.reduce((s,r)=>s+r.bestPriceGainPct,0)/rows.length).toFixed(2))}}
function group(rows,keyFn){const m={};for(const r of rows){const k=keyFn(r);(m[k]||(m[k]=[])).push(r)}return Object.fromEntries(Object.entries(m).map(([k,v])=>[k,summarize(v)]))}
function firstEligibleSnapshot(predFixture,selection){const snaps=(predFixture?.snapshots||[]).filter(s=>s.phase==='PREMATCH').sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));return snaps.find(s=>String(s.selection||'').toUpperCase()===selection&&['PRIME','VALUE','WATCH'].some(v=>String(s.classification||'').toUpperCase().startsWith(v)))||snaps.find(s=>String(s.selection||'').toUpperCase()===selection)||snaps[0]||null}
export default async function handler(req,res){
 res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Market truth storage unavailable'});
 const [rb,pb,mb]=await Promise.all([listJson('argus/reports/',500),listJson('argus/predictions/',500),listJson('argus/market-memory/',500)]),[reports,preds,mems]=await Promise.all([readManyJson(rb),readManyJson(pb),readManyJson(mb)]),predByDate=new Map(preds.map(x=>[String(x.date),x])),memByDate=new Map(mems.map(x=>[String(x.date),x])),observations=[];
 for(const report of reports){const pred=predByDate.get(String(report.date)),mem=memByDate.get(String(report.date));for(const r of report.matches||[]){if(!['WIN','LOSS'].includes(r.outcome)||r.prediction?.phase!=='PREMATCH')continue;const side=sideKey(r.prediction?.selection);if(!side)continue;const pf=pred?.fixtures?.[String(r.fixtureId)],mf=mem?.fixtures?.[String(r.fixtureId)],entry=firstEligibleSnapshot(pf,String(r.prediction?.selection||'').toUpperCase());if(!entry||!mf)continue;const ko=new Date(r.kickoff||0).getTime(),entryAt=new Date(entry.recordedAt||0).getTime();if(!Number.isFinite(ko)||!Number.isFinite(entryAt))continue;const snaps=(mf.snapshots||[]).filter(s=>s.phase==='PREMATCH'&&new Date(s.recordedAt).getTime()>=entryAt&&new Date(s.recordedAt).getTime()<=ko&&n(s?.odds?.[side])>1).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));if(!snaps.length)continue;const entryOdds=n(snaps[0].odds?.[side]),closeOdds=n(snaps[snaps.length-1].odds?.[side]);if(!(entryOdds>1&&closeOdds>1))continue;const best=Math.max(...snaps.map(s=>n(s.odds?.[side])||0)),clv=(entryOdds/closeOdds-1)*100,bestGain=(best/entryOdds-1)*100,mins=(ko-entryAt)/60000;observations.push({fixtureId:r.fixtureId,league:r.competition||'UNKNOWN',selection:String(r.prediction?.selection||'UNKNOWN').toUpperCase(),verdict:String(r.prediction?.classification||r.prediction?.verdict||'UNKNOWN').toUpperCase(),entryOdds,closeOdds,bestOdds:best,clvPct:Number(clv.toFixed(2)),bestPriceGainPct:Number(bestGain.toFixed(2)),minutesBeforeKickoff:Number(mins.toFixed(1)),phaseBucket:phaseBucket(mins),snapshotCount:snaps.length,outcome:r.outcome})}}
 const state={version:'MARKET-TRUTH-1',generatedAt:new Date().toISOString(),observations:observations.length,global:summarize(observations),byLeague:group(observations,r=>r.league),bySelection:group(observations,r=>r.selection),byVerdict:group(observations,r=>r.verdict),byPhase:group(observations,r=>r.phaseBucket),byLeagueSelection:group(observations,r=>`${r.league}|||${r.selection}`),policy:{closingLineIsPrimaryMarketTruth:true,minimumEvidenceForClaim:50,positiveCLVDoesNotCreatePrime:true,negativeCLVMayTriggerReview:true,automaticBetPlacement:false,rule:'ARGUS treats repeatable positive CLV as evidence of market value, not proof of guaranteed profit.'}};
 if(req.method==='POST')await writeJson(OUT,state);return res.status(200).json(state)
}
