import { readJson, storageReady } from './_report-store.js';

const TZ='Europe/Brussels';
function dateTZ(v=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(v);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function overround(o={}){const h=n(o.home),d=n(o.draw),a=n(o.away);return h>1&&d>1&&a>1?(1/h+1/d+1/a-1)*100:null}
function pctMove(a,b){if(!(a>1&&b>1))return null;return ((b/a)-1)*100}
function implied(o){const x=n(o);return x>1?1/x:0}
function normalizedOdds(o={}){const h=implied(o.home),d=implied(o.draw),a=implied(o.away),s=h+d+a;return s?{home:h/s,draw:d/s,away:a/s}:null}
function normalizedModel(match){const p=match?.preMatchModel;if(!p)return null;const h=n(p.home),d=n(p.draw),a=n(p.away),s=h+d+a;return s?{home:h/s,draw:d/s,away:a/s}:null}
function modelSide(match,market){const p=normalizedModel(match);if(!p||!market)return null;return ['home','draw','away'].map(side=>({side,edge:p[side]-market[side]})).sort((a,b)=>b.edge-a.edge)[0]}
function minutesToKickoff(match){const t=new Date(match?.kickoff||0).getTime();return Number.isFinite(t)?Math.max(0,(t-Date.now())/60000):null}
function timeBucket(minutes){if(minutes==null)return'UNKNOWN';if(minutes<=15)return'0-15M';if(minutes<=60)return'16-60M';if(minutes<=180)return'61-180M';return'180M+'}
function learningType(status){return status==='CONFIRMING_STEAM'?'STEAM':status==='CONFIRMING_MOVE'?'SUPPORT':status==='ADVERSE_STEAM'?'ADVERSE_STEAM':status==='ADVERSE_DRIFT'?'ADVERSE_DRIFT':status==='REVERSAL'?'REVERSAL':'FLAT'}
function learnedPenalty(learning,match,status){const type=learningType(status),tb=timeBucket(minutesToKickoff(match)),league=match?.competition||'UNKNOWN',p=learning?.profiles||{},candidates=[['LEAGUE_TIMING',p.byLeagueTiming?.[`${league}|||${type}|||${tb}`]],['LEAGUE_TYPE',p.byLeagueType?.[`${league}|||${type}`]],['TIMING',p.byTiming?.[`${type}|||${tb}`]],['TYPE',p.byType?.[type]]].filter(([,x])=>x&&Number(x.sample)>=30);if(!candidates.length)return{penalty:0,status:'LEARNING',evidence:[]};const evidence=candidates.map(([source,x])=>({source,status:x.status,sample:x.sample,roi:x.roi,avgCLV:x.avgCLV,penalty:x.penalty||0,reason:x.reason})),worst=evidence.slice().sort((a,b)=>(b.penalty||0)-(a.penalty||0))[0];return{penalty:Math.min(8,Number(worst?.penalty)||0),status:worst?.status||'NEUTRAL',evidence,timeBucket:tb,type}}
function timingAdvice(learning,match,selectedSide){const tb=timeBucket(minutesToKickoff(match)),league=match?.competition||'UNKNOWN',sel=String(selectedSide||'UNKNOWN').toUpperCase(),p=learning?.profiles||{},candidates=[['LEAGUE_TIMING',p.byLeagueTiming?.[`${league}|||${tb}`]],['SELECTION_TIMING',p.bySelectionTiming?.[`${sel}|||${tb}`]],['TIMING',p.byTiming?.[tb]]].filter(([,x])=>x&&Number(x.sample)>=30);if(!candidates.length)return{action:'LEARNING',status:'LEARNING',penalty:0,evidence:[],timeBucket:tb};const evidence=candidates.map(([source,x])=>({source,status:x.status,action:x.action,sample:x.sample,waitBetterRate:x.waitBetterRate,entryBetterRate:x.entryBetterRate,avgBestLaterGainPct:x.avgBestLaterGainPct,avgEntryVsClosePct:x.avgEntryVsClosePct,reason:x.reason}));const wait=evidence.filter(x=>x.action==='WAIT').sort((a,b)=>b.sample-a.sample)[0],take=evidence.filter(x=>x.action==='TAKE_NOW').sort((a,b)=>b.sample-a.sample)[0];if(wait)return{action:'WAIT',status:wait.status,penalty:2,evidence,timeBucket:tb,reason:wait.reason};if(take)return{action:'TAKE_NOW',status:take.status,penalty:0,evidence,timeBucket:tb,reason:take.reason};return{action:'NO_TIMING_EDGE',status:'NEUTRAL',penalty:0,evidence,timeBucket:tb,reason:'No stable timing edge detected'}}
function summarize(fixture,match){const s=(fixture?.snapshots||[]).filter(x=>x.phase==='PREMATCH'&&x?.odds?.home>1&&x?.odds?.draw>1&&x?.odds?.away>1).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));if(!s.length)return{regime:'UNKNOWN',directionalStatus:'INSUFFICIENT',confidence:'LOW',reasons:['NO_MARKET_MEMORY'],sample:0};const first=s[0],last=s[s.length-1],moves=['home','draw','away'].map(k=>({side:k,oddsMove:pctMove(first.odds[k],last.odds[k])})).filter(x=>Number.isFinite(x.oddsMove)),maxAbs=moves.length?Math.max(...moves.map(x=>Math.abs(x.oddsMove))):0,spanMinutes=Math.max(0,(new Date(last.recordedAt)-new Date(first.recordedAt))/60000),lastAgeMinutes=Math.max(0,(Date.now()-new Date(last.recordedAt).getTime())/60000),margin=overround(last.odds),reasons=[];let regime='STABLE',confidence=s.length>=4?'HIGH':s.length>=2?'MEDIUM':'LOW';if(lastAgeMinutes>45){regime='STALE';reasons.push('STALE_CLOSING_OBSERVATION')}else if(maxAbs>=10){regime='VOLATILE';reasons.push('LARGE_PRICE_SWING')}else if(maxAbs>=5){regime='MOVING';reasons.push('MEANINGFUL_PRICE_MOVE')}else reasons.push('LIMITED_PRICE_DRIFT');if(margin!=null&&margin>=12){regime=regime==='VOLATILE'?'VOLATILE':'WIDE';reasons.push('HIGH_OVERROUND')}
 const firstMarket=normalizedOdds(first.odds),lastMarket=normalizedOdds(last.odds),best=modelSide(match,lastMarket);let directionalStatus='NEUTRAL',directionalPenalty=0,directionalWeight=1,directionalReason='No material directional conflict';let selectedMovePct=null,reversal=false;if(best&&firstMarket&&lastMarket){selectedMovePct=(lastMarket[best.side]-firstMarket[best.side])*100;const recent=s.slice(-3);if(recent.length>=3){const a=normalizedOdds(recent[0].odds),b=normalizedOdds(recent[1].odds),c=normalizedOdds(recent[2].odds);if(a&&b&&c){const d1=b[best.side]-a[best.side],d2=c[best.side]-b[best.side];reversal=Math.abs(d1)>=.02&&Math.abs(d2)>=.02&&Math.sign(d1)!==Math.sign(d2)}}const steam=s.length>=3&&spanMinutes>=15&&Math.abs(selectedMovePct)>=4;if(reversal){directionalStatus='REVERSAL';directionalPenalty=7;directionalWeight=.90;directionalReason='Recent market direction reversed sharply'}else if(steam&&selectedMovePct<=-4){directionalStatus='ADVERSE_STEAM';directionalPenalty=8;directionalWeight=.88;directionalReason='Market moved materially against ARGUS model side'}else if(selectedMovePct<=-2.5){directionalStatus='ADVERSE_DRIFT';directionalPenalty=4;directionalWeight=.94;directionalReason='Market drift conflicts with ARGUS model side'}else if(steam&&selectedMovePct>=4){directionalStatus='CONFIRMING_STEAM';directionalWeight=1.01;directionalReason='Market moved toward ARGUS model side; confirmation only'}else if(selectedMovePct>=2.5){directionalStatus='CONFIRMING_MOVE';directionalWeight=1.005;directionalReason='Market direction mildly confirms ARGUS model side'}}
 return{regime,directionalStatus,directionalPenalty,directionalWeight,directionalReason,selectedSide:best?.side||null,selectedMovePct:selectedMovePct==null?null:+selectedMovePct.toFixed(2),reversal,confidence,reasons,sample:s.length,spanMinutes:+spanMinutes.toFixed(1),lastAgeMinutes:+lastAgeMinutes.toFixed(1),maxMovePct:+maxAbs.toFixed(2),movesPct:{home:+(pctMove(first.odds.home,last.odds.home)||0).toFixed(2),draw:+(pctMove(first.odds.draw,last.odds.draw)||0).toFixed(2),away:+(pctMove(first.odds.away,last.odds.away)||0).toFixed(2)},overroundPct:margin==null?null:+margin.toFixed(2),first:first.odds,last:last.odds,firstRecordedAt:first.recordedAt,lastRecordedAt:last.recordedAt}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(200).json({ok:true,fixtures:0,regimes:{},storage:false});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],byDate=new Map(),regimes={},steam=await readJson('argus/learning/steam-learning.json',null),timing=await readJson('argus/learning/odds-timing.json',null);for(const m of matches){const date=dateTZ(new Date(m.kickoff||Date.now()));if(!byDate.has(date))byDate.set(date,await readJson(`argus/market-memory/${date}.json`,{fixtures:{}}));const memory=byDate.get(date),profile=summarize(memory?.fixtures?.[String(m.id)],m),learned=learnedPenalty(steam,m,profile.directionalStatus),timingRec=timingAdvice(timing,m,profile.selectedSide);const basePenalty=profile.regime==='VOLATILE'?8:profile.regime==='WIDE'?6:profile.regime==='STALE'?5:profile.regime==='MOVING'?2:0,penalty=Math.max(basePenalty,profile.directionalPenalty||0,learned.penalty||0,timingRec.penalty||0);regimes[String(m.id)]={fixtureId:m.id,...profile,steamLearningStatus:learned.status,steamLearningPenalty:learned.penalty||0,steamLearningEvidence:learned.evidence||[],steamLearningType:learned.type||learningType(profile.directionalStatus),steamLearningTimeBucket:learned.timeBucket||timeBucket(minutesToKickoff(m)),timingAction:timingRec.action,timingStatus:timingRec.status,timingPenalty:timingRec.penalty||0,timingReason:timingRec.reason||null,timingEvidence:timingRec.evidence||[],timingTimeBucket:timingRec.timeBucket,confidencePenalty:penalty,betEligible:!['VOLATILE','STALE'].includes(profile.regime)&&!['REVERSAL','ADVERSE_STEAM'].includes(profile.directionalStatus)&&timingRec.action!=='WAIT',governance:{mayCreatePrime:false,mayUpgradeVerdict:false,positiveConfirmationWeightCap:1.01,learnedPositivePromotionAllowed:false,learnedPenaltyMax:8,timingWaitMaySuspend:true,takeNowMayPromote:false,mayDowngrade:true,hardBlock:false}}}return res.status(200).json({ok:true,version:'MARKET-REGIME-4',fixtures:Object.keys(regimes).length,steamLearningVersion:steam?.version||null,oddsTimingVersion:timing?.version||null,regimes,policy:{directionalMarketEvidence:true,settledSteamLearning:true,oddsTimingLearning:true,directProbabilityMutation:false,promotionAllowed:false,positiveConfirmationCapped:true,learningDowngradeOnly:true,takeNowCannotPromote:true}})}
