import { readJson, storageReady } from './_report-store.js';

const TZ='Europe/Brussels';
function dateTZ(v=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(v);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function overround(o={}){const h=n(o.home),d=n(o.draw),a=n(o.away);return h>1&&d>1&&a>1?(1/h+1/d+1/a-1)*100:null}
function pctMove(a,b){if(!(a>1&&b>1))return null;return ((b/a)-1)*100}
function summarize(fixture){const s=(fixture?.snapshots||[]).filter(x=>x.phase==='PREMATCH'&&x?.odds?.home>1&&x?.odds?.draw>1&&x?.odds?.away>1).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));if(!s.length)return{regime:'UNKNOWN',confidence:'LOW',reasons:['NO_MARKET_MEMORY'],sample:0};const first=s[0],last=s[s.length-1],moves=['home','draw','away'].map(k=>pctMove(first.odds[k],last.odds[k])).filter(Number.isFinite),maxAbs=moves.length?Math.max(...moves.map(Math.abs)):0,spanMinutes=Math.max(0,(new Date(last.recordedAt)-new Date(first.recordedAt))/60000),lastAgeMinutes=Math.max(0,(Date.now()-new Date(last.recordedAt).getTime())/60000),margin=overround(last.odds),reasons=[];let regime='STABLE',confidence=s.length>=4?'HIGH':s.length>=2?'MEDIUM':'LOW';if(lastAgeMinutes>45){regime='STALE';reasons.push('STALE_CLOSING_OBSERVATION')}else if(maxAbs>=10){regime='VOLATILE';reasons.push('LARGE_PRICE_SWING')}else if(maxAbs>=5){regime='MOVING';reasons.push('MEANINGFUL_PRICE_MOVE')}else reasons.push('LIMITED_PRICE_DRIFT');if(margin!=null&&margin>=12){regime=regime==='VOLATILE'?'VOLATILE':'WIDE';reasons.push('HIGH_OVERROUND')}return{regime,confidence,reasons,sample:s.length,spanMinutes:+spanMinutes.toFixed(1),lastAgeMinutes:+lastAgeMinutes.toFixed(1),maxMovePct:+maxAbs.toFixed(2),movesPct:{home:+(pctMove(first.odds.home,last.odds.home)||0).toFixed(2),draw:+(pctMove(first.odds.draw,last.odds.draw)||0).toFixed(2),away:+(pctMove(first.odds.away,last.odds.away)||0).toFixed(2)},overroundPct:margin==null?null:+margin.toFixed(2),first:first.odds,last:last.odds,firstRecordedAt:first.recordedAt,lastRecordedAt:last.recordedAt}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(200).json({ok:true,fixtures:0,regimes:{},storage:false});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],byDate=new Map(),regimes={};for(const m of matches){const date=dateTZ(new Date(m.kickoff||Date.now()));if(!byDate.has(date))byDate.set(date,await readJson(`argus/market-memory/${date}.json`,{fixtures:{}}));const memory=byDate.get(date),profile=summarize(memory?.fixtures?.[String(m.id)]);const penalty=profile.regime==='VOLATILE'?8:profile.regime==='WIDE'?6:profile.regime==='STALE'?5:profile.regime==='MOVING'?2:0;regimes[String(m.id)]={fixtureId:m.id,...profile,confidencePenalty:penalty,betEligible:!['VOLATILE','STALE'].includes(profile.regime),governance:{mayCreatePrime:false,mayDowngrade:true,hardBlock:false}}}return res.status(200).json({ok:true,version:'MARKET-REGIME-1',fixtures:Object.keys(regimes).length,regimes})}
