const MAX_ADJ=.025;
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function clamp(v,lo=-MAX_ADJ,hi=MAX_ADJ){return Math.max(lo,Math.min(hi,v))}
function text(m){return [m?.competition,m?.league,m?.round,m?.stage,m?.status?.long,m?.status?.short].filter(Boolean).join(' ').toLowerCase()}
function classify(m){const t=text(m);const cup=/cup|copa|coupe|pokal|coppa|taça|knockout|playoff|play-off|final|semi|quarter|round of|champions league|europa league|conference league/.test(t);const final=/\bfinal\b/.test(t)&&!/semi|quarter/.test(t);const semi=/semi/.test(t);const playoff=/playoff|play-off|knockout|round of|quarter/.test(t);const friendly=/friendly|club friendly|amical/.test(t);return{cup,final,semi,playoff,friendly}}
function standings(m){const h=m?.context?.homeStanding??m?.homeStanding??m?.standings?.home??null,a=m?.context?.awayStanding??m?.awayStanding??m?.standings?.away??null;return{home:Number.isFinite(Number(h))?Number(h):null,away:Number.isFinite(Number(a))?Number(a):null}}
function derive(m){const c=classify(m),s=standings(m);let home=0,draw=0,away=0,confidence='LOW';const reasons=[];if(c.friendly){draw+=.004;reasons.push('FRIENDLY_VOLATILITY')}
if(c.final){draw+=.010;home-=.003;away-=.003;confidence='MEDIUM';reasons.push('FINAL_CAUTION')}
else if(c.semi||c.playoff){draw+=.006;confidence='MEDIUM';reasons.push('KNOCKOUT_CAUTION')}
if(s.home!==null&&s.away!==null){const gap=s.away-s.home;if(Math.abs(gap)>=8){const boost=Math.min(.012,Math.abs(gap)*.0008);if(gap>0){home+=boost;away-=boost*.55;reasons.push('TABLE_STRENGTH_HOME')}else{away+=boost;home-=boost*.55;reasons.push('TABLE_STRENGTH_AWAY')}confidence='MEDIUM'}else if(Math.abs(gap)<=2){draw+=.004;reasons.push('TABLE_PARITY')}}
return{delta:{home:clamp(home),draw:clamp(draw),away:clamp(away)},confidence,reasons,signals:{...c,standings:s}}}
function adjust(model,d){if(!model)return null;let h=n(model.home),x=n(model.draw),a=n(model.away);if(!(h>0&&x>0&&a>0))return null;h=Math.max(.01,h*(1+d.home));x=Math.max(.01,x*(1+d.draw));a=Math.max(.01,a*(1+d.away));const z=h+x+a;return{home:+(h/z).toFixed(4),draw:+(x/z).toFixed(4),away:+(a/z).toFixed(4),source:'ARGUS-MATCH-CONTEXT'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],impact={};for(const m of matches.filter(x=>!x.isFinished)){const ctx=derive(m),adjustedModel=adjust(m.preMatchModel,ctx.delta);impact[String(m.id)]={competition:m.competition||null,confidence:ctx.confidence,reasons:ctx.reasons,signals:ctx.signals,probabilityDelta:{home:+(ctx.delta.home*100).toFixed(2),draw:+(ctx.delta.draw*100).toFixed(2),away:+(ctx.delta.away*100).toFixed(2)},adjustedModel,governance:{maxAbsoluteAdjustmentPct:MAX_ADJ*100,observedSignalsOnly:true,mayCreatePrime:false,mayDowngrade:true}}}return res.status(200).json({ok:true,version:'MATCH-CONTEXT-1',fixtures:Object.keys(impact).length,impact})}
