import { readJson, storageReady } from './_report-store.js';

const ROOT='argus/matchup-memory';
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function norm(v){return String(v||'UNKNOWN').replace(/[^0-9A-Za-z-]/g,'')||'UNKNOWN'}
function key(own,opp){return `${norm(own)}__vs__${norm(opp)}`}
function summarize(rows=[]){const sample=rows.length;if(!sample)return{sample:0,confidence:'NONE'};const p=rows.reduce((s,x)=>s+n(x.points),0),gf=rows.reduce((s,x)=>s+n(x.gf),0),ga=rows.reduce((s,x)=>s+n(x.ga),0);return{sample,ppg:p/sample,goalDiff:(gf-ga)/sample,confidence:sample>=12?'HIGH':sample>=6?'MEDIUM':'LOW'}}
async function profile(teamId,own,opp){if(!storageReady()||!teamId||!own||!opp)return null;const doc=await readJson(`${ROOT}/${teamId}.json`,{matchups:{}}),rows=doc.matchups?.[key(own,opp)]||[];return summarize(rows)}
function delta(p){if(!p||p.sample<6)return 0;const ppgDelta=(p.ppg-1.5)/1.5,gdDelta=p.goalDiff/2,blend=.65*ppgDelta+.35*gdDelta,trust=p.sample>=12?.65:.35;return Math.max(-.05,Math.min(.05,blend*.05*trust))}
function adjust(model,homeDelta,awayDelta){if(!model)return null;let h=n(model.home),d=n(model.draw),a=n(model.away);if(!(h>0&&d>0&&a>0))return null;h=Math.max(.01,h*(1+homeDelta-awayDelta*.3));a=Math.max(.01,a*(1+awayDelta-homeDelta*.3));d=Math.max(.01,d*(1-Math.abs(homeDelta-awayDelta)*.15));const s=h+d+a;return{home:Number((h/s).toFixed(4)),draw:Number((d/s).toFixed(4)),away:Number((a/s).toFixed(4)),source:'ARGUS-MATCHUP-MEMORY'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],availability=req.body?.availability||{},impact={};for(const m of matches){const av=availability[String(m.id)];if(!av?.lineupsConfirmed)continue;const hf=av.home?.formation,af=av.away?.formation;if(!hf||!af)continue;const [hp,ap]=await Promise.all([profile(av.home?.teamId,hf,af),profile(av.away?.teamId,af,hf)]),hd=delta(hp),ad=delta(ap),adjustedModel=adjust(m.preMatchModel,hd,ad);impact[String(m.id)]={fixtureId:m.id,home:{formation:hf,opponentFormation:af,profile:hp,probabilityDelta:Number((hd*100).toFixed(2))},away:{formation:af,opponentFormation:hf,profile:ap,probabilityDelta:Number((ad*100).toFixed(2))},adjustedModel,governance:{minimumSample:6,highConfidenceSample:12,maxAbsoluteAdjustmentPct:5,mayCreatePrime:false,mayDowngrade:true}}}return res.status(200).json({version:'MATCHUP-IMPACT-1',generatedAt:new Date().toISOString(),fixtures:Object.keys(impact).length,impact})}
