import { requestQuery } from './_request-query.js';
import { readJson, writeJson, storageReady } from './_report-store.js';

const ROOT='argus/matchup-memory';
const FINAL=new Set(['FT','AET','PEN']);
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function norm(v){return String(v||'UNKNOWN').replace(/[^0-9A-Za-z-]/g,'')||'UNKNOWN'}
function pts(gf,ga){return gf>ga?3:gf===ga?1:0}
function key(own,opp){return `${norm(own)}__vs__${norm(opp)}`}
function summarize(rows=[]){const sample=rows.length;if(!sample)return{sample:0,confidence:'NONE'};const p=rows.reduce((s,x)=>s+n(x.points),0),gf=rows.reduce((s,x)=>s+n(x.gf),0),ga=rows.reduce((s,x)=>s+n(x.ga),0);return{sample,ppg:Number((p/sample).toFixed(3)),goalDiff:Number(((gf-ga)/sample).toFixed(3)),winRate:Number((rows.filter(x=>x.points===3).length/sample*100).toFixed(1)),confidence:sample>=12?'HIGH':sample>=6?'MEDIUM':'LOW'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!storageReady())return res.status(503).json({error:'Storage not configured'});if(req.method==='GET'){const teamId=String(requestQuery(req)?.teamId||''),own=String(requestQuery(req)?.formation||''),opp=String(requestQuery(req)?.opponentFormation||'');if(!teamId||!own||!opp)return res.status(400).json({error:'teamId, formation and opponentFormation required'});const doc=await readJson(`${ROOT}/${teamId}.json`,{matchups:{}}),rows=doc.matchups?.[key(own,opp)]||[];return res.status(200).json({teamId,formation:own,opponentFormation:opp,summary:summarize(rows),history:rows.slice(-40)})}if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const fixtures=Array.isArray(req.body?.fixtures)?req.body.fixtures:[];let saved=0;for(const f of fixtures){const status=String(f.status||f.fixture?.status?.short||'');if(!FINAL.has(status))continue;const homeId=Number(f.homeTeamId||f.teams?.home?.id),awayId=Number(f.awayTeamId||f.teams?.away?.id),hf=f.homeFormation||f.lineups?.home?.formation,af=f.awayFormation||f.lineups?.away?.formation,gfHome=n(f.goals?.home??f.homeGoals,NaN),gfAway=n(f.goals?.away??f.awayGoals,NaN),fixtureId=Number(f.id||f.fixture?.id);if(!homeId||!awayId||!hf||!af||!Number.isFinite(gfHome)||!Number.isFinite(gfAway)||!fixtureId)continue;for(const side of [{teamId:homeId,own:hf,opp:af,gf:gfHome,ga:gfAway},{teamId:awayId,own:af,opp:hf,gf:gfAway,ga:gfHome}]){const path=`${ROOT}/${side.teamId}.json`,doc=await readJson(path,{teamId:side.teamId,matchups:{},updatedAt:null}),k=key(side.own,side.opp),rows=Array.isArray(doc.matchups[k])?doc.matchups[k]:[];if(rows.some(x=>Number(x.fixtureId)===fixtureId))continue;rows.push({fixtureId,date:f.date||f.fixture?.date||new Date().toISOString(),formation:norm(side.own),opponentFormation:norm(side.opp),gf:side.gf,ga:side.ga,points:pts(side.gf,side.ga)});doc.matchups[k]=rows.slice(-100);doc.updatedAt=new Date().toISOString();await writeJson(path,doc);saved++}}return res.status(200).json({ok:true,saved})}
