import { listJson, readManyJson, readJson, writeJson, storageReady } from './_report-store.js';

const STATE_PATH='argus/autopilot/model-health.json';
function num(v){const x=Number(v);return Number.isFinite(x)?x:null}
function add(map,key,row){if(!map[key])map[key]={n:0,w:0,l:0,pl:0};const a=map[key];a.n++;if(row.outcome==='WIN')a.w++;if(row.outcome==='LOSS')a.l++;if(num(row.pl)!=null)a.pl+=Number(row.pl)}
function metrics(a){const n=a.w+a.l,roi=n?100*a.pl/n:null;return{sample:n,wins:a.w,losses:a.l,roi:roi==null?null:Number(roi.toFixed(2))}}
function desiredStatus(m){if(m.sample<20)return'UNVALIDATED';if(m.roi<=-15)return'DEGRADED';if(m.roi<=-5)return'CAUTION';if(m.roi>=8&&m.sample>=50)return'VALIDATING_POSITIVE';return'NEUTRAL'}
function rank(s){return({DEGRADED:0,CAUTION:1,UNVALIDATED:2,NEUTRAL:3,RECOVERING:3,VALIDATING_POSITIVE:4})[s]??2}
function multiplier(status){return({DEGRADED:.78,CAUTION:.88,UNVALIDATED:1,NEUTRAL:1,RECOVERING:.96,VALIDATING_POSITIVE:1.04})[status]??1}
function evolve(prev,m){const target=desiredStatus(m),old=prev?.status||'UNVALIDATED';if(target==='DEGRADED'||target==='CAUTION')return{status:target,multiplier:multiplier(target),recoveryStreak:0,reason:'Negative out-of-sample evidence'};if(old==='DEGRADED'||old==='CAUTION'){const streak=(prev?.recoveryStreak||0)+1;if(target==='VALIDATING_POSITIVE'&&m.sample>=50&&streak>=3)return{status:'NEUTRAL',multiplier:1,recoveryStreak:streak,reason:'Recovered after 3 consecutive healthy evaluations'};return{status:'RECOVERING',multiplier:.96,recoveryStreak:streak,reason:'Evidence improved, recovery gate still active'}}return{status:target,multiplier:multiplier(target),recoveryStreak:prev?.recoveryStreak||0,reason:target==='VALIDATING_POSITIVE'?'Positive evidence; upside remains capped':'No material degradation detected'}}
function finish(group,previous={}){const out={};for(const[k,a]of Object.entries(group)){const m=metrics(a),e=evolve(previous[k],m);out[k]={...m,...e,updatedAt:new Date().toISOString()}}return out}

export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Model health storage unavailable'});const blobs=await listJson('argus/reports/',400),reports=await readManyJson(blobs),league={},phase={},classification={};for(const report of reports)for(const row of report.matches||[]){if(!['WIN','LOSS'].includes(row.outcome)||!row.prediction)continue;add(league,row.competition||'UNKNOWN',row);add(phase,row.prediction.phase||'UNKNOWN',row);add(classification,row.prediction.classification||'UNKNOWN',row)}const prev=await readJson(STATE_PATH,{version:'MODEL-HEALTH-0',league:{},phase:{},classification:{}});const state={version:'MODEL-HEALTH-1',generatedAt:new Date().toISOString(),policy:{minimumSample:20,recoveryEvaluations:3,minMultiplier:.78,maxMultiplier:1.04,primeUnlock:false,rule:'Negative evidence acts immediately. Recovery requires repeated healthy evaluations. PRIME remains governed separately.'},league:finish(league,prev.league),phase:finish(phase,prev.phase),classification:finish(classification,prev.classification)};await writeJson(STATE_PATH,state);return res.status(200).json(state)}