import { readJson, writeJson, storageReady } from './_report-store.js';
const PATH='argus/player-memory/state.json';
const FINISHED=new Set(['FT','AET','PEN']);
function authorized(req){const s=String(process.env.CRON_SECRET||'').trim();return !s||req.headers.authorization===`Bearer ${s}`}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function key(t,p){return `${t}:${p}`}
function init(){return{version:'PLAYER-MEMORY-1',updatedAt:null,matches:{},players:{},teams:{}}}
function teamResult(match,side){const h=n(match?.score?.home),a=n(match?.score?.away),gf=side==='home'?h:a,ga=side==='home'?a:h,pts=gf>ga?3:gf===ga?1:0;return{gf,ga,pts,win:pts===3?1:0,draw:pts===1?1:0,loss:pts===0?1:0}}
function settlePlayer(state,teamId,teamName,p,r){const k=key(teamId,p.id),row=state.players[k]||{teamId,teamName,playerId:p.id,name:p.name||null,pos:p.pos||null,starts:0,points:0,gf:0,ga:0,wins:0,draws:0,losses:0};row.starts++;row.points+=r.pts;row.gf+=r.gf;row.ga+=r.ga;row.wins+=r.win;row.draws+=r.draw;row.losses+=r.loss;row.name=p.name||row.name;row.pos=p.pos||row.pos;state.players[k]=row}
function settleTeam(state,teamId,teamName,r){const k=String(teamId),row=state.teams[k]||{teamId,teamName,matches:0,points:0,gf:0,ga:0};row.matches++;row.points+=r.pts;row.gf+=r.gf;row.ga+=r.ga;row.teamName=teamName||row.teamName;state.teams[k]=row}
function profiles(state){const out={};for(const [k,p] of Object.entries(state.players||{})){const t=state.teams?.[String(p.teamId)]||{},teamPPG=t.matches?t.points/t.matches:0,ppg=p.starts?p.points/p.starts:0,delta=ppg-teamPPG,sample=p.starts,confidence=sample>=15?'HIGH':sample>=8?'MEDIUM':sample>=4?'LOW':'INSUFFICIENT';out[k]={...p,ppg:Number(ppg.toFixed(3)),teamPPG:Number(teamPPG.toFixed(3)),ppgDelta:Number(delta.toFixed(3)),goalDiffPerStart:sample?Number(((p.gf-p.ga)/sample).toFixed(3)):0,confidence,validated:sample>=8}}return out}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!storageReady())return res.status(503).json({error:'Player memory storage unavailable'});let state=await readJson(PATH,init());if(req.method==='GET')return res.status(200).json({version:state.version,updatedAt:state.updatedAt,profiles:profiles(state),teamCount:Object.keys(state.teams||{}).length,playerCount:Object.keys(state.players||{}).length,policy:{authenticatedWrites:true}});if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!authorized(req))return res.status(401).json({error:'Unauthorized'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],availability=req.body?.availability||{};let saved=0,settled=0;for(const m of matches){const id=String(m.id||'');if(!id)continue;const av=availability[id],prev=state.matches[id]||{};if(av?.lineupsConfirmed&&!prev.lineups){state.matches[id]={...prev,fixtureId:m.id,kickoff:m.kickoff,homeTeamId:av.home?.teamId,awayTeamId:av.away?.teamId,homeTeamName:av.home?.teamName||m.home,awayTeamName:av.away?.teamName||m.away,lineups:{home:av.home?.starters||[],away:av.away?.starters||[]},settled:false};saved++}const row=state.matches[id];if(row?.lineups&&!row.settled&&FINISHED.has(String(m.status))){const hr=teamResult(m,'home'),ar=teamResult(m,'away');settleTeam(state,row.homeTeamId,row.homeTeamName,hr);settleTeam(state,row.awayTeamId,row.awayTeamName,ar);for(const p of row.lineups.home||[])if(p?.id)settlePlayer(state,row.homeTeamId,row.homeTeamName,p,hr);for(const p of row.lineups.away||[])if(p?.id)settlePlayer(state,row.awayTeamId,row.awayTeamName,p,ar);row.settled=true;row.finalScore=m.score;row.finalStatus=m.status;settled++}}
state.updatedAt=new Date().toISOString();const ids=Object.keys(state.matches);if(ids.length>3000){ids.sort((a,b)=>new Date(state.matches[a].kickoff||0)-new Date(state.matches[b].kickoff||0));for(const id of ids.slice(0,ids.length-3000))delete state.matches[id]}await writeJson(PATH,state);return res.status(200).json({version:state.version,updatedAt:state.updatedAt,savedLineups:saved,settledMatches:settled,playerCount:Object.keys(state.players).length,teamCount:Object.keys(state.teams).length,profiles:profiles(state),policy:{authenticatedWrites:true}})}
