import { readJson, storageReady } from './_report-store.js';
import { VALIDATION_POLICY, isInValidationEpoch } from './_validation-policy.js';

const BANKROLL_PATH='argus/paper/virtual-bankroll.json';
const EPS=1e-12;
const n=(v,f=null)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const round=(v,d=3)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
function dayKey(v){const d=new Date(v||0);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):'UNKNOWN'}
function officialBet(b){return String(b?.cohort||'OFFICIAL_PAPER')==='OFFICIAL_PAPER'&&b?.integrity?.countsAsOfficialTrackRecord!==false&&isInValidationEpoch(b?.capturedAt)}
function decided(b){return b?.status==='WIN'||b?.status==='LOSS'}
function flatReturn(b){const o=n(b?.odds);if(!(o>1)||!decided(b))return null;return b.status==='WIN'?o-1:-1}
function shareMap(rows,keyFn){const m={};for(const r of rows){const k=String(keyFn(r)||'UNKNOWN');m[k]=(m[k]||0)+1}return Object.fromEntries(Object.entries(m).sort((a,b)=>b[1]-a[1]))}
function maxShare(map,total){if(!total)return 0;return Math.max(0,...Object.values(map).map(x=>x/total))}
function seeded(seed=2166136261){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function quantile(a,q){if(!a.length)return null;const x=(a.length-1)*q,lo=Math.floor(x),hi=Math.ceil(x);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(x-lo)}
function blockBootstrap(rows,reps=1600){
  if(rows.length<20)return{method:'DAY_BLOCK_BOOTSTRAP',reps:0,lower95:null,upper95:null};
  const groups=new Map();for(const r of rows){const k=dayKey(r.kickoff||r.capturedAt);const g=groups.get(k)||[];g.push(r._return);groups.set(k,g)}
  const days=[...groups.values()];if(days.length<2)return{method:'DAY_BLOCK_BOOTSTRAP',reps:0,lower95:null,upper95:null};
  const rng=seeded((rows.length*2654435761+days.length)>>>0),means=[];
  for(let z=0;z<reps;z++){let sum=0,count=0;for(let i=0;i<days.length;i++){const g=days[Math.floor(rng()*days.length)];for(const v of g){sum+=v;count++}}if(count)means.push(sum/count)}
  means.sort((a,b)=>a-b);return{method:'DAY_BLOCK_BOOTSTRAP',reps:means.length,blocks:days.length,lower95:round(quantile(means,.025)*100,2),upper95:round(quantile(means,.975)*100,2)}
}
function drawdown(rows){let equity=0,peak=0,max=0;for(const r of rows.slice().sort((a,b)=>new Date(a.kickoff||a.capturedAt)-new Date(b.kickoff||b.capturedAt))){equity+=r._return;peak=Math.max(peak,equity);max=Math.max(max,peak-equity)}return round(max,2)}
function calibration(rows){const x=rows.filter(r=>n(r.probability)!=null&&n(r.probability)>=0&&n(r.probability)<=1);if(!x.length)return{sample:0};let bs=0,marketBs=0,ll=0,ps=0,w=0;for(const r of x){const y=r.status==='WIN'?1:0,p=Math.min(1-EPS,Math.max(EPS,n(r.probability))),mp=Math.min(1-EPS,Math.max(EPS,1/n(r.odds)));bs+=(p-y)**2;marketBs+=(mp-y)**2;ll+=-(y*Math.log(p)+(1-y)*Math.log(1-p));ps+=p;w+=y}return{sample:x.length,brier:round(bs/x.length,4),rawImpliedOddsBrier:round(marketBs/x.length,4),logLoss:round(ll/x.length,4),meanPredictedPct:round(ps/x.length*100,1),observedWinPct:round(w/x.length*100,1),calibrationGapPp:round((ps/x.length-w/x.length)*100,1),note:'Raw implied-odds baseline is not vig-adjusted.'}}
function clv(rows){const x=rows.filter(r=>r?.closingEvidence?.sameSelection===true&&n(r.closingEvidence.rawClvPct)!=null);if(!x.length)return{sample:0,meanPct:null,medianPct:null,positiveSharePct:null,meanImpliedMovePp:null};const vals=x.map(r=>n(r.closingEvidence.rawClvPct)).sort((a,b)=>a-b),moves=x.map(r=>n(r.closingEvidence.impliedProbabilityMovePp,0));return{sample:x.length,meanPct:round(vals.reduce((a,b)=>a+b,0)/vals.length,2),medianPct:round(quantile(vals,.5),2),positiveSharePct:round(vals.filter(v=>v>0).length/vals.length*100,1),meanImpliedMovePp:round(moves.reduce((a,b)=>a+b,0)/moves.length,2),source:'same-selection near-kickoff market price from current decision plan',independentClosingBook:false}}
function grouped(rows,keyFn){const m=new Map();for(const r of rows){const k=String(keyFn(r)||'UNKNOWN'),a=m.get(k)||[];a.push(r);m.set(k,a)}return Object.fromEntries([...m.entries()].sort((a,b)=>b[1].length-a[1].length).slice(0,25).map(([k,a])=>[k,{sample:a.length,roiPct:round(a.reduce((s,r)=>s+r._return,0)/a.length*100,2),wins:a.filter(r=>r.status==='WIN').length,losses:a.filter(r=>r.status==='LOSS').length}]))}
function classify({sample,days,roi,ci,competitionCount,marketCount,maxCompetition,maxMarket,clvStats}){
  const t=VALIDATION_POLICY.thresholds;
  const positive=roi>0,ciPositive=n(ci.lower95)!=null&&ci.lower95>0;
  const finalOk=sample>=t.validated.settled&&days>=t.validated.days&&positive&&ciPositive&&competitionCount>=t.validated.competitions&&marketCount>=t.validated.marketFamilies&&maxCompetition<=t.validated.maxCompetitionShare&&maxMarket<=t.validated.maxMarketShare&&clvStats.sample>=t.validated.clvSample&&n(clvStats.meanPct,-Infinity)>0;
  if(finalOk)return'STATISTICALLY_VALIDATED';
  const provisional=sample>=t.provisional.settled&&days>=t.provisional.days&&positive&&ciPositive&&competitionCount>=t.provisional.competitions&&marketCount>=t.provisional.marketFamilies&&maxCompetition<=t.provisional.maxCompetitionShare;
  if(provisional)return'PROVISIONALLY_VALIDATED';
  if(sample>=t.promising.settled&&days>=t.promising.days&&positive)return'PROMISING';
  if(sample>=t.promising.settled&&n(ci.upper95)!=null&&ci.upper95<0)return'NEGATIVE_EVIDENCE';
  return'BUILDING_EVIDENCE';
}
function missingForValidation(x){const t=VALIDATION_POLICY.thresholds.validated,out=[];if(x.sample<t.settled)out.push(`${t.settled-x.sample} more settled official bets`);if(x.days<t.days)out.push(`${t.days-x.days} more validation days`);if(!(x.roi>0))out.push('positive flat-stake ROI');if(!(n(x.ci.lower95)!=null&&x.ci.lower95>0))out.push('95% lower confidence bound above 0%');if(x.competitionCount<t.competitions)out.push(`${t.competitions-x.competitionCount} more competitions`);if(x.marketCount<t.marketFamilies)out.push(`${t.marketFamilies-x.marketCount} more market families`);if(x.maxCompetition>t.maxCompetitionShare)out.push('reduce single-competition concentration');if(x.maxMarket>t.maxMarketShare)out.push('reduce single-market concentration');if(x.clvStats.sample<t.clvSample)out.push(`${t.clvSample-x.clvStats.sample} more near-close CLV observations`);if(!(n(x.clvStats.meanPct,-Infinity)>0))out.push('positive mean near-close CLV');return out}
export default async function handler(req,res){
  res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!storageReady())return res.status(503).json({error:'Storage unavailable'});
  const state=await readJson(BANKROLL_PATH,null);if(!state)return res.status(200).json({version:'PROFITABILITY-PROOF-1',status:'BUILDING_EVIDENCE',reason:'Virtual bankroll not initialized',policy:VALIDATION_POLICY});
  const all=Object.values(state.bets||{}).filter(officialBet),rows=all.filter(decided).map(b=>({...b,_return:flatReturn(b)})).filter(b=>n(b._return)!=null&&n(b.odds)>1);
  const wins=rows.filter(r=>r.status==='WIN').length,losses=rows.length-wins,total=rows.reduce((s,r)=>s+r._return,0),roi=rows.length?total/rows.length*100:0,ci=blockBootstrap(rows),dates=rows.map(r=>new Date(r.kickoff||r.capturedAt).getTime()).filter(Number.isFinite),first=dates.length?Math.min(...dates):null,last=dates.length?Math.max(...dates):null,elapsedDays=first?Math.max(1,Math.floor((Date.now()-first)/86400000)+1):0,byCompetitionCounts=shareMap(rows,r=>r.competition),byMarketCounts=shareMap(rows,r=>r.marketType),competitionCount=Object.keys(byCompetitionCounts).filter(k=>k!=='UNKNOWN').length,marketCount=Object.keys(byMarketCounts).filter(k=>k!=='UNKNOWN').length,maxCompetition=maxShare(byCompetitionCounts,rows.length),maxMarket=maxShare(byMarketCounts,rows.length),clvStats=clv(rows),status=classify({sample:rows.length,days:elapsedDays,roi,ci,competitionCount,marketCount,maxCompetition,maxMarket,clvStats});
  const facts={sample:rows.length,open:all.filter(b=>b.status==='OPEN').length,wins,losses,hitRatePct:rows.length?round(wins/rows.length*100,1):null,flatStakeProfitUnits:round(total,2),flatStakeRoiPct:rows.length?round(roi,2):null,confidenceInterval95:ci,maxDrawdownUnits:drawdown(rows),period:{epochStart:VALIDATION_POLICY.startsAt,firstBetAt:first?new Date(first).toISOString():null,lastDecidedBetAt:last?new Date(last).toISOString():null,elapsedDays},diversification:{competitions:competitionCount,marketFamilies:marketCount,maxCompetitionSharePct:round(maxCompetition*100,1),maxMarketSharePct:round(maxMarket*100,1),byCompetition:byCompetitionCounts,byMarket:byMarketCounts},calibration:calibration(rows),clv:clvStats};
  const assessment={status,statisticallyValidated:status==='STATISTICALLY_VALIDATED',profitabilityObserved:rows.length>0&&roi>0,profitabilityStatisticallySeparatedFromZero:n(ci.lower95)!=null&&ci.lower95>0,missingForFinalValidation:missingForValidation({sample:rows.length,days:elapsedDays,roi,ci,competitionCount,marketCount,maxCompetition,maxMarket,clvStats})};
  return res.status(200).json({ok:true,version:'PROFITABILITY-PROOF-1',generatedAt:new Date().toISOString(),epoch:VALIDATION_POLICY.epoch,assessment,facts,marketBreakdown:grouped(rows,r=>r.marketType),competitionBreakdown:grouped(rows,r=>r.competition),policy:VALIDATION_POLICY,integrity:{source:'VIRTUAL-BANKROLL-3/OFFICIAL_PAPER',learningShadowExcluded:true,oneOfficialPositionPerFixture:true,noHistoricalBackfill:true,noHindsight:true,flatStakePrimary:true,dayBlockBootstrap:true,marketOddsRequired:true,automaticRealWagering:false},disclaimer:'Statistical validation describes observed paper-betting evidence in this fixed prospective epoch; it cannot guarantee future profit.'});
}
