import { readJson, storageReady } from './_report-store.js';

const LIFE='argus/autopilot/opportunity-lifecycle.json';
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function rank(v){const x=String(v||'NO BET').toUpperCase();return x==='PRIME'?3:x==='VALUE'?2:x==='WATCH'?1:0}
function stabilityFor(f={}){const events=Array.isArray(f.events)?f.events.slice(-16):[];let vc=0,af=0,sc=0,rev=0,last=0;for(const e of events){const a=e?.from||{},b=e?.to||{};if(a.verdict&&b.verdict&&a.verdict!==b.verdict){vc++;const dir=Math.sign(rank(b.verdict)-rank(a.verdict));if(last&&dir&&dir!==last)rev++;if(dir)last=dir}if(typeof a.eligible==='boolean'&&typeof b.eligible==='boolean'&&a.eligible!==b.eligible)af++;if(a.selection&&b.selection&&a.selection!==b.selection)sc++}let score=100-Math.min(36,vc*7)-Math.min(24,af*8)-Math.min(24,sc*12)-Math.min(20,rev*8);score=Math.max(0,Math.round(score));let status=events.length<4?'LEARNING':'STABLE',penalty=0,hardBlock=false;if(events.length>=4&&(score<35||sc>=2||af>=4)){status='CHAOTIC';penalty=10;hardBlock=true}else if(events.length>=4&&(score<55||rev>=2||vc>=5)){status='UNSTABLE';penalty=7}else if(events.length>=4&&(score<75||vc>=3||af>=2)){status='OSCILLATING';penalty=4}else if(events.length>=4&&vc>=1){status='MOSTLY_STABLE';penalty=1}return{status,score,penalty,hardBlock,sampleEvents:events.length,verdictChanges:vc,actionabilityFlips:af,selectionChanges:sc,reversals:rev}}
function apply(d,t,s){if(!d)return null;let verdict=String(d.verdict||'NO BET').toUpperCase(),eligible=Boolean(d.eligible),issues=[...(d.issues||[])],positive=[...(d.positive||[])],reason=t?.reason||'Robustness unavailable';if(t){if(t.status==='FAIL'){issues.push('ROBUSTNESS_FAIL');if(t.hardBlock&&['PRIME','VALUE'].includes(verdict)){verdict='NO BET';eligible=false}}else if(t.status==='FRAGILE'){issues.push('ROBUSTNESS_FRAGILE');if(verdict==='PRIME')verdict='VALUE';else if(verdict==='VALUE'){verdict='WATCH';eligible=false}}else if(t.status==='ADEQUATE'){issues.push('ROBUSTNESS_ADEQUATE');if(verdict==='PRIME')verdict='VALUE'}else if(['STRONG','ROBUST'].includes(t.status)){positive.push(`ROBUSTNESS_${t.status}`)}}
 if(s){if(s.status==='CHAOTIC'){issues.push('DECISION_STABILITY_CHAOTIC');if(['PRIME','VALUE'].includes(verdict)){verdict='NO BET';eligible=false}}else if(s.status==='UNSTABLE'){issues.push('DECISION_STABILITY_UNSTABLE');if(verdict==='PRIME')verdict='VALUE';else if(verdict==='VALUE'){verdict='WATCH';eligible=false}}else if(s.status==='OSCILLATING'){issues.push('DECISION_STABILITY_OSCILLATING');if(verdict==='PRIME')verdict='VALUE'}else if(s.status==='STABLE')positive.push('DECISION_STABILITY_STABLE')}
 if(verdict==='WATCH'||verdict==='NO BET')eligible=false;const conf={...(d.confidence||{})},penalty=Math.max(0,n(t?.penalty,0))+Math.max(0,n(s?.penalty,0));if(Number.isFinite(Number(conf.net)))conf.net=Math.max(0,Number(conf.net)-penalty);if(Number.isFinite(Number(conf.penalty)))conf.penalty=Number(conf.penalty)+penalty;return{...d,preRobustnessVerdict:d.verdict,verdict,eligible,issues:[...new Set(issues)],positive:[...new Set(positive)],confidence:conf,robustnessTest:t||null,robustnessStatus:t?.status||'UNAVAILABLE',robustnessScore:t?.score??null,robustnessPenalty:n(t?.penalty,0),robustnessReason:reason,decisionStability:s||null,decisionStabilityStatus:s?.status||'UNAVAILABLE',decisionStabilityScore:s?.score??null,decisionStabilityPenalty:n(s?.penalty,0)}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const eligibility=req.body?.eligibility||{},tests=req.body?.robustness?.tests||req.body?.tests||{},src=eligibility.decisions||{};let life={fixtures:{}};if(storageReady())try{life=await readJson(LIFE,{fixtures:{}})}catch(_){}const decisions={};for(const[id,d]of Object.entries(src)){const s=stabilityFor(life.fixtures?.[id]||{});decisions[id]=apply(d,tests[id],s)}const vals=Object.values(decisions).filter(Boolean);return res.status(200).json({ok:true,version:'ROBUSTNESS-GATE-2',generatedAt:new Date().toISOString(),summary:{total:vals.length,prime:vals.filter(x=>x.verdict==='PRIME'&&x.eligible).length,value:vals.filter(x=>x.verdict==='VALUE'&&x.eligible).length,watch:vals.filter(x=>x.verdict==='WATCH').length,noBet:vals.filter(x=>x.verdict==='NO BET').length,eligible:vals.filter(x=>x.eligible).length,failed:vals.filter(x=>x.robustnessStatus==='FAIL').length,fragile:vals.filter(x=>x.robustnessStatus==='FRAGILE').length,stabilityChaotic:vals.filter(x=>x.decisionStabilityStatus==='CHAOTIC').length,stabilityUnstable:vals.filter(x=>x.decisionStabilityStatus==='UNSTABLE').length,stabilityOscillating:vals.filter(x=>x.decisionStabilityStatus==='OSCILLATING').length,downgraded:vals.filter(x=>x.preRobustnessVerdict&&x.preRobustnessVerdict!==x.verdict).length},policy:{downgradeOnly:true,mayCreatePrime:false,mayUpgradeVerdict:false,mayIncreaseConfidence:false,mayIncreaseStake:false,failMayHardBlock:true,fragileCannotRemainPrime:true,chaoticDecisionHistoryMayHardBlock:true,unstableDecisionHistoryCannotRemainActionableValue:true,stableHistoryCannotPromote:true,automaticBetPlacement:false},decisions})}
