import { readJson, writeJson, listJson, readManyJson, storageReady } from './_report-store.js';

const API_BASE='https://v3.football.api-sports.io';
const TZ='Europe/Brussels';
const QUOTA_GUARD_PATH='argus/data/api-football-quota-guard.json';
const FINAL=new Set(['FT','AET','PEN']);
const VOID=new Set(['CANC','ABD','AWD','WO']);
const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
const safe=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const fact=n=>{let x=1;for(let i=2;i<=n;i++)x*=i;return x};
const pois=(k,l)=>Math.exp(-l)*Math.pow(l,k)/fact(k);
function dateBrussels(d=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function lambdas(m){const h=m?.history90d?.home,a=m?.history90d?.away;if(!h||!a||safe(h.matches)<3||safe(a.matches)<3)return null;const fd=(safe(h.last5PPG)-safe(a.last5PPG))/3,vd=((h.homePPG==null?safe(h.pointsPerGame,1.4):safe(h.homePPG,1.4))-(a.awayPPG==null?safe(a.pointsPerGame,1.2):safe(a.awayPPG,1.2)))/3;let lh=safe(h.goalsForPerGame,1.2)*.54+safe(a.goalsAgainstPerGame,1.2)*.46,la=safe(a.goalsForPerGame,1.1)*.54+safe(h.goalsAgainstPerGame,1.1)*.46;lh*=1.06+fd*.11+vd*.08;la*=.98-fd*.07-vd*.05;return{home:clamp(lh,.2,3.8),away:clamp(la,.2,3.8),quality:clamp(Math.min(safe(h.matches),safe(a.matches))/10,0,1)}}
function matrix(m){const l=lambdas(m);if(!l)return null;const rows=[];for(let h=0;h<=7;h++)for(let a=0;a<=7;a++)rows.push({h,a,p:pois(h,l.home)*pois(a,l.away)});const s=rows.reduce((x,r)=>x+r.p,0)||1;rows.forEach(r=>r.p/=s);return{rows,l}}
function sum(rows,fn){return rows.reduce((s,r)=>s+(fn(r)?r.p:0),0)}
function odd(m,key){const v=m?.marketOdds?.[key]??m?.markets?.[key];const n=Number(v?.odds??v);return Number.isFinite(n)&&n>1?n:null}
function shadowMarkets(m){const x=matrix(m);if(!x)return[];const r=x.rows,q=Math.round(x.l.quality*100),mk=(key,label,prob)=>{const o=odd(m,key),edge=o?Number(((prob-1/o)*100).toFixed(1)):null;return{key,label,probability:Number(prob.toFixed(5)),odds:o,edge,quality:q}};const total=t=>sum(r,z=>z.h+z.a>t),btts=sum(r,z=>z.h>0&&z.a>0),hw=sum(r,z=>z.h>z.a),dr=sum(r,z=>z.h===z.a),aw=sum(r,z=>z.h<z.a);const scores=r.slice().sort((a,b)=>b.p-a.p).slice(0,3).map(z=>({key:`score:${z.h}-${z.a}`,label:`Exact ${z.h}-${z.a}`,probability:Number(z.p.toFixed(5)),odds:Number(m?.marketOdds?.exactScores?.[`${z.h}-${z.a}`])||null,quality:q}));return [mk('over15','Over 1.5',total(1.5)),mk('over25','Over 2.5',total(2.5)),mk('over35','Over 3.5',total(3.5)),mk('under25','Under 2.5',1-total(2.5)),mk('bttsYes','BTTS Yes',btts),mk('bttsNo','BTTS No',1-btts),mk('homeOver05','Home O0.5',sum(r,z=>z.h>.5)),mk('awayOver05','Away O0.5',sum(r,z=>z.a>.5)),mk('doubleChance1X','Double Chance 1X',hw+dr),mk('doubleChanceX2','Double Chance X2',aw+dr),...scores]}
function currentOddsMap(m){const out={};for(const p of shadowMarkets(m)){if(p.odds)out[p.key]=p.odds}return out}
function settlePick(p,h,a){const key=p.key;if(key==='over15')return h+a>1;if(key==='over25')return h+a>2;if(key==='over35')return h+a>3;if(key==='under25')return h+a<3;if(key==='bttsYes')return h>0&&a>0;if(key==='bttsNo')return !(h>0&&a>0);if(key==='homeOver05')return h>0;if(key==='awayOver05')return a>0;if(key==='doubleChance1X')return h>=a;if(key==='doubleChanceX2')return a>=h;if(key.startsWith('score:'))return key.slice(6)===`${h}-${a}`;return null}
async function fetchFixtures(date){const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error('API_FOOTBALL_KEY is not configured');const r=await fetch(`${API_BASE}/fixtures?date=${date}&timezone=${encodeURIComponent(TZ)}`,{headers:{'x-apisports-key':key,Accept:'application/json'}});if(!r.ok)throw new Error(`API-Football HTTP ${r.status}`);const j=await r.json();return j.response||[]}
function lastClosingSnapshot(f){const ko=new Date(f.kickoff||0).getTime();return (f.oddsSnapshots||[]).filter(s=>new Date(s.recordedAt).getTime()<=ko).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt)).pop()||null}
async function capture(req,res){if(!storageReady())return res.status(503).json({error:'Storage unavailable'});const body=req.body||{},date=String(body.date||dateBrussels()),matches=Array.isArray(body.matches)?body.matches:[];const path=`argus/shadow/${date}.json`,store=await readJson(path,{date,createdAt:new Date().toISOString(),fixtures:{}});let frozen=0,snapshots=0,skippedLate=0;for(const m of matches){if(!m?.id||m.isFinished)continue;const now=Date.now(),kickoff=new Date(m.kickoff||0).getTime();if(Number.isFinite(kickoff)&&now>=kickoff){skippedLate++;continue}const id=String(m.id),picks=shadowMarkets(m);if(!picks.length)continue;let f=store.fixtures[id];if(!f){f={fixtureId:m.id,competition:m.competition||null,home:m.home,away:m.away,kickoff:m.kickoff||null,frozenAt:new Date().toISOString(),freezeVersion:'SHADOW-FREEZE-2',picks:picks.map(p=>({...p,frozen:true})),oddsSnapshots:[]};frozen+=picks.length}const odds=currentOddsMap(m);if(Object.keys(odds).length){const snap={recordedAt:new Date().toISOString(),odds};const last=f.oddsSnapshots?.[f.oddsSnapshots.length-1];if(JSON.stringify(last?.odds)!==JSON.stringify(odds)){f.oddsSnapshots=f.oddsSnapshots||[];f.oddsSnapshots.push(snap);if(f.oddsSnapshots.length>120)f.oddsSnapshots=f.oddsSnapshots.slice(-120);snapshots++}}store.fixtures[id]=f}store.updatedAt=new Date().toISOString();store.integrity='IMMUTABLE FIRST FREEZE — later captures may append odds snapshots only.';await writeJson(path,store);return res.status(200).json({ok:true,date,fixtures:Object.keys(store.fixtures).length,frozenPicks:frozen,oddsSnapshots:snapshots,skippedLate})}
async function settle(req,res){if(!storageReady())return res.status(503).json({error:'Storage unavailable'});const date=String(req.query?.date||dateBrussels()),guard=await readJson(QUOTA_GUARD_PATH,null);if(guard?.date===date&&guard?.exhausted)return res.status(200).json({ok:true,date,settled:0,skipped:true,reason:'PROVIDER_BLOCKED_BY_QUOTA_GUARD',providerCallSkipped:true});const path=`argus/shadow/${date}.json`,store=await readJson(path,null);if(!store)return res.status(200).json({ok:true,date,settled:0,reason:'NO_SHADOW_BOOK'});const rows=await fetchFixtures(date),byId=new Map(rows.map(x=>[String(x.fixture?.id),x]));let settled=0,wins=0,losses=0,clvN=0,clvSum=0;for(const [id,f] of Object.entries(store.fixtures||{})){const r=byId.get(id),st=r?.fixture?.status?.short;if(VOID.has(st)){for(const p of f.picks||[])p.outcome='VOID';continue}if(!FINAL.has(st))continue;const h=Number(r?.goals?.home),a=Number(r?.goals?.away);if(!Number.isFinite(h)||!Number.isFinite(a))continue;f.finalScore={home:h,away:a};f.settledAt=new Date().toISOString();const close=lastClosingSnapshot(f);f.closingSnapshot=close||null;for(const p of f.picks||[]){const ok=settlePick(p,h,a);if(ok==null)continue;p.outcome=ok?'WIN':'LOSS';p.pl=p.odds?Number((ok?(p.odds-1):-1).toFixed(2)):null;const closingOdds=Number(close?.odds?.[p.key]);p.closingOdds=Number.isFinite(closingOdds)&&closingOdds>1?closingOdds:null;p.clv=p.odds&&p.closingOdds?Number(((p.odds/p.closingOdds-1)*100).toFixed(2)):null;if(p.clv!=null){clvN++;clvSum+=p.clv}settled++;ok?wins++:losses++}}store.lastSettlement=new Date().toISOString();await writeJson(path,store);return res.status(200).json({ok:true,date,settled,wins,losses,clvSamples:clvN,avgCLV:clvN?Number((clvSum/clvN).toFixed(2)):null})}
async function summary(req,res){if(!storageReady())return res.status(200).json({storageReady:false,summary:{}});const blobs=await listJson('argus/shadow/',120),books=await readManyJson(blobs);let picks=0,settled=0,wins=0,pl=0,priced=0,clvN=0,clvSum=0;const market={};for(const b of books)for(const f of Object.values(b.fixtures||{}))for(const p of f.picks||[]){picks++;if(!market[p.key])market[p.key]={sample:0,settled:0,wins:0,pl:0,clvN:0,clvSum:0};market[p.key].sample++;if(['WIN','LOSS'].includes(p.outcome)){settled++;market[p.key].settled++;if(p.outcome==='WIN'){wins++;market[p.key].wins++}if(Number.isFinite(Number(p.pl))){pl+=Number(p.pl);market[p.key].pl+=Number(p.pl)}if(Number.isFinite(Number(p.clv))){clvN++;clvSum+=Number(p.clv);market[p.key].clvN++;market[p.key].clvSum+=Number(p.clv)}}if(p.odds)priced++}const prof=Object.fromEntries(Object.entries(market).map(([k,v])=>[k,{sample:v.sample,settled:v.settled,wins:v.wins,hitRate:v.settled?Number((v.wins/v.settled*100).toFixed(1)):null,roi:v.settled?Number((v.pl/v.settled*100).toFixed(1)):null,avgCLV:v.clvN?Number((v.clvSum/v.clvN).toFixed(2)):null,clvSamples:v.clvN}]));return res.status(200).json({storageReady:true,summary:{books:books.length,picks,settled,wins,hitRate:settled?Number((wins/settled*100).toFixed(1)):null,priced,flatStakePL:Number(pl.toFixed(2)),roi:settled?Number((pl/settled*100).toFixed(1)):null,avgCLV:clvN?Number((clvSum/clvN).toFixed(2)):null,clvSamples:clvN},market:prof,integrity:'Shadow predictions are frozen before kickoff. Later runs only append timestamped odds snapshots.'})}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method==='POST')return capture(req,res);if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(String(req.query?.mode||'').toLowerCase()==='settle')return settle(req,res);return summary(req,res)}
