import { requestQuery } from './_request-query.js';
import { readJson, storageReady } from './_report-store.js';

const PLAN='argus/autopilot/decision-plan.json';
const TRENDS='argus/research/streak-intelligence.json';
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const up=s=>String(s||'').toUpperCase();
function dateTZ(v=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Brussels',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(v).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`}
function activeToday(r,today){if(!r||r.isLive||['FT','AET','PEN','CANC','ABD','AWD','WO'].includes(r.status))return false;const d=new Date(r.kickoff||0);return Number.isFinite(d.getTime())&&dateTZ(d)===today}
function trendMap(trends){const map=new Map();for(const t of trends||[]){if(!t.playsToday||!t.completeWindow||!t.verifiedCalendarContinuity||n(t.dataCoveragePct)!==100)continue;const k=String(t.team||'').toLowerCase();const a=map.get(k)||[];a.push(t);map.set(k,a)}return map}
function trendEvidence(row,tm){const home=tm.get(String(row.home||'').toLowerCase())||[],away=tm.get(String(row.away||'').toLowerCase())||[],side=up(row.stakeSelection||row.eligibilityCandidate?.side);const support=[],contradictions=[];const h=id=>home.some(t=>t.condition===id&&t.perfect10),a=id=>away.some(t=>t.condition===id&&t.perfect10);if(side==='HOME'){if(h('WIN'))support.push('Home team is 10/10 wins');else if(h('UNBEATEN'))support.push('Home team is 10/10 unbeaten');if(a('WIN'))contradictions.push('Away team is 10/10 wins');else if(a('UNBEATEN'))contradictions.push('Away team is 10/10 unbeaten')}if(side==='AWAY'){if(a('WIN'))support.push('Away team is 10/10 wins');else if(a('UNBEATEN'))support.push('Away team is 10/10 unbeaten');if(h('WIN'))contradictions.push('Home team is 10/10 wins');else if(h('UNBEATEN'))contradictions.push('Home team is 10/10 unbeaten')}if(side==='DRAW'&&(h('WIN')||a('WIN')))contradictions.push('Perfect recent win streak conflicts with draw selection');return{support,contradictions}}
function evaluate(row,tm){const pillars=[],vetoes=[],warnings=[];const side=up(row.stakeSelection||row.eligibilityCandidate?.side),odds=n(row.stakeOdds??row.eligibilityCandidate?.odds,null),edge=n(row.eligibilityCandidate?.edgePct??row.eligibilityCandidate?.edge,null),conf=n(row.netConfidence,null),score=n(row.portfolioRankScore,row.score||0),reg=up(row.marketRegime?.regime||row.marketRegime),learn=up(row.learningStatus),trend=trendEvidence(row,tm);if(row.finalVerdict==='PRIME'&&row.betEligible)pillars.push('PRIME eligibility survived');else vetoes.push('Not an eligible PRIME');if(odds&&odds>1)pillars.push('Real price recorded');else vetoes.push('Real price missing');if(conf>=72)pillars.push(`Confidence ${conf.toFixed(0)}%`);else if(conf<66)vetoes.push('Confidence below survival floor');else warnings.push('Confidence only moderate');if(edge>=5)pillars.push(`Edge ${edge.toFixed(1)}%`);else if(edge<3.5)vetoes.push('Edge too small');else warnings.push('Edge below preferred survival level');if(score>=90)pillars.push(`Decision score ${score.toFixed(0)}`);else if(score<80)vetoes.push('Decision score too low');if(row.preKickoffGate==='PASSED'||row.preKickoffGate==='CONFIRMED')pillars.push('Pre-kickoff gate passed');else if(row.preKickoffGate==='BLOCKED')vetoes.push('Pre-kickoff gate blocked');else warnings.push('Pre-kickoff confirmation incomplete');if(row.lineupsConfirmed)pillars.push('Lineups confirmed');else warnings.push('Lineups not confirmed');if(['VOLATILE','STALE','WIDE'].includes(reg))vetoes.push(`Market regime ${reg}`);else pillars.push('Market regime not adverse');if(['DEGRADED','CAUTION'].includes(learn))vetoes.push(`Ledger learning ${learn}`);else if(learn)pillars.push(`Ledger learning ${learn}`);if(row.portfolioBlocked)vetoes.push('Portfolio risk blocked');if(n(row.matchContext?.regime?.riskScore,0)>=55)vetoes.push('Context regime risk elevated');pillars.push(...trend.support.map(x=>`Trend support: ${x}`));vetoes.push(...trend.contradictions.map(x=>`Trend contradiction: ${x}`));const hardVeto=vetoes.length>0,pillarCount=pillars.length,survivalScore=Math.max(0,Math.min(100,Math.round(55+pillarCount*6-vetoes.length*20-warnings.length*3))),status=!hardVeto&&pillarCount>=7&&survivalScore>=94?'SURVIVING_EDGE':!hardVeto&&pillarCount>=5&&survivalScore>=86?'NEAR_SURVIVAL':'REJECTED';return{fixtureId:row.fixtureId,competition:row.competition,home:row.home,away:row.away,kickoff:row.kickoff,selection:side,odds,confidence:conf,edgePct:edge,decisionScore:score,status,survivalScore,pillarCount,pillars,vetoes,warnings,trendSupport:trend.support,trendContradictions:trend.contradictions,automaticWagering:false}}
export default async function handler(req,res){
  if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});
  if(!storageReady())return res.status(503).json({error:'Storage unavailable'});
  res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=120');
  const today=String(requestQuery(req)?.date||dateTZ()),summaryOnly=String(requestQuery(req)?.mode||'').toLowerCase()==='summary';
  const [plan,tr]=await Promise.all([readJson(PLAN,{generatedAt:null,plan:[]}),readJson(TRENDS,{generatedAt:null,trends:[]})]);
  const tm=trendMap(tr.trends||[]),evaluated=(plan.plan||[]).filter(r=>activeToday(r,today)).map(r=>evaluate(r,tm)).sort((a,b)=>b.survivalScore-a.survivalScore),survivors=evaluated.filter(x=>x.status==='SURVIVING_EDGE'),near=evaluated.filter(x=>x.status==='NEAR_SURVIVAL');
  const report={version:'SURVIVING-EDGE-4',generatedAt:new Date().toISOString(),mode:summaryOnly?'SUMMARY':'FULL',date:today,sourceGeneratedAt:plan.generatedAt||null,trendSourceGeneratedAt:tr.generatedAt||null,summary:{evaluated:evaluated.length,surviving:survivors.length,near:near.length,rejected:evaluated.filter(x=>x.status==='REJECTED').length},survivors,near,policy:{contradictionFirst:true,eligiblePrimeRequired:true,minimumPreferredConfidence:72,minimumPreferredEdgePct:5,hardContradictionsReject:true,trendMaySupportOrVeto:true,trendCannotCreatePrime:true,noGuarantee:true,automaticWagering:false,cacheSeconds:60,persistOnRead:false,rule:'ARGUS tries to falsify a candidate before surfacing it. A SURVIVING EDGE is a highly selective intersection of independent evidence, not a guaranteed win.'}};
  if(!summaryOnly)report.evaluated=evaluated.slice(0,100);
  return res.status(200).json(report);
}
