import { readJson, storageReady } from './_report-store.js';

const ROOT='argus/tactical-memory';
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function normFormation(v){return String(v||'').replace(/[^0-9A-Za-z-]/g,'')||'UNKNOWN'}
function memoryKey(teamId,formation){return `${teamId}:${normFormation(formation)}`}
function summarize(history=[]){const sample=history.length;if(!sample)return{sample:0,confidence:'NONE'};const points=history.reduce((s,x)=>s+n(x.points),0),gf=history.reduce((s,x)=>s+n(x.gf),0),ga=history.reduce((s,x)=>s+n(x.ga),0);return{sample,ppg:points/sample,goalDiff:(gf-ga)/sample,confidence:sample>=15?'HIGH':sample>=8?'MEDIUM':'LOW'}}
async function profile(teamId,formation){if(!storageReady()||!teamId||!formation)return null;const doc=await readJson(`${ROOT}/${teamId}.json`,{formations:{}}),rows=doc.formations?.[memoryKey(teamId,formation)]||[];return summarize(rows)}
function teamDelta(p){if(!p||p.sample<8)return 0;const ppgDelta=(p.ppg-1.5)/1.5,gdDelta=p.goalDiff/2;const blended=.65*ppgDelta+.35*gdDelta;const trust=p.sample>=15?.65:.35;return Math.max(-.08,Math.min(.08,blended*.06*trust))}
function adjust(model,homeDelta,awayDelta){if(!model)return null;let h=n(model.home),d=n(model.draw),a=n(model.away);if(!(h>0&&d>0&&a>0))return null;h=Math.max(.01,h*(1+homeDelta-awayDelta*.35));a=Math.max(.01,a*(1+awayDelta-homeDelta*.35));d=Math.max(.01,d*(1-Math.abs(homeDelta-awayDelta)*.2));const s=h+d+a;return{home:Number((h/s).toFixed(4)),draw:Number((d/s).toFixed(4)),away:Number((a/s).toFixed(4)),source:'ARGUS-TACTICAL-MEMORY'}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],availability=req.body?.availability||{},impact={};for(const m of matches){const av=availability[String(m.id)];if(!av?.lineupsConfirmed)continue;const [homeProfile,awayProfile]=await Promise.all([profile(av.home?.teamId,av.home?.formation),profile(av.away?.teamId,av.away?.formation)]),homeDelta=teamDelta(homeProfile),awayDelta=teamDelta(awayProfile),adjustedModel=adjust(m.preMatchModel,homeDelta,awayDelta);impact[String(m.id)]={fixtureId:m.id,home:{formation:av.home?.formation||null,profile:homeProfile,probabilityDelta:Number((homeDelta*100).toFixed(2))},away:{formation:av.away?.formation||null,profile:awayProfile,probabilityDelta:Number((awayDelta*100).toFixed(2))},adjustedModel,governance:{minimumSample:8,highConfidenceSample:15,maxAbsoluteAdjustmentPct:8,mayCreatePrime:false,mayDowngrade:true}}}return res.status(200).json({version:'TACTICAL-IMPACT-1',generatedAt:new Date().toISOString(),fixtures:Object.keys(impact).length,impact})}
