import { THRESHOLDS, clamp, number as n, uncertaintyBand, downgradeOnlyPolicy } from './_governance-core.js';
function factor(name,score,weight,reason){return{name,score:clamp(score,0,100),weight,reason}}
function assess(m){const factors=[];const fresh=m?.evidenceFreshness||m?.freshness||null,agree=m?.crossSourceAgreement||null,regime=String(m?.marketRegime?.regime||'UNKNOWN').toUpperCase(),movement=String(m?.marketRegime?.directionalStatus||'NEUTRAL').toUpperCase(),decay=m?.signalDecay||null,cal=n(m?.confidenceCalibration?.confidencePenalty,0),basePenalty=n(m?.confidencePenalty,0),lineups=m?.playerImpact?.lineupsConfirmed??null;
 factors.push(factor('FRESHNESS',fresh?.score!=null?100-n(fresh.score):fresh?35:50,.18,fresh?.status||'UNKNOWN'));
 factors.push(factor('CROSS_SOURCE',agree?.score!=null?100-n(agree.score):agree?40:50,.20,agree?.status||'UNKNOWN'));
 let marketRisk=regime==='VOLATILE'?90:regime==='STALE'?95:regime==='WIDE'?70:regime==='MOVING'?35:regime==='STABLE'?15:50;if(movement==='REVERSAL')marketRisk=100;else if(movement==='ADVERSE_STEAM')marketRisk=Math.max(marketRisk,95);else if(movement==='ADVERSE_DRIFT')marketRisk=Math.max(marketRisk,65);factors.push(factor('MARKET',marketRisk,.18,`${regime}/${movement}`));
 const decayRisk=decay?.status==='EXPIRED'?100:decay?.status==='DECAYING'?85:decay?.status==='AGING'?55:decay?.status==='REVALIDATED'?15:35;factors.push(factor('SIGNAL_DECAY',decayRisk,.14,decay?.status||'NEW'));
 factors.push(factor('CALIBRATION',clamp(cal*8,0,100),.10,cal?`penalty ${cal}`:'no penalty'));
 factors.push(factor('ACCUMULATED_PENALTIES',clamp(basePenalty*5,0,100),.10,`penalty ${basePenalty}`));
 const ko=(()=>{const t=new Date(m?.kickoff||0).getTime();return Number.isFinite(t)?Math.round((t-Date.now())/60000):null})();let lineupRisk=25;if(ko!=null&&ko>=0&&ko<=15)lineupRisk=lineups?5:100;else if(ko!=null&&ko<=60)lineupRisk=lineups?10:65;factors.push(factor('LINEUPS',lineupRisk,.10,lineups?'CONFIRMED':'NOT_CONFIRMED'));
 const uncertainty=Math.round(factors.reduce((s,x)=>s+x.score*x.weight,0)),margin=100-uncertainty,band=uncertaintyBand(uncertainty);return{uncertaintyScore:uncertainty,decisionMargin:margin,status:band.status,confidencePenalty:band.penalty,hardBlock:band.hardBlock,factors,governance:downgradeOnlyPolicy({mayDowngrade:true,extremeIsHardVeto:true,highCannotBePrime:true,elevatedRequiresMargin:true,thresholds:THRESHOLDS.uncertainty})}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const matches=Array.isArray(req.body?.matches)?req.body.matches:[],budgets={};for(const m of matches)budgets[String(m.id)]={fixtureId:m.id,...assess(m)};const vals=Object.values(budgets);return res.status(200).json({ok:true,version:'UNCERTAINTY-BUDGET-2',generatedAt:new Date().toISOString(),summary:{total:vals.length,extreme:vals.filter(x=>x.status==='EXTREME').length,high:vals.filter(x=>x.status==='HIGH').length,elevated:vals.filter(x=>x.status==='ELEVATED').length,moderate:vals.filter(x=>x.status==='MODERATE').length,low:vals.filter(x=>x.status==='LOW_UNCERTAINTY').length,hardBlocked:vals.filter(x=>x.hardBlock).length},policy:downgradeOnlyPolicy({extremeHardVeto:true,highCannotRemainPrime:true,positiveMarginCannotPromote:true,thresholds:THRESHOLDS.uncertainty}),budgets})}
